generator:
  class: sfPropelGenerator
  param:
    model_class:           Usuario
    theme:                 admin15
    non_verbose_templates: true
    with_show:             false
    singular:              Usuario
    plural:                Usuarios
    route_prefix:          usuario
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
          usuario: 
              attributes:
                  class: form-control input-medium
              label:       Usuario
          nombre_completo: 
              attributes:
                  class: form-control input-medium
              label:       Nombre Completo
          administrador: 
              attributes:
                  class: form-control input-medium
              label:      Administrador
          clave: 
              attributes:
                  class: form-control input-medium
              label:       Clave
          email: 
              attributes:
                  class: form-control input-medium
              label:       Correo Electronico
          numero_telefono: 
              attributes:
                  class: form-control input-medium
              label:       Número Telefónico
          perfil_id: 
              attributes:
                  class: form-control input-medium
              label:       Perfil
      list: 
        title:   Listado de Usuarios
        display: [usuario,nombre_completo,perfil, email, numero_telefono, activo, administrador]
        object_actions:
          _edit: 
            attributes:  class=btn btn-xs btn-warning
          _delete: 
            attributes:  class=btn btn-xs btn-danger
      filter:
        display: [usuario,nombre_completo,perfil_id,email, numero_telefono, activo]
      form:    ~
      edit: 
        title:   " Edicion de Usuario [%%USUARIO%%]"
        display:  [usuario,nombre_completo, perfil_id, email, numero_telefono, activo, administrador]
      new: 
        title:   Creacion de Usuario
        display:  [usuario, nombre_completo, perfil_id, clave, email, numero_telefono, activo, administrador]
