<?php



/**
 * This class defines the structure of the 'moneda' table.
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Mon Jan 22 00:33:51 2018
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.model.map
 */
class MonedaTableMap extends TableMap
{

    /**
     * The (dot-path) name of this class
     */
    const CLASS_NAME = 'lib.model.map.MonedaTableMap';

    /**
     * Initialize the table attributes, columns and validators
     * Relations are not initialized by this method since they are lazy loaded
     *
     * @return void
     * @throws PropelException
     */
    public function initialize()
    {
        // attributes
        $this->setName('moneda');
        $this->setPhpName('Moneda');
        $this->setClassname('Moneda');
        $this->setPackage('lib.model');
        $this->setUseIdGenerator(true);
        // columns
        $this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
        $this->addColumn('DESCRIPCION', 'Descripcion', 'VARCHAR', false, 255, null);
        $this->getColumn('DESCRIPCION', false)->setPrimaryString(true);
        $this->addColumn('SIMBOLO', 'Simbolo', 'VARCHAR', false, 3, null);
        $this->getColumn('SIMBOLO', false)->setPrimaryString(true);
        $this->addColumn('CODIGO', 'Codigo', 'VARCHAR', false, 3, null);
        $this->getColumn('CODIGO', false)->setPrimaryString(true);
        // validators
    } // initialize()

    /**
     * Build the RelationMap objects for this table relationships
     */
    public function buildRelations()
    {
        $this->addRelation('RequerimientoRelatedByMonedaId', 'Requerimiento', RelationMap::ONE_TO_MANY, array('id' => 'moneda_id', ), null, null, 'RequerimientosRelatedByMonedaId');
        $this->addRelation('RequerimientoRelatedByMonedaIngreso', 'Requerimiento', RelationMap::ONE_TO_MANY, array('id' => 'moneda_ingreso', ), null, null, 'RequerimientosRelatedByMonedaIngreso');
        $this->addRelation('RequerimientoRelatedByMonedaEgresos', 'Requerimiento', RelationMap::ONE_TO_MANY, array('id' => 'moneda_egresos', ), null, null, 'RequerimientosRelatedByMonedaEgresos');
        $this->addRelation('Propiedad', 'Propiedad', RelationMap::ONE_TO_MANY, array('id' => 'moneda_id', ), null, null, 'Propiedads');
    } // buildRelations()

    /**
     *
     * Gets the list of behaviors registered for this table
     *
     * @return array Associative array (name => parameters) of behaviors
     */
    public function getBehaviors()
    {
        return array(
            'symfony' => array('form' => 'true', 'filter' => 'true', ),
            'symfony_behaviors' => array(),
        );
    } // getBehaviors()

} // MonedaTableMap
