<?php



/**
 * This class defines the structure of the 'propiedad' table.
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * 12/27/17 04:11:30
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.model.map
 */
class PropiedadTableMap extends TableMap
{

    /**
     * The (dot-path) name of this class
     */
    const CLASS_NAME = 'lib.model.map.PropiedadTableMap';

    /**
     * Initialize the table attributes, columns and validators
     * Relations are not initialized by this method since they are lazy loaded
     *
     * @return void
     * @throws PropelException
     */
    public function initialize()
    {
        // attributes
        $this->setName('propiedad');
        $this->setPhpName('Propiedad');
        $this->setClassname('Propiedad');
        $this->setPackage('lib.model');
        $this->setUseIdGenerator(true);
        // columns
        $this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
        $this->addColumn('TIPO_OPERACION', 'TipoOperacion', 'VARCHAR', false, 32, null);
        $this->addColumn('TIPO_INMUEBLE', 'TipoInmueble', 'VARCHAR', false, 32, null);
        $this->addColumn('CANTIDAD_HABITACION', 'CantidadHabitacion', 'INTEGER', false, null, null);
        $this->addColumn('CANTIDAD_BANIO', 'CantidadBanio', 'INTEGER', false, null, null);
        $this->addColumn('CANTIDAD_PARQUEO', 'CantidadParqueo', 'INTEGER', false, null, null);
        $this->addColumn('CANTIDAD_COMEDOR', 'CantidadComedor', 'INTEGER', false, null, null);
        $this->addColumn('CANTIDAD_SALA', 'CantidadSala', 'INTEGER', false, null, null);
        $this->addColumn('CANTIDAD_COCINA', 'CantidadCocina', 'INTEGER', false, null, null);
        $this->addColumn('DORMITORIO_SERVICIO', 'DormitorioServicio', 'BOOLEAN', false, 1, false);
        $this->addColumn('ESTUDIO', 'Estudio', 'BOOLEAN', false, 1, false);
        $this->addColumn('CISTERNA', 'Cisterna', 'BOOLEAN', false, 1, false);
        $this->addColumn('CANTIDAD_JARDIN', 'CantidadJardin', 'INTEGER', false, null, null);
        $this->addColumn('CANTIDAD_PATIO', 'CantidadPatio', 'INTEGER', false, null, null);
        $this->addColumn('LAVANDERIA', 'Lavanderia', 'BOOLEAN', false, 1, false);
        $this->addColumn('ESTADO', 'Estado', 'VARCHAR', false, 32, null);
        $this->addColumn('AMENIDADES', 'Amenidades', 'VARCHAR', false, 255, null);
        $this->addColumn('PRECIO', 'Precio', 'DOUBLE', false, null, null);
        $this->addColumn('NEGOCIABLE', 'Negociable', 'BOOLEAN', false, 1, false);
        $this->addColumn('INCLUYE_GASTOS_ESCRITURA', 'IncluyeGastosEscritura', 'BOOLEAN', false, 1, false);
        $this->addColumn('ANIO_CONSTRUCCION', 'AnioConstruccion', 'INTEGER', false, null, null);
        $this->addColumn('MANTENIMIENTO_MENSUAL', 'MantenimientoMensual', 'DOUBLE', false, null, null);
        $this->addColumn('IUSI_SEMESTRAL', 'IusiSemestral', 'DOUBLE', false, null, null);
        $this->addColumn('VALOR_AVALUO', 'ValorAvaluo', 'DOUBLE', false, null, null);
        $this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
        $this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
        $this->addColumn('CREATED_BY', 'CreatedBy', 'VARCHAR', false, 32, null);
        $this->addColumn('UPDATED_BY', 'UpdatedBy', 'VARCHAR', false, 32, null);
        // validators
    } // initialize()

    /**
     * Build the RelationMap objects for this table relationships
     */
    public function buildRelations()
    {
    } // buildRelations()

    /**
     *
     * Gets the list of behaviors registered for this table
     *
     * @return array Associative array (name => parameters) of behaviors
     */
    public function getBehaviors()
    {
        return array(
            'symfony' => array('form' => 'true', 'filter' => 'true', ),
            'symfony_behaviors' => array(),
            'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
        );
    } // getBehaviors()

} // PropiedadTableMap
