<?php



/**
 * This class defines the structure of the 'tasa_cambio' table.
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Fri Jan 26 12:36:05 2018
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.model.map
 */
class TasaCambioTableMap extends TableMap
{

    /**
     * The (dot-path) name of this class
     */
    const CLASS_NAME = 'lib.model.map.TasaCambioTableMap';

    /**
     * Initialize the table attributes, columns and validators
     * Relations are not initialized by this method since they are lazy loaded
     *
     * @return void
     * @throws PropelException
     */
    public function initialize()
    {
        // attributes
        $this->setName('tasa_cambio');
        $this->setPhpName('TasaCambio');
        $this->setClassname('TasaCambio');
        $this->setPackage('lib.model');
        $this->setUseIdGenerator(true);
        // columns
        $this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
        $this->addForeignKey('MONEDA_ORIGEN', 'MonedaOrigen', 'INTEGER', 'moneda', 'ID', true, null, null);
        $this->addForeignKey('MONEDA_DESTINO', 'MonedaDestino', 'INTEGER', 'moneda', 'ID', true, null, null);
        $this->addColumn('MONTO', 'Monto', 'FLOAT', false, null, null);
        // validators
    } // initialize()

    /**
     * Build the RelationMap objects for this table relationships
     */
    public function buildRelations()
    {
        $this->addRelation('MonedaRelatedByMonedaOrigen', 'Moneda', RelationMap::MANY_TO_ONE, array('moneda_origen' => 'id', ), null, null);
        $this->addRelation('MonedaRelatedByMonedaDestino', 'Moneda', RelationMap::MANY_TO_ONE, array('moneda_destino' => 'id', ), null, null);
    } // buildRelations()

    /**
     *
     * Gets the list of behaviors registered for this table
     *
     * @return array Associative array (name => parameters) of behaviors
     */
    public function getBehaviors()
    {
        return array(
            'symfony' => array('form' => 'true', 'filter' => 'true', ),
            'symfony_behaviors' => array(),
        );
    } // getBehaviors()

} // TasaCambioTableMap
