<?php


/**
 * Base class that represents a row from the 'moneda' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Mon Mar  5 02:41:00 2018
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseMoneda extends BaseObject implements Persistent
{
    /**
     * Peer class name
     */
    const PEER = 'MonedaPeer';

    /**
     * The Peer class.
     * Instance provides a convenient way of calling static methods on a class
     * that calling code may not be able to identify.
     * @var        MonedaPeer
     */
    protected static $peer;

    /**
     * The flag var to prevent infinit loop in deep copy
     * @var       boolean
     */
    protected $startCopy = false;

    /**
     * The value for the id field.
     * @var        int
     */
    protected $id;

    /**
     * The value for the descripcion field.
     * @var        string
     */
    protected $descripcion;

    /**
     * The value for the simbolo field.
     * @var        string
     */
    protected $simbolo;

    /**
     * The value for the codigo field.
     * @var        string
     */
    protected $codigo;

    /**
     * @var        PropelObjectCollection|Requerimiento[] Collection to store aggregation of Requerimiento objects.
     */
    protected $collRequerimientos;
    protected $collRequerimientosPartial;

    /**
     * @var        PropelObjectCollection|Propiedad[] Collection to store aggregation of Propiedad objects.
     */
    protected $collPropiedads;
    protected $collPropiedadsPartial;

    /**
     * @var        PropelObjectCollection|TasaCambio[] Collection to store aggregation of TasaCambio objects.
     */
    protected $collTasaCambiosRelatedByMonedaOrigen;
    protected $collTasaCambiosRelatedByMonedaOrigenPartial;

    /**
     * @var        PropelObjectCollection|TasaCambio[] Collection to store aggregation of TasaCambio objects.
     */
    protected $collTasaCambiosRelatedByMonedaDestino;
    protected $collTasaCambiosRelatedByMonedaDestinoPartial;

    /**
     * Flag to prevent endless save loop, if this object is referenced
     * by another object which falls in this transaction.
     * @var        boolean
     */
    protected $alreadyInSave = false;

    /**
     * Flag to prevent endless validation loop, if this object is referenced
     * by another object which falls in this transaction.
     * @var        boolean
     */
    protected $alreadyInValidation = false;

    /**
     * An array of objects scheduled for deletion.
     * @var		PropelObjectCollection
     */
    protected $requerimientosScheduledForDeletion = null;

    /**
     * An array of objects scheduled for deletion.
     * @var		PropelObjectCollection
     */
    protected $propiedadsScheduledForDeletion = null;

    /**
     * An array of objects scheduled for deletion.
     * @var		PropelObjectCollection
     */
    protected $tasaCambiosRelatedByMonedaOrigenScheduledForDeletion = null;

    /**
     * An array of objects scheduled for deletion.
     * @var		PropelObjectCollection
     */
    protected $tasaCambiosRelatedByMonedaDestinoScheduledForDeletion = null;

    /**
     * Get the [id] column value.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get the [descripcion] column value.
     *
     * @return string
     */
    public function getDescripcion()
    {
        return $this->descripcion;
    }

    /**
     * Get the [simbolo] column value.
     *
     * @return string
     */
    public function getSimbolo()
    {
        return $this->simbolo;
    }

    /**
     * Get the [codigo] column value.
     *
     * @return string
     */
    public function getCodigo()
    {
        return $this->codigo;
    }

    /**
     * Set the value of [id] column.
     *
     * @param int $v new value
     * @return Moneda The current object (for fluent API support)
     */
    public function setId($v)
    {
        if ($v !== null) {
            $v = (int) $v;
        }

        if ($this->id !== $v) {
            $this->id = $v;
            $this->modifiedColumns[] = MonedaPeer::ID;
        }


        return $this;
    } // setId()

    /**
     * Set the value of [descripcion] column.
     *
     * @param string $v new value
     * @return Moneda The current object (for fluent API support)
     */
    public function setDescripcion($v)
    {
        if ($v !== null) {
            $v = (string) $v;
        }

        if ($this->descripcion !== $v) {
            $this->descripcion = $v;
            $this->modifiedColumns[] = MonedaPeer::DESCRIPCION;
        }


        return $this;
    } // setDescripcion()

    /**
     * Set the value of [simbolo] column.
     *
     * @param string $v new value
     * @return Moneda The current object (for fluent API support)
     */
    public function setSimbolo($v)
    {
        if ($v !== null) {
            $v = (string) $v;
        }

        if ($this->simbolo !== $v) {
            $this->simbolo = $v;
            $this->modifiedColumns[] = MonedaPeer::SIMBOLO;
        }


        return $this;
    } // setSimbolo()

    /**
     * Set the value of [codigo] column.
     *
     * @param string $v new value
     * @return Moneda The current object (for fluent API support)
     */
    public function setCodigo($v)
    {
        if ($v !== null) {
            $v = (string) $v;
        }

        if ($this->codigo !== $v) {
            $this->codigo = $v;
            $this->modifiedColumns[] = MonedaPeer::CODIGO;
        }


        return $this;
    } // setCodigo()

    /**
     * Indicates whether the columns in this object are only set to default values.
     *
     * This method can be used in conjunction with isModified() to indicate whether an object is both
     * modified _and_ has some values set which are non-default.
     *
     * @return boolean Whether the columns in this object are only been set with default values.
     */
    public function hasOnlyDefaultValues()
    {
        // otherwise, everything was equal, so return true
        return true;
    } // hasOnlyDefaultValues()

    /**
     * Hydrates (populates) the object variables with values from the database resultset.
     *
     * An offset (0-based "start column") is specified so that objects can be hydrated
     * with a subset of the columns in the resultset rows.  This is needed, for example,
     * for results of JOIN queries where the resultset row includes columns from two or
     * more tables.
     *
     * @param array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
     * @param int $startcol 0-based offset column which indicates which restultset column to start with.
     * @param boolean $rehydrate Whether this object is being re-hydrated from the database.
     * @return int             next starting column
     * @throws PropelException - Any caught Exception will be rewrapped as a PropelException.
     */
    public function hydrate($row, $startcol = 0, $rehydrate = false)
    {
        try {

            $this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
            $this->descripcion = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
            $this->simbolo = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
            $this->codigo = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
            $this->resetModified();

            $this->setNew(false);

            if ($rehydrate) {
                $this->ensureConsistency();
            }

            return $startcol + 4; // 4 = MonedaPeer::NUM_HYDRATE_COLUMNS.

        } catch (Exception $e) {
            throw new PropelException("Error populating Moneda object", $e);
        }
    }

    /**
     * Checks and repairs the internal consistency of the object.
     *
     * This method is executed after an already-instantiated object is re-hydrated
     * from the database.  It exists to check any foreign keys to make sure that
     * the objects related to the current object are correct based on foreign key.
     *
     * You can override this method in the stub class, but you should always invoke
     * the base method from the overridden method (i.e. parent::ensureConsistency()),
     * in case your model changes.
     *
     * @throws PropelException
     */
    public function ensureConsistency()
    {

    } // ensureConsistency

    /**
     * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
     *
     * This will only work if the object has been saved and has a valid primary key set.
     *
     * @param boolean $deep (optional) Whether to also de-associated any related objects.
     * @param PropelPDO $con (optional) The PropelPDO connection to use.
     * @return void
     * @throws PropelException - if this object is deleted, unsaved or doesn't have pk match in db
     */
    public function reload($deep = false, PropelPDO $con = null)
    {
        if ($this->isDeleted()) {
            throw new PropelException("Cannot reload a deleted object.");
        }

        if ($this->isNew()) {
            throw new PropelException("Cannot reload an unsaved object.");
        }

        if ($con === null) {
            $con = Propel::getConnection(MonedaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

        // We don't need to alter the object instance pool; we're just modifying this instance
        // already in the pool.

        $stmt = MonedaPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
        $row = $stmt->fetch(PDO::FETCH_NUM);
        $stmt->closeCursor();
        if (!$row) {
            throw new PropelException('Cannot find matching row in the database to reload object values.');
        }
        $this->hydrate($row, 0, true); // rehydrate

        if ($deep) {  // also de-associate any related objects?

            $this->collRequerimientos = null;

            $this->collPropiedads = null;

            $this->collTasaCambiosRelatedByMonedaOrigen = null;

            $this->collTasaCambiosRelatedByMonedaDestino = null;

        } // if (deep)
    }

    /**
     * Removes this object from datastore and sets delete attribute.
     *
     * @param PropelPDO $con
     * @return void
     * @throws PropelException
     * @throws Exception
     * @see        BaseObject::setDeleted()
     * @see        BaseObject::isDeleted()
     */
    public function delete(PropelPDO $con = null)
    {
        if ($this->isDeleted()) {
            throw new PropelException("This object has already been deleted.");
        }

        if ($con === null) {
            $con = Propel::getConnection(MonedaPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        $con->beginTransaction();
        try {
            $deleteQuery = MonedaQuery::create()
                ->filterByPrimaryKey($this->getPrimaryKey());
            $ret = $this->preDelete($con);
            // symfony_behaviors behavior
            foreach (sfMixer::getCallables('BaseMoneda:delete:pre') as $callable)
            {
              if (call_user_func($callable, $this, $con))
              {
                $con->commit();
                return;
              }
            }

            if ($ret) {
                $deleteQuery->delete($con);
                $this->postDelete($con);
                // symfony_behaviors behavior
                foreach (sfMixer::getCallables('BaseMoneda:delete:post') as $callable)
                {
                  call_user_func($callable, $this, $con);
                }

                $con->commit();
                $this->setDeleted(true);
            } else {
                $con->commit();
            }
        } catch (Exception $e) {
            $con->rollBack();
            throw $e;
        }
    }

    /**
     * Persists this object to the database.
     *
     * If the object is new, it inserts it; otherwise an update is performed.
     * All modified related objects will also be persisted in the doSave()
     * method.  This method wraps all precipitate database operations in a
     * single transaction.
     *
     * @param PropelPDO $con
     * @return int             The number of rows affected by this insert/update and any referring fk objects' save() operations.
     * @throws PropelException
     * @throws Exception
     * @see        doSave()
     */
    public function save(PropelPDO $con = null)
    {
        if ($this->isDeleted()) {
            throw new PropelException("You cannot save an object that has been deleted.");
        }

        if ($con === null) {
            $con = Propel::getConnection(MonedaPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        $con->beginTransaction();
        $isInsert = $this->isNew();
        try {
            $ret = $this->preSave($con);
            // symfony_behaviors behavior
            foreach (sfMixer::getCallables('BaseMoneda:save:pre') as $callable)
            {
              if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
              {
                  $con->commit();
                return $affectedRows;
              }
            }

            if ($isInsert) {
                $ret = $ret && $this->preInsert($con);
            } else {
                $ret = $ret && $this->preUpdate($con);
            }
            if ($ret) {
                $affectedRows = $this->doSave($con);
                if ($isInsert) {
                    $this->postInsert($con);
                } else {
                    $this->postUpdate($con);
                }
                $this->postSave($con);
                // symfony_behaviors behavior
                foreach (sfMixer::getCallables('BaseMoneda:save:post') as $callable)
                {
                  call_user_func($callable, $this, $con, $affectedRows);
                }

                MonedaPeer::addInstanceToPool($this);
            } else {
                $affectedRows = 0;
            }
            $con->commit();

            return $affectedRows;
        } catch (Exception $e) {
            $con->rollBack();
            throw $e;
        }
    }

    /**
     * Performs the work of inserting or updating the row in the database.
     *
     * If the object is new, it inserts it; otherwise an update is performed.
     * All related objects are also updated in this method.
     *
     * @param PropelPDO $con
     * @return int             The number of rows affected by this insert/update and any referring fk objects' save() operations.
     * @throws PropelException
     * @see        save()
     */
    protected function doSave(PropelPDO $con)
    {
        $affectedRows = 0; // initialize var to track total num of affected rows
        if (!$this->alreadyInSave) {
            $this->alreadyInSave = true;

            if ($this->isNew() || $this->isModified()) {
                // persist changes
                if ($this->isNew()) {
                    $this->doInsert($con);
                } else {
                    $this->doUpdate($con);
                }
                $affectedRows += 1;
                $this->resetModified();
            }

            if ($this->requerimientosScheduledForDeletion !== null) {
                if (!$this->requerimientosScheduledForDeletion->isEmpty()) {
                    RequerimientoQuery::create()
                        ->filterByPrimaryKeys($this->requerimientosScheduledForDeletion->getPrimaryKeys(false))
                        ->delete($con);
                    $this->requerimientosScheduledForDeletion = null;
                }
            }

            if ($this->collRequerimientos !== null) {
                foreach ($this->collRequerimientos as $referrerFK) {
                    if (!$referrerFK->isDeleted()) {
                        $affectedRows += $referrerFK->save($con);
                    }
                }
            }

            if ($this->propiedadsScheduledForDeletion !== null) {
                if (!$this->propiedadsScheduledForDeletion->isEmpty()) {
                    PropiedadQuery::create()
                        ->filterByPrimaryKeys($this->propiedadsScheduledForDeletion->getPrimaryKeys(false))
                        ->delete($con);
                    $this->propiedadsScheduledForDeletion = null;
                }
            }

            if ($this->collPropiedads !== null) {
                foreach ($this->collPropiedads as $referrerFK) {
                    if (!$referrerFK->isDeleted()) {
                        $affectedRows += $referrerFK->save($con);
                    }
                }
            }

            if ($this->tasaCambiosRelatedByMonedaOrigenScheduledForDeletion !== null) {
                if (!$this->tasaCambiosRelatedByMonedaOrigenScheduledForDeletion->isEmpty()) {
                    TasaCambioQuery::create()
                        ->filterByPrimaryKeys($this->tasaCambiosRelatedByMonedaOrigenScheduledForDeletion->getPrimaryKeys(false))
                        ->delete($con);
                    $this->tasaCambiosRelatedByMonedaOrigenScheduledForDeletion = null;
                }
            }

            if ($this->collTasaCambiosRelatedByMonedaOrigen !== null) {
                foreach ($this->collTasaCambiosRelatedByMonedaOrigen as $referrerFK) {
                    if (!$referrerFK->isDeleted()) {
                        $affectedRows += $referrerFK->save($con);
                    }
                }
            }

            if ($this->tasaCambiosRelatedByMonedaDestinoScheduledForDeletion !== null) {
                if (!$this->tasaCambiosRelatedByMonedaDestinoScheduledForDeletion->isEmpty()) {
                    TasaCambioQuery::create()
                        ->filterByPrimaryKeys($this->tasaCambiosRelatedByMonedaDestinoScheduledForDeletion->getPrimaryKeys(false))
                        ->delete($con);
                    $this->tasaCambiosRelatedByMonedaDestinoScheduledForDeletion = null;
                }
            }

            if ($this->collTasaCambiosRelatedByMonedaDestino !== null) {
                foreach ($this->collTasaCambiosRelatedByMonedaDestino as $referrerFK) {
                    if (!$referrerFK->isDeleted()) {
                        $affectedRows += $referrerFK->save($con);
                    }
                }
            }

            $this->alreadyInSave = false;

        }

        return $affectedRows;
    } // doSave()

    /**
     * Insert the row in the database.
     *
     * @param PropelPDO $con
     *
     * @throws PropelException
     * @see        doSave()
     */
    protected function doInsert(PropelPDO $con)
    {
        $modifiedColumns = array();
        $index = 0;

        $this->modifiedColumns[] = MonedaPeer::ID;
        if (null !== $this->id) {
            throw new PropelException('Cannot insert a value for auto-increment primary key (' . MonedaPeer::ID . ')');
        }

         // check the columns in natural order for more readable SQL queries
        if ($this->isColumnModified(MonedaPeer::ID)) {
            $modifiedColumns[':p' . $index++]  = '`ID`';
        }
        if ($this->isColumnModified(MonedaPeer::DESCRIPCION)) {
            $modifiedColumns[':p' . $index++]  = '`DESCRIPCION`';
        }
        if ($this->isColumnModified(MonedaPeer::SIMBOLO)) {
            $modifiedColumns[':p' . $index++]  = '`SIMBOLO`';
        }
        if ($this->isColumnModified(MonedaPeer::CODIGO)) {
            $modifiedColumns[':p' . $index++]  = '`CODIGO`';
        }

        $sql = sprintf(
            'INSERT INTO `moneda` (%s) VALUES (%s)',
            implode(', ', $modifiedColumns),
            implode(', ', array_keys($modifiedColumns))
        );

        try {
            $stmt = $con->prepare($sql);
            foreach ($modifiedColumns as $identifier => $columnName) {
                switch ($columnName) {
                    case '`ID`':
                        $stmt->bindValue($identifier, $this->id, PDO::PARAM_INT);
                        break;
                    case '`DESCRIPCION`':
                        $stmt->bindValue($identifier, $this->descripcion, PDO::PARAM_STR);
                        break;
                    case '`SIMBOLO`':
                        $stmt->bindValue($identifier, $this->simbolo, PDO::PARAM_STR);
                        break;
                    case '`CODIGO`':
                        $stmt->bindValue($identifier, $this->codigo, PDO::PARAM_STR);
                        break;
                }
            }
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute INSERT statement [%s]', $sql), $e);
        }

        try {
            $pk = $con->lastInsertId();
        } catch (Exception $e) {
            throw new PropelException('Unable to get autoincrement id.', $e);
        }
        $this->setId($pk);

        $this->setNew(false);
    }

    /**
     * Update the row in the database.
     *
     * @param PropelPDO $con
     *
     * @see        doSave()
     */
    protected function doUpdate(PropelPDO $con)
    {
        $selectCriteria = $this->buildPkeyCriteria();
        $valuesCriteria = $this->buildCriteria();
        BasePeer::doUpdate($selectCriteria, $valuesCriteria, $con);
    }

    /**
     * Array of ValidationFailed objects.
     * @var        array ValidationFailed[]
     */
    protected $validationFailures = array();

    /**
     * Gets any ValidationFailed objects that resulted from last call to validate().
     *
     *
     * @return array ValidationFailed[]
     * @see        validate()
     */
    public function getValidationFailures()
    {
        return $this->validationFailures;
    }

    /**
     * Validates the objects modified field values and all objects related to this table.
     *
     * If $columns is either a column name or an array of column names
     * only those columns are validated.
     *
     * @param mixed $columns Column name or an array of column names.
     * @return boolean Whether all columns pass validation.
     * @see        doValidate()
     * @see        getValidationFailures()
     */
    public function validate($columns = null)
    {
        $res = $this->doValidate($columns);
        if ($res === true) {
            $this->validationFailures = array();

            return true;
        } else {
            $this->validationFailures = $res;

            return false;
        }
    }

    /**
     * This function performs the validation work for complex object models.
     *
     * In addition to checking the current object, all related objects will
     * also be validated.  If all pass then <code>true</code> is returned; otherwise
     * an aggreagated array of ValidationFailed objects will be returned.
     *
     * @param array $columns Array of column names to validate.
     * @return mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
     */
    protected function doValidate($columns = null)
    {
        if (!$this->alreadyInValidation) {
            $this->alreadyInValidation = true;
            $retval = null;

            $failureMap = array();


            if (($retval = MonedaPeer::doValidate($this, $columns)) !== true) {
                $failureMap = array_merge($failureMap, $retval);
            }


                if ($this->collRequerimientos !== null) {
                    foreach ($this->collRequerimientos as $referrerFK) {
                        if (!$referrerFK->validate($columns)) {
                            $failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
                        }
                    }
                }

                if ($this->collPropiedads !== null) {
                    foreach ($this->collPropiedads as $referrerFK) {
                        if (!$referrerFK->validate($columns)) {
                            $failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
                        }
                    }
                }

                if ($this->collTasaCambiosRelatedByMonedaOrigen !== null) {
                    foreach ($this->collTasaCambiosRelatedByMonedaOrigen as $referrerFK) {
                        if (!$referrerFK->validate($columns)) {
                            $failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
                        }
                    }
                }

                if ($this->collTasaCambiosRelatedByMonedaDestino !== null) {
                    foreach ($this->collTasaCambiosRelatedByMonedaDestino as $referrerFK) {
                        if (!$referrerFK->validate($columns)) {
                            $failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
                        }
                    }
                }


            $this->alreadyInValidation = false;
        }

        return (!empty($failureMap) ? $failureMap : true);
    }

    /**
     * Retrieves a field from the object by name passed in as a string.
     *
     * @param string $name name
     * @param string $type The type of fieldname the $name is of:
     *               one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
     *               BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     *               Defaults to BasePeer::TYPE_PHPNAME
     * @return mixed Value of field.
     */
    public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
    {
        $pos = MonedaPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
        $field = $this->getByPosition($pos);

        return $field;
    }

    /**
     * Retrieves a field from the object by Position as specified in the xml schema.
     * Zero-based.
     *
     * @param int $pos position in xml schema
     * @return mixed Value of field at $pos
     */
    public function getByPosition($pos)
    {
        switch ($pos) {
            case 0:
                return $this->getId();
                break;
            case 1:
                return $this->getDescripcion();
                break;
            case 2:
                return $this->getSimbolo();
                break;
            case 3:
                return $this->getCodigo();
                break;
            default:
                return null;
                break;
        } // switch()
    }

    /**
     * Exports the object as an array.
     *
     * You can specify the key type of the array by passing one of the class
     * type constants.
     *
     * @param     string  $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
     *                    BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     *                    Defaults to BasePeer::TYPE_PHPNAME.
     * @param     boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns. Defaults to true.
     * @param     array $alreadyDumpedObjects List of objects to skip to avoid recursion
     * @param     boolean $includeForeignObjects (optional) Whether to include hydrated related objects. Default to FALSE.
     *
     * @return array an associative array containing the field names (as keys) and field values
     */
    public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true, $alreadyDumpedObjects = array(), $includeForeignObjects = false)
    {
        if (isset($alreadyDumpedObjects['Moneda'][$this->getPrimaryKey()])) {
            return '*RECURSION*';
        }
        $alreadyDumpedObjects['Moneda'][$this->getPrimaryKey()] = true;
        $keys = MonedaPeer::getFieldNames($keyType);
        $result = array(
            $keys[0] => $this->getId(),
            $keys[1] => $this->getDescripcion(),
            $keys[2] => $this->getSimbolo(),
            $keys[3] => $this->getCodigo(),
        );
        if ($includeForeignObjects) {
            if (null !== $this->collRequerimientos) {
                $result['Requerimientos'] = $this->collRequerimientos->toArray(null, true, $keyType, $includeLazyLoadColumns, $alreadyDumpedObjects);
            }
            if (null !== $this->collPropiedads) {
                $result['Propiedads'] = $this->collPropiedads->toArray(null, true, $keyType, $includeLazyLoadColumns, $alreadyDumpedObjects);
            }
            if (null !== $this->collTasaCambiosRelatedByMonedaOrigen) {
                $result['TasaCambiosRelatedByMonedaOrigen'] = $this->collTasaCambiosRelatedByMonedaOrigen->toArray(null, true, $keyType, $includeLazyLoadColumns, $alreadyDumpedObjects);
            }
            if (null !== $this->collTasaCambiosRelatedByMonedaDestino) {
                $result['TasaCambiosRelatedByMonedaDestino'] = $this->collTasaCambiosRelatedByMonedaDestino->toArray(null, true, $keyType, $includeLazyLoadColumns, $alreadyDumpedObjects);
            }
        }

        return $result;
    }

    /**
     * Sets a field from the object by name passed in as a string.
     *
     * @param string $name peer name
     * @param mixed $value field value
     * @param string $type The type of fieldname the $name is of:
     *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
     *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     *                     Defaults to BasePeer::TYPE_PHPNAME
     * @return void
     */
    public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
    {
        $pos = MonedaPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);

        $this->setByPosition($pos, $value);
    }

    /**
     * Sets a field from the object by Position as specified in the xml schema.
     * Zero-based.
     *
     * @param int $pos position in xml schema
     * @param mixed $value field value
     * @return void
     */
    public function setByPosition($pos, $value)
    {
        switch ($pos) {
            case 0:
                $this->setId($value);
                break;
            case 1:
                $this->setDescripcion($value);
                break;
            case 2:
                $this->setSimbolo($value);
                break;
            case 3:
                $this->setCodigo($value);
                break;
        } // switch()
    }

    /**
     * Populates the object using an array.
     *
     * This is particularly useful when populating an object from one of the
     * request arrays (e.g. $_POST).  This method goes through the column
     * names, checking to see whether a matching key exists in populated
     * array. If so the setByName() method is called for that column.
     *
     * You can specify the key type of the array by additionally passing one
     * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
     * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     * The default key type is the column's BasePeer::TYPE_PHPNAME
     *
     * @param array  $arr     An array to populate the object from.
     * @param string $keyType The type of keys the array uses.
     * @return void
     */
    public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
    {
        $keys = MonedaPeer::getFieldNames($keyType);

        if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
        if (array_key_exists($keys[1], $arr)) $this->setDescripcion($arr[$keys[1]]);
        if (array_key_exists($keys[2], $arr)) $this->setSimbolo($arr[$keys[2]]);
        if (array_key_exists($keys[3], $arr)) $this->setCodigo($arr[$keys[3]]);
    }

    /**
     * Build a Criteria object containing the values of all modified columns in this object.
     *
     * @return Criteria The Criteria object containing all modified values.
     */
    public function buildCriteria()
    {
        $criteria = new Criteria(MonedaPeer::DATABASE_NAME);

        if ($this->isColumnModified(MonedaPeer::ID)) $criteria->add(MonedaPeer::ID, $this->id);
        if ($this->isColumnModified(MonedaPeer::DESCRIPCION)) $criteria->add(MonedaPeer::DESCRIPCION, $this->descripcion);
        if ($this->isColumnModified(MonedaPeer::SIMBOLO)) $criteria->add(MonedaPeer::SIMBOLO, $this->simbolo);
        if ($this->isColumnModified(MonedaPeer::CODIGO)) $criteria->add(MonedaPeer::CODIGO, $this->codigo);

        return $criteria;
    }

    /**
     * Builds a Criteria object containing the primary key for this object.
     *
     * Unlike buildCriteria() this method includes the primary key values regardless
     * of whether or not they have been modified.
     *
     * @return Criteria The Criteria object containing value(s) for primary key(s).
     */
    public function buildPkeyCriteria()
    {
        $criteria = new Criteria(MonedaPeer::DATABASE_NAME);
        $criteria->add(MonedaPeer::ID, $this->id);

        return $criteria;
    }

    /**
     * Returns the primary key for this object (row).
     * @return int
     */
    public function getPrimaryKey()
    {
        return $this->getId();
    }

    /**
     * Generic method to set the primary key (id column).
     *
     * @param  int $key Primary key.
     * @return void
     */
    public function setPrimaryKey($key)
    {
        $this->setId($key);
    }

    /**
     * Returns true if the primary key for this object is null.
     * @return boolean
     */
    public function isPrimaryKeyNull()
    {

        return null === $this->getId();
    }

    /**
     * Sets contents of passed object to values from current object.
     *
     * If desired, this method can also make copies of all associated (fkey referrers)
     * objects.
     *
     * @param object $copyObj An object of Moneda (or compatible) type.
     * @param boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
     * @param boolean $makeNew Whether to reset autoincrement PKs and make the object new.
     * @throws PropelException
     */
    public function copyInto($copyObj, $deepCopy = false, $makeNew = true)
    {
        $copyObj->setDescripcion($this->getDescripcion());
        $copyObj->setSimbolo($this->getSimbolo());
        $copyObj->setCodigo($this->getCodigo());

        if ($deepCopy && !$this->startCopy) {
            // important: temporarily setNew(false) because this affects the behavior of
            // the getter/setter methods for fkey referrer objects.
            $copyObj->setNew(false);
            // store object hash to prevent cycle
            $this->startCopy = true;

            foreach ($this->getRequerimientos() as $relObj) {
                if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
                    $copyObj->addRequerimiento($relObj->copy($deepCopy));
                }
            }

            foreach ($this->getPropiedads() as $relObj) {
                if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
                    $copyObj->addPropiedad($relObj->copy($deepCopy));
                }
            }

            foreach ($this->getTasaCambiosRelatedByMonedaOrigen() as $relObj) {
                if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
                    $copyObj->addTasaCambioRelatedByMonedaOrigen($relObj->copy($deepCopy));
                }
            }

            foreach ($this->getTasaCambiosRelatedByMonedaDestino() as $relObj) {
                if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
                    $copyObj->addTasaCambioRelatedByMonedaDestino($relObj->copy($deepCopy));
                }
            }

            //unflag object copy
            $this->startCopy = false;
        } // if ($deepCopy)

        if ($makeNew) {
            $copyObj->setNew(true);
            $copyObj->setId(NULL); // this is a auto-increment column, so set to default value
        }
    }

    /**
     * Makes a copy of this object that will be inserted as a new row in table when saved.
     * It creates a new object filling in the simple attributes, but skipping any primary
     * keys that are defined for the table.
     *
     * If desired, this method can also make copies of all associated (fkey referrers)
     * objects.
     *
     * @param boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
     * @return Moneda Clone of current object.
     * @throws PropelException
     */
    public function copy($deepCopy = false)
    {
        // we use get_class(), because this might be a subclass
        $clazz = get_class($this);
        $copyObj = new $clazz();
        $this->copyInto($copyObj, $deepCopy);

        return $copyObj;
    }

    /**
     * Returns a peer instance associated with this om.
     *
     * Since Peer classes are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     *
     * @return MonedaPeer
     */
    public function getPeer()
    {
        if (self::$peer === null) {
            self::$peer = new MonedaPeer();
        }

        return self::$peer;
    }


    /**
     * Initializes a collection based on the name of a relation.
     * Avoids crafting an 'init[$relationName]s' method name
     * that wouldn't work when StandardEnglishPluralizer is used.
     *
     * @param string $relationName The name of the relation to initialize
     * @return void
     */
    public function initRelation($relationName)
    {
        if ('Requerimiento' == $relationName) {
            $this->initRequerimientos();
        }
        if ('Propiedad' == $relationName) {
            $this->initPropiedads();
        }
        if ('TasaCambioRelatedByMonedaOrigen' == $relationName) {
            $this->initTasaCambiosRelatedByMonedaOrigen();
        }
        if ('TasaCambioRelatedByMonedaDestino' == $relationName) {
            $this->initTasaCambiosRelatedByMonedaDestino();
        }
    }

    /**
     * Clears out the collRequerimientos collection
     *
     * This does not modify the database; however, it will remove any associated objects, causing
     * them to be refetched by subsequent calls to accessor method.
     *
     * @return void
     * @see        addRequerimientos()
     */
    public function clearRequerimientos()
    {
        $this->collRequerimientos = null; // important to set this to null since that means it is uninitialized
        $this->collRequerimientosPartial = null;
    }

    /**
     * reset is the collRequerimientos collection loaded partially
     *
     * @return void
     */
    public function resetPartialRequerimientos($v = true)
    {
        $this->collRequerimientosPartial = $v;
    }

    /**
     * Initializes the collRequerimientos collection.
     *
     * By default this just sets the collRequerimientos collection to an empty array (like clearcollRequerimientos());
     * however, you may wish to override this method in your stub class to provide setting appropriate
     * to your application -- for example, setting the initial array to the values stored in database.
     *
     * @param boolean $overrideExisting If set to true, the method call initializes
     *                                        the collection even if it is not empty
     *
     * @return void
     */
    public function initRequerimientos($overrideExisting = true)
    {
        if (null !== $this->collRequerimientos && !$overrideExisting) {
            return;
        }
        $this->collRequerimientos = new PropelObjectCollection();
        $this->collRequerimientos->setModel('Requerimiento');
    }

    /**
     * Gets an array of Requerimiento objects which contain a foreign key that references this object.
     *
     * If the $criteria is not null, it is used to always fetch the results from the database.
     * Otherwise the results are fetched from the database the first time, then cached.
     * Next time the same method is called without $criteria, the cached collection is returned.
     * If this Moneda is new, it will return
     * an empty collection or the current collection; the criteria is ignored on a new object.
     *
     * @param Criteria $criteria optional Criteria object to narrow the query
     * @param PropelPDO $con optional connection object
     * @return PropelObjectCollection|Requerimiento[] List of Requerimiento objects
     * @throws PropelException
     */
    public function getRequerimientos($criteria = null, PropelPDO $con = null)
    {
        $partial = $this->collRequerimientosPartial && !$this->isNew();
        if (null === $this->collRequerimientos || null !== $criteria  || $partial) {
            if ($this->isNew() && null === $this->collRequerimientos) {
                // return empty collection
                $this->initRequerimientos();
            } else {
                $collRequerimientos = RequerimientoQuery::create(null, $criteria)
                    ->filterByMoneda($this)
                    ->find($con);
                if (null !== $criteria) {
                    if (false !== $this->collRequerimientosPartial && count($collRequerimientos)) {
                      $this->initRequerimientos(false);

                      foreach($collRequerimientos as $obj) {
                        if (false == $this->collRequerimientos->contains($obj)) {
                          $this->collRequerimientos->append($obj);
                        }
                      }

                      $this->collRequerimientosPartial = true;
                    }

                    return $collRequerimientos;
                }

                if($partial && $this->collRequerimientos) {
                    foreach($this->collRequerimientos as $obj) {
                        if($obj->isNew()) {
                            $collRequerimientos[] = $obj;
                        }
                    }
                }

                $this->collRequerimientos = $collRequerimientos;
                $this->collRequerimientosPartial = false;
            }
        }

        return $this->collRequerimientos;
    }

    /**
     * Sets a collection of Requerimiento objects related by a one-to-many relationship
     * to the current object.
     * It will also schedule objects for deletion based on a diff between old objects (aka persisted)
     * and new objects from the given Propel collection.
     *
     * @param PropelCollection $requerimientos A Propel collection.
     * @param PropelPDO $con Optional connection object
     */
    public function setRequerimientos(PropelCollection $requerimientos, PropelPDO $con = null)
    {
        $this->requerimientosScheduledForDeletion = $this->getRequerimientos(new Criteria(), $con)->diff($requerimientos);

        foreach ($this->requerimientosScheduledForDeletion as $requerimientoRemoved) {
            $requerimientoRemoved->setMoneda(null);
        }

        $this->collRequerimientos = null;
        foreach ($requerimientos as $requerimiento) {
            $this->addRequerimiento($requerimiento);
        }

        $this->collRequerimientos = $requerimientos;
        $this->collRequerimientosPartial = false;
    }

    /**
     * Returns the number of related Requerimiento objects.
     *
     * @param Criteria $criteria
     * @param boolean $distinct
     * @param PropelPDO $con
     * @return int             Count of related Requerimiento objects.
     * @throws PropelException
     */
    public function countRequerimientos(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
    {
        $partial = $this->collRequerimientosPartial && !$this->isNew();
        if (null === $this->collRequerimientos || null !== $criteria || $partial) {
            if ($this->isNew() && null === $this->collRequerimientos) {
                return 0;
            } else {
                if($partial && !$criteria) {
                    return count($this->getRequerimientos());
                }
                $query = RequerimientoQuery::create(null, $criteria);
                if ($distinct) {
                    $query->distinct();
                }

                return $query
                    ->filterByMoneda($this)
                    ->count($con);
            }
        } else {
            return count($this->collRequerimientos);
        }
    }

    /**
     * Method called to associate a Requerimiento object to this object
     * through the Requerimiento foreign key attribute.
     *
     * @param    Requerimiento $l Requerimiento
     * @return Moneda The current object (for fluent API support)
     */
    public function addRequerimiento(Requerimiento $l)
    {
        if ($this->collRequerimientos === null) {
            $this->initRequerimientos();
            $this->collRequerimientosPartial = true;
        }
        if (!$this->collRequerimientos->contains($l)) { // only add it if the **same** object is not already associated
            $this->doAddRequerimiento($l);
        }

        return $this;
    }

    /**
     * @param	Requerimiento $requerimiento The requerimiento object to add.
     */
    protected function doAddRequerimiento($requerimiento)
    {
        $this->collRequerimientos[]= $requerimiento;
        $requerimiento->setMoneda($this);
    }

    /**
     * @param	Requerimiento $requerimiento The requerimiento object to remove.
     */
    public function removeRequerimiento($requerimiento)
    {
        if ($this->getRequerimientos()->contains($requerimiento)) {
            $this->collRequerimientos->remove($this->collRequerimientos->search($requerimiento));
            if (null === $this->requerimientosScheduledForDeletion) {
                $this->requerimientosScheduledForDeletion = clone $this->collRequerimientos;
                $this->requerimientosScheduledForDeletion->clear();
            }
            $this->requerimientosScheduledForDeletion[]= $requerimiento;
            $requerimiento->setMoneda(null);
        }
    }


    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Moneda is new, it will return
     * an empty collection; or if this Moneda has previously
     * been saved, it will retrieve related Requerimientos from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Moneda.
     *
     * @param Criteria $criteria optional Criteria object to narrow the query
     * @param PropelPDO $con optional connection object
     * @param string $join_behavior optional join type to use (defaults to Criteria::LEFT_JOIN)
     * @return PropelObjectCollection|Requerimiento[] List of Requerimiento objects
     */
    public function getRequerimientosJoinUsuario($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        $query = RequerimientoQuery::create(null, $criteria);
        $query->joinWith('Usuario', $join_behavior);

        return $this->getRequerimientos($query, $con);
    }

    /**
     * Clears out the collPropiedads collection
     *
     * This does not modify the database; however, it will remove any associated objects, causing
     * them to be refetched by subsequent calls to accessor method.
     *
     * @return void
     * @see        addPropiedads()
     */
    public function clearPropiedads()
    {
        $this->collPropiedads = null; // important to set this to null since that means it is uninitialized
        $this->collPropiedadsPartial = null;
    }

    /**
     * reset is the collPropiedads collection loaded partially
     *
     * @return void
     */
    public function resetPartialPropiedads($v = true)
    {
        $this->collPropiedadsPartial = $v;
    }

    /**
     * Initializes the collPropiedads collection.
     *
     * By default this just sets the collPropiedads collection to an empty array (like clearcollPropiedads());
     * however, you may wish to override this method in your stub class to provide setting appropriate
     * to your application -- for example, setting the initial array to the values stored in database.
     *
     * @param boolean $overrideExisting If set to true, the method call initializes
     *                                        the collection even if it is not empty
     *
     * @return void
     */
    public function initPropiedads($overrideExisting = true)
    {
        if (null !== $this->collPropiedads && !$overrideExisting) {
            return;
        }
        $this->collPropiedads = new PropelObjectCollection();
        $this->collPropiedads->setModel('Propiedad');
    }

    /**
     * Gets an array of Propiedad objects which contain a foreign key that references this object.
     *
     * If the $criteria is not null, it is used to always fetch the results from the database.
     * Otherwise the results are fetched from the database the first time, then cached.
     * Next time the same method is called without $criteria, the cached collection is returned.
     * If this Moneda is new, it will return
     * an empty collection or the current collection; the criteria is ignored on a new object.
     *
     * @param Criteria $criteria optional Criteria object to narrow the query
     * @param PropelPDO $con optional connection object
     * @return PropelObjectCollection|Propiedad[] List of Propiedad objects
     * @throws PropelException
     */
    public function getPropiedads($criteria = null, PropelPDO $con = null)
    {
        $partial = $this->collPropiedadsPartial && !$this->isNew();
        if (null === $this->collPropiedads || null !== $criteria  || $partial) {
            if ($this->isNew() && null === $this->collPropiedads) {
                // return empty collection
                $this->initPropiedads();
            } else {
                $collPropiedads = PropiedadQuery::create(null, $criteria)
                    ->filterByMoneda($this)
                    ->find($con);
                if (null !== $criteria) {
                    if (false !== $this->collPropiedadsPartial && count($collPropiedads)) {
                      $this->initPropiedads(false);

                      foreach($collPropiedads as $obj) {
                        if (false == $this->collPropiedads->contains($obj)) {
                          $this->collPropiedads->append($obj);
                        }
                      }

                      $this->collPropiedadsPartial = true;
                    }

                    return $collPropiedads;
                }

                if($partial && $this->collPropiedads) {
                    foreach($this->collPropiedads as $obj) {
                        if($obj->isNew()) {
                            $collPropiedads[] = $obj;
                        }
                    }
                }

                $this->collPropiedads = $collPropiedads;
                $this->collPropiedadsPartial = false;
            }
        }

        return $this->collPropiedads;
    }

    /**
     * Sets a collection of Propiedad objects related by a one-to-many relationship
     * to the current object.
     * It will also schedule objects for deletion based on a diff between old objects (aka persisted)
     * and new objects from the given Propel collection.
     *
     * @param PropelCollection $propiedads A Propel collection.
     * @param PropelPDO $con Optional connection object
     */
    public function setPropiedads(PropelCollection $propiedads, PropelPDO $con = null)
    {
        $this->propiedadsScheduledForDeletion = $this->getPropiedads(new Criteria(), $con)->diff($propiedads);

        foreach ($this->propiedadsScheduledForDeletion as $propiedadRemoved) {
            $propiedadRemoved->setMoneda(null);
        }

        $this->collPropiedads = null;
        foreach ($propiedads as $propiedad) {
            $this->addPropiedad($propiedad);
        }

        $this->collPropiedads = $propiedads;
        $this->collPropiedadsPartial = false;
    }

    /**
     * Returns the number of related Propiedad objects.
     *
     * @param Criteria $criteria
     * @param boolean $distinct
     * @param PropelPDO $con
     * @return int             Count of related Propiedad objects.
     * @throws PropelException
     */
    public function countPropiedads(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
    {
        $partial = $this->collPropiedadsPartial && !$this->isNew();
        if (null === $this->collPropiedads || null !== $criteria || $partial) {
            if ($this->isNew() && null === $this->collPropiedads) {
                return 0;
            } else {
                if($partial && !$criteria) {
                    return count($this->getPropiedads());
                }
                $query = PropiedadQuery::create(null, $criteria);
                if ($distinct) {
                    $query->distinct();
                }

                return $query
                    ->filterByMoneda($this)
                    ->count($con);
            }
        } else {
            return count($this->collPropiedads);
        }
    }

    /**
     * Method called to associate a Propiedad object to this object
     * through the Propiedad foreign key attribute.
     *
     * @param    Propiedad $l Propiedad
     * @return Moneda The current object (for fluent API support)
     */
    public function addPropiedad(Propiedad $l)
    {
        if ($this->collPropiedads === null) {
            $this->initPropiedads();
            $this->collPropiedadsPartial = true;
        }
        if (!$this->collPropiedads->contains($l)) { // only add it if the **same** object is not already associated
            $this->doAddPropiedad($l);
        }

        return $this;
    }

    /**
     * @param	Propiedad $propiedad The propiedad object to add.
     */
    protected function doAddPropiedad($propiedad)
    {
        $this->collPropiedads[]= $propiedad;
        $propiedad->setMoneda($this);
    }

    /**
     * @param	Propiedad $propiedad The propiedad object to remove.
     */
    public function removePropiedad($propiedad)
    {
        if ($this->getPropiedads()->contains($propiedad)) {
            $this->collPropiedads->remove($this->collPropiedads->search($propiedad));
            if (null === $this->propiedadsScheduledForDeletion) {
                $this->propiedadsScheduledForDeletion = clone $this->collPropiedads;
                $this->propiedadsScheduledForDeletion->clear();
            }
            $this->propiedadsScheduledForDeletion[]= $propiedad;
            $propiedad->setMoneda(null);
        }
    }


    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Moneda is new, it will return
     * an empty collection; or if this Moneda has previously
     * been saved, it will retrieve related Propiedads from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Moneda.
     *
     * @param Criteria $criteria optional Criteria object to narrow the query
     * @param PropelPDO $con optional connection object
     * @param string $join_behavior optional join type to use (defaults to Criteria::LEFT_JOIN)
     * @return PropelObjectCollection|Propiedad[] List of Propiedad objects
     */
    public function getPropiedadsJoinDepartamento($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        $query = PropiedadQuery::create(null, $criteria);
        $query->joinWith('Departamento', $join_behavior);

        return $this->getPropiedads($query, $con);
    }


    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Moneda is new, it will return
     * an empty collection; or if this Moneda has previously
     * been saved, it will retrieve related Propiedads from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Moneda.
     *
     * @param Criteria $criteria optional Criteria object to narrow the query
     * @param PropelPDO $con optional connection object
     * @param string $join_behavior optional join type to use (defaults to Criteria::LEFT_JOIN)
     * @return PropelObjectCollection|Propiedad[] List of Propiedad objects
     */
    public function getPropiedadsJoinMunicipio($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        $query = PropiedadQuery::create(null, $criteria);
        $query->joinWith('Municipio', $join_behavior);

        return $this->getPropiedads($query, $con);
    }


    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Moneda is new, it will return
     * an empty collection; or if this Moneda has previously
     * been saved, it will retrieve related Propiedads from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Moneda.
     *
     * @param Criteria $criteria optional Criteria object to narrow the query
     * @param PropelPDO $con optional connection object
     * @param string $join_behavior optional join type to use (defaults to Criteria::LEFT_JOIN)
     * @return PropelObjectCollection|Propiedad[] List of Propiedad objects
     */
    public function getPropiedadsJoinCarretera($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        $query = PropiedadQuery::create(null, $criteria);
        $query->joinWith('Carretera', $join_behavior);

        return $this->getPropiedads($query, $con);
    }


    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Moneda is new, it will return
     * an empty collection; or if this Moneda has previously
     * been saved, it will retrieve related Propiedads from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Moneda.
     *
     * @param Criteria $criteria optional Criteria object to narrow the query
     * @param PropelPDO $con optional connection object
     * @param string $join_behavior optional join type to use (defaults to Criteria::LEFT_JOIN)
     * @return PropelObjectCollection|Propiedad[] List of Propiedad objects
     */
    public function getPropiedadsJoinUsuario($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        $query = PropiedadQuery::create(null, $criteria);
        $query->joinWith('Usuario', $join_behavior);

        return $this->getPropiedads($query, $con);
    }

    /**
     * Clears out the collTasaCambiosRelatedByMonedaOrigen collection
     *
     * This does not modify the database; however, it will remove any associated objects, causing
     * them to be refetched by subsequent calls to accessor method.
     *
     * @return void
     * @see        addTasaCambiosRelatedByMonedaOrigen()
     */
    public function clearTasaCambiosRelatedByMonedaOrigen()
    {
        $this->collTasaCambiosRelatedByMonedaOrigen = null; // important to set this to null since that means it is uninitialized
        $this->collTasaCambiosRelatedByMonedaOrigenPartial = null;
    }

    /**
     * reset is the collTasaCambiosRelatedByMonedaOrigen collection loaded partially
     *
     * @return void
     */
    public function resetPartialTasaCambiosRelatedByMonedaOrigen($v = true)
    {
        $this->collTasaCambiosRelatedByMonedaOrigenPartial = $v;
    }

    /**
     * Initializes the collTasaCambiosRelatedByMonedaOrigen collection.
     *
     * By default this just sets the collTasaCambiosRelatedByMonedaOrigen collection to an empty array (like clearcollTasaCambiosRelatedByMonedaOrigen());
     * however, you may wish to override this method in your stub class to provide setting appropriate
     * to your application -- for example, setting the initial array to the values stored in database.
     *
     * @param boolean $overrideExisting If set to true, the method call initializes
     *                                        the collection even if it is not empty
     *
     * @return void
     */
    public function initTasaCambiosRelatedByMonedaOrigen($overrideExisting = true)
    {
        if (null !== $this->collTasaCambiosRelatedByMonedaOrigen && !$overrideExisting) {
            return;
        }
        $this->collTasaCambiosRelatedByMonedaOrigen = new PropelObjectCollection();
        $this->collTasaCambiosRelatedByMonedaOrigen->setModel('TasaCambio');
    }

    /**
     * Gets an array of TasaCambio objects which contain a foreign key that references this object.
     *
     * If the $criteria is not null, it is used to always fetch the results from the database.
     * Otherwise the results are fetched from the database the first time, then cached.
     * Next time the same method is called without $criteria, the cached collection is returned.
     * If this Moneda is new, it will return
     * an empty collection or the current collection; the criteria is ignored on a new object.
     *
     * @param Criteria $criteria optional Criteria object to narrow the query
     * @param PropelPDO $con optional connection object
     * @return PropelObjectCollection|TasaCambio[] List of TasaCambio objects
     * @throws PropelException
     */
    public function getTasaCambiosRelatedByMonedaOrigen($criteria = null, PropelPDO $con = null)
    {
        $partial = $this->collTasaCambiosRelatedByMonedaOrigenPartial && !$this->isNew();
        if (null === $this->collTasaCambiosRelatedByMonedaOrigen || null !== $criteria  || $partial) {
            if ($this->isNew() && null === $this->collTasaCambiosRelatedByMonedaOrigen) {
                // return empty collection
                $this->initTasaCambiosRelatedByMonedaOrigen();
            } else {
                $collTasaCambiosRelatedByMonedaOrigen = TasaCambioQuery::create(null, $criteria)
                    ->filterByMonedaRelatedByMonedaOrigen($this)
                    ->find($con);
                if (null !== $criteria) {
                    if (false !== $this->collTasaCambiosRelatedByMonedaOrigenPartial && count($collTasaCambiosRelatedByMonedaOrigen)) {
                      $this->initTasaCambiosRelatedByMonedaOrigen(false);

                      foreach($collTasaCambiosRelatedByMonedaOrigen as $obj) {
                        if (false == $this->collTasaCambiosRelatedByMonedaOrigen->contains($obj)) {
                          $this->collTasaCambiosRelatedByMonedaOrigen->append($obj);
                        }
                      }

                      $this->collTasaCambiosRelatedByMonedaOrigenPartial = true;
                    }

                    return $collTasaCambiosRelatedByMonedaOrigen;
                }

                if($partial && $this->collTasaCambiosRelatedByMonedaOrigen) {
                    foreach($this->collTasaCambiosRelatedByMonedaOrigen as $obj) {
                        if($obj->isNew()) {
                            $collTasaCambiosRelatedByMonedaOrigen[] = $obj;
                        }
                    }
                }

                $this->collTasaCambiosRelatedByMonedaOrigen = $collTasaCambiosRelatedByMonedaOrigen;
                $this->collTasaCambiosRelatedByMonedaOrigenPartial = false;
            }
        }

        return $this->collTasaCambiosRelatedByMonedaOrigen;
    }

    /**
     * Sets a collection of TasaCambioRelatedByMonedaOrigen objects related by a one-to-many relationship
     * to the current object.
     * It will also schedule objects for deletion based on a diff between old objects (aka persisted)
     * and new objects from the given Propel collection.
     *
     * @param PropelCollection $tasaCambiosRelatedByMonedaOrigen A Propel collection.
     * @param PropelPDO $con Optional connection object
     */
    public function setTasaCambiosRelatedByMonedaOrigen(PropelCollection $tasaCambiosRelatedByMonedaOrigen, PropelPDO $con = null)
    {
        $this->tasaCambiosRelatedByMonedaOrigenScheduledForDeletion = $this->getTasaCambiosRelatedByMonedaOrigen(new Criteria(), $con)->diff($tasaCambiosRelatedByMonedaOrigen);

        foreach ($this->tasaCambiosRelatedByMonedaOrigenScheduledForDeletion as $tasaCambioRelatedByMonedaOrigenRemoved) {
            $tasaCambioRelatedByMonedaOrigenRemoved->setMonedaRelatedByMonedaOrigen(null);
        }

        $this->collTasaCambiosRelatedByMonedaOrigen = null;
        foreach ($tasaCambiosRelatedByMonedaOrigen as $tasaCambioRelatedByMonedaOrigen) {
            $this->addTasaCambioRelatedByMonedaOrigen($tasaCambioRelatedByMonedaOrigen);
        }

        $this->collTasaCambiosRelatedByMonedaOrigen = $tasaCambiosRelatedByMonedaOrigen;
        $this->collTasaCambiosRelatedByMonedaOrigenPartial = false;
    }

    /**
     * Returns the number of related TasaCambio objects.
     *
     * @param Criteria $criteria
     * @param boolean $distinct
     * @param PropelPDO $con
     * @return int             Count of related TasaCambio objects.
     * @throws PropelException
     */
    public function countTasaCambiosRelatedByMonedaOrigen(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
    {
        $partial = $this->collTasaCambiosRelatedByMonedaOrigenPartial && !$this->isNew();
        if (null === $this->collTasaCambiosRelatedByMonedaOrigen || null !== $criteria || $partial) {
            if ($this->isNew() && null === $this->collTasaCambiosRelatedByMonedaOrigen) {
                return 0;
            } else {
                if($partial && !$criteria) {
                    return count($this->getTasaCambiosRelatedByMonedaOrigen());
                }
                $query = TasaCambioQuery::create(null, $criteria);
                if ($distinct) {
                    $query->distinct();
                }

                return $query
                    ->filterByMonedaRelatedByMonedaOrigen($this)
                    ->count($con);
            }
        } else {
            return count($this->collTasaCambiosRelatedByMonedaOrigen);
        }
    }

    /**
     * Method called to associate a TasaCambio object to this object
     * through the TasaCambio foreign key attribute.
     *
     * @param    TasaCambio $l TasaCambio
     * @return Moneda The current object (for fluent API support)
     */
    public function addTasaCambioRelatedByMonedaOrigen(TasaCambio $l)
    {
        if ($this->collTasaCambiosRelatedByMonedaOrigen === null) {
            $this->initTasaCambiosRelatedByMonedaOrigen();
            $this->collTasaCambiosRelatedByMonedaOrigenPartial = true;
        }
        if (!$this->collTasaCambiosRelatedByMonedaOrigen->contains($l)) { // only add it if the **same** object is not already associated
            $this->doAddTasaCambioRelatedByMonedaOrigen($l);
        }

        return $this;
    }

    /**
     * @param	TasaCambioRelatedByMonedaOrigen $tasaCambioRelatedByMonedaOrigen The tasaCambioRelatedByMonedaOrigen object to add.
     */
    protected function doAddTasaCambioRelatedByMonedaOrigen($tasaCambioRelatedByMonedaOrigen)
    {
        $this->collTasaCambiosRelatedByMonedaOrigen[]= $tasaCambioRelatedByMonedaOrigen;
        $tasaCambioRelatedByMonedaOrigen->setMonedaRelatedByMonedaOrigen($this);
    }

    /**
     * @param	TasaCambioRelatedByMonedaOrigen $tasaCambioRelatedByMonedaOrigen The tasaCambioRelatedByMonedaOrigen object to remove.
     */
    public function removeTasaCambioRelatedByMonedaOrigen($tasaCambioRelatedByMonedaOrigen)
    {
        if ($this->getTasaCambiosRelatedByMonedaOrigen()->contains($tasaCambioRelatedByMonedaOrigen)) {
            $this->collTasaCambiosRelatedByMonedaOrigen->remove($this->collTasaCambiosRelatedByMonedaOrigen->search($tasaCambioRelatedByMonedaOrigen));
            if (null === $this->tasaCambiosRelatedByMonedaOrigenScheduledForDeletion) {
                $this->tasaCambiosRelatedByMonedaOrigenScheduledForDeletion = clone $this->collTasaCambiosRelatedByMonedaOrigen;
                $this->tasaCambiosRelatedByMonedaOrigenScheduledForDeletion->clear();
            }
            $this->tasaCambiosRelatedByMonedaOrigenScheduledForDeletion[]= $tasaCambioRelatedByMonedaOrigen;
            $tasaCambioRelatedByMonedaOrigen->setMonedaRelatedByMonedaOrigen(null);
        }
    }

    /**
     * Clears out the collTasaCambiosRelatedByMonedaDestino collection
     *
     * This does not modify the database; however, it will remove any associated objects, causing
     * them to be refetched by subsequent calls to accessor method.
     *
     * @return void
     * @see        addTasaCambiosRelatedByMonedaDestino()
     */
    public function clearTasaCambiosRelatedByMonedaDestino()
    {
        $this->collTasaCambiosRelatedByMonedaDestino = null; // important to set this to null since that means it is uninitialized
        $this->collTasaCambiosRelatedByMonedaDestinoPartial = null;
    }

    /**
     * reset is the collTasaCambiosRelatedByMonedaDestino collection loaded partially
     *
     * @return void
     */
    public function resetPartialTasaCambiosRelatedByMonedaDestino($v = true)
    {
        $this->collTasaCambiosRelatedByMonedaDestinoPartial = $v;
    }

    /**
     * Initializes the collTasaCambiosRelatedByMonedaDestino collection.
     *
     * By default this just sets the collTasaCambiosRelatedByMonedaDestino collection to an empty array (like clearcollTasaCambiosRelatedByMonedaDestino());
     * however, you may wish to override this method in your stub class to provide setting appropriate
     * to your application -- for example, setting the initial array to the values stored in database.
     *
     * @param boolean $overrideExisting If set to true, the method call initializes
     *                                        the collection even if it is not empty
     *
     * @return void
     */
    public function initTasaCambiosRelatedByMonedaDestino($overrideExisting = true)
    {
        if (null !== $this->collTasaCambiosRelatedByMonedaDestino && !$overrideExisting) {
            return;
        }
        $this->collTasaCambiosRelatedByMonedaDestino = new PropelObjectCollection();
        $this->collTasaCambiosRelatedByMonedaDestino->setModel('TasaCambio');
    }

    /**
     * Gets an array of TasaCambio objects which contain a foreign key that references this object.
     *
     * If the $criteria is not null, it is used to always fetch the results from the database.
     * Otherwise the results are fetched from the database the first time, then cached.
     * Next time the same method is called without $criteria, the cached collection is returned.
     * If this Moneda is new, it will return
     * an empty collection or the current collection; the criteria is ignored on a new object.
     *
     * @param Criteria $criteria optional Criteria object to narrow the query
     * @param PropelPDO $con optional connection object
     * @return PropelObjectCollection|TasaCambio[] List of TasaCambio objects
     * @throws PropelException
     */
    public function getTasaCambiosRelatedByMonedaDestino($criteria = null, PropelPDO $con = null)
    {
        $partial = $this->collTasaCambiosRelatedByMonedaDestinoPartial && !$this->isNew();
        if (null === $this->collTasaCambiosRelatedByMonedaDestino || null !== $criteria  || $partial) {
            if ($this->isNew() && null === $this->collTasaCambiosRelatedByMonedaDestino) {
                // return empty collection
                $this->initTasaCambiosRelatedByMonedaDestino();
            } else {
                $collTasaCambiosRelatedByMonedaDestino = TasaCambioQuery::create(null, $criteria)
                    ->filterByMonedaRelatedByMonedaDestino($this)
                    ->find($con);
                if (null !== $criteria) {
                    if (false !== $this->collTasaCambiosRelatedByMonedaDestinoPartial && count($collTasaCambiosRelatedByMonedaDestino)) {
                      $this->initTasaCambiosRelatedByMonedaDestino(false);

                      foreach($collTasaCambiosRelatedByMonedaDestino as $obj) {
                        if (false == $this->collTasaCambiosRelatedByMonedaDestino->contains($obj)) {
                          $this->collTasaCambiosRelatedByMonedaDestino->append($obj);
                        }
                      }

                      $this->collTasaCambiosRelatedByMonedaDestinoPartial = true;
                    }

                    return $collTasaCambiosRelatedByMonedaDestino;
                }

                if($partial && $this->collTasaCambiosRelatedByMonedaDestino) {
                    foreach($this->collTasaCambiosRelatedByMonedaDestino as $obj) {
                        if($obj->isNew()) {
                            $collTasaCambiosRelatedByMonedaDestino[] = $obj;
                        }
                    }
                }

                $this->collTasaCambiosRelatedByMonedaDestino = $collTasaCambiosRelatedByMonedaDestino;
                $this->collTasaCambiosRelatedByMonedaDestinoPartial = false;
            }
        }

        return $this->collTasaCambiosRelatedByMonedaDestino;
    }

    /**
     * Sets a collection of TasaCambioRelatedByMonedaDestino objects related by a one-to-many relationship
     * to the current object.
     * It will also schedule objects for deletion based on a diff between old objects (aka persisted)
     * and new objects from the given Propel collection.
     *
     * @param PropelCollection $tasaCambiosRelatedByMonedaDestino A Propel collection.
     * @param PropelPDO $con Optional connection object
     */
    public function setTasaCambiosRelatedByMonedaDestino(PropelCollection $tasaCambiosRelatedByMonedaDestino, PropelPDO $con = null)
    {
        $this->tasaCambiosRelatedByMonedaDestinoScheduledForDeletion = $this->getTasaCambiosRelatedByMonedaDestino(new Criteria(), $con)->diff($tasaCambiosRelatedByMonedaDestino);

        foreach ($this->tasaCambiosRelatedByMonedaDestinoScheduledForDeletion as $tasaCambioRelatedByMonedaDestinoRemoved) {
            $tasaCambioRelatedByMonedaDestinoRemoved->setMonedaRelatedByMonedaDestino(null);
        }

        $this->collTasaCambiosRelatedByMonedaDestino = null;
        foreach ($tasaCambiosRelatedByMonedaDestino as $tasaCambioRelatedByMonedaDestino) {
            $this->addTasaCambioRelatedByMonedaDestino($tasaCambioRelatedByMonedaDestino);
        }

        $this->collTasaCambiosRelatedByMonedaDestino = $tasaCambiosRelatedByMonedaDestino;
        $this->collTasaCambiosRelatedByMonedaDestinoPartial = false;
    }

    /**
     * Returns the number of related TasaCambio objects.
     *
     * @param Criteria $criteria
     * @param boolean $distinct
     * @param PropelPDO $con
     * @return int             Count of related TasaCambio objects.
     * @throws PropelException
     */
    public function countTasaCambiosRelatedByMonedaDestino(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
    {
        $partial = $this->collTasaCambiosRelatedByMonedaDestinoPartial && !$this->isNew();
        if (null === $this->collTasaCambiosRelatedByMonedaDestino || null !== $criteria || $partial) {
            if ($this->isNew() && null === $this->collTasaCambiosRelatedByMonedaDestino) {
                return 0;
            } else {
                if($partial && !$criteria) {
                    return count($this->getTasaCambiosRelatedByMonedaDestino());
                }
                $query = TasaCambioQuery::create(null, $criteria);
                if ($distinct) {
                    $query->distinct();
                }

                return $query
                    ->filterByMonedaRelatedByMonedaDestino($this)
                    ->count($con);
            }
        } else {
            return count($this->collTasaCambiosRelatedByMonedaDestino);
        }
    }

    /**
     * Method called to associate a TasaCambio object to this object
     * through the TasaCambio foreign key attribute.
     *
     * @param    TasaCambio $l TasaCambio
     * @return Moneda The current object (for fluent API support)
     */
    public function addTasaCambioRelatedByMonedaDestino(TasaCambio $l)
    {
        if ($this->collTasaCambiosRelatedByMonedaDestino === null) {
            $this->initTasaCambiosRelatedByMonedaDestino();
            $this->collTasaCambiosRelatedByMonedaDestinoPartial = true;
        }
        if (!$this->collTasaCambiosRelatedByMonedaDestino->contains($l)) { // only add it if the **same** object is not already associated
            $this->doAddTasaCambioRelatedByMonedaDestino($l);
        }

        return $this;
    }

    /**
     * @param	TasaCambioRelatedByMonedaDestino $tasaCambioRelatedByMonedaDestino The tasaCambioRelatedByMonedaDestino object to add.
     */
    protected function doAddTasaCambioRelatedByMonedaDestino($tasaCambioRelatedByMonedaDestino)
    {
        $this->collTasaCambiosRelatedByMonedaDestino[]= $tasaCambioRelatedByMonedaDestino;
        $tasaCambioRelatedByMonedaDestino->setMonedaRelatedByMonedaDestino($this);
    }

    /**
     * @param	TasaCambioRelatedByMonedaDestino $tasaCambioRelatedByMonedaDestino The tasaCambioRelatedByMonedaDestino object to remove.
     */
    public function removeTasaCambioRelatedByMonedaDestino($tasaCambioRelatedByMonedaDestino)
    {
        if ($this->getTasaCambiosRelatedByMonedaDestino()->contains($tasaCambioRelatedByMonedaDestino)) {
            $this->collTasaCambiosRelatedByMonedaDestino->remove($this->collTasaCambiosRelatedByMonedaDestino->search($tasaCambioRelatedByMonedaDestino));
            if (null === $this->tasaCambiosRelatedByMonedaDestinoScheduledForDeletion) {
                $this->tasaCambiosRelatedByMonedaDestinoScheduledForDeletion = clone $this->collTasaCambiosRelatedByMonedaDestino;
                $this->tasaCambiosRelatedByMonedaDestinoScheduledForDeletion->clear();
            }
            $this->tasaCambiosRelatedByMonedaDestinoScheduledForDeletion[]= $tasaCambioRelatedByMonedaDestino;
            $tasaCambioRelatedByMonedaDestino->setMonedaRelatedByMonedaDestino(null);
        }
    }

    /**
     * Clears the current object and sets all attributes to their default values
     */
    public function clear()
    {
        $this->id = null;
        $this->descripcion = null;
        $this->simbolo = null;
        $this->codigo = null;
        $this->alreadyInSave = false;
        $this->alreadyInValidation = false;
        $this->clearAllReferences();
        $this->resetModified();
        $this->setNew(true);
        $this->setDeleted(false);
    }

    /**
     * Resets all references to other model objects or collections of model objects.
     *
     * This method is a user-space workaround for PHP's inability to garbage collect
     * objects with circular references (even in PHP 5.3). This is currently necessary
     * when using Propel in certain daemon or large-volumne/high-memory operations.
     *
     * @param boolean $deep Whether to also clear the references on all referrer objects.
     */
    public function clearAllReferences($deep = false)
    {
        if ($deep) {
            if ($this->collRequerimientos) {
                foreach ($this->collRequerimientos as $o) {
                    $o->clearAllReferences($deep);
                }
            }
            if ($this->collPropiedads) {
                foreach ($this->collPropiedads as $o) {
                    $o->clearAllReferences($deep);
                }
            }
            if ($this->collTasaCambiosRelatedByMonedaOrigen) {
                foreach ($this->collTasaCambiosRelatedByMonedaOrigen as $o) {
                    $o->clearAllReferences($deep);
                }
            }
            if ($this->collTasaCambiosRelatedByMonedaDestino) {
                foreach ($this->collTasaCambiosRelatedByMonedaDestino as $o) {
                    $o->clearAllReferences($deep);
                }
            }
        } // if ($deep)

        if ($this->collRequerimientos instanceof PropelCollection) {
            $this->collRequerimientos->clearIterator();
        }
        $this->collRequerimientos = null;
        if ($this->collPropiedads instanceof PropelCollection) {
            $this->collPropiedads->clearIterator();
        }
        $this->collPropiedads = null;
        if ($this->collTasaCambiosRelatedByMonedaOrigen instanceof PropelCollection) {
            $this->collTasaCambiosRelatedByMonedaOrigen->clearIterator();
        }
        $this->collTasaCambiosRelatedByMonedaOrigen = null;
        if ($this->collTasaCambiosRelatedByMonedaDestino instanceof PropelCollection) {
            $this->collTasaCambiosRelatedByMonedaDestino->clearIterator();
        }
        $this->collTasaCambiosRelatedByMonedaDestino = null;
    }

    /**
     * return the string representation of this object
     *
     * @return string The value of the 'descripcion' column
     */
    public function __toString()
    {
        return (string) $this->getDescripcion();
    }

    /**
     * return true is the object is in saving state
     *
     * @return boolean
     */
    public function isAlreadyInSave()
    {
        return $this->alreadyInSave;
    }

    /**
     * Catches calls to virtual methods
     */
    public function __call($name, $params)
    {

        // symfony_behaviors behavior
        if ($callable = sfMixer::getCallable('BaseMoneda:' . $name))
        {
          array_unshift($params, $this);
          return call_user_func_array($callable, $params);
        }


        return parent::__call($name, $params);
    }

}
