<?php


/**
 * Base class that represents a row from the 'propiedad' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * 12/27/17 04:11:29
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BasePropiedad extends BaseObject implements Persistent
{
    /**
     * Peer class name
     */
    const PEER = 'PropiedadPeer';

    /**
     * The Peer class.
     * Instance provides a convenient way of calling static methods on a class
     * that calling code may not be able to identify.
     * @var        PropiedadPeer
     */
    protected static $peer;

    /**
     * The flag var to prevent infinit loop in deep copy
     * @var       boolean
     */
    protected $startCopy = false;

    /**
     * The value for the id field.
     * @var        int
     */
    protected $id;

    /**
     * The value for the tipo_operacion field.
     * @var        string
     */
    protected $tipo_operacion;

    /**
     * The value for the tipo_inmueble field.
     * @var        string
     */
    protected $tipo_inmueble;

    /**
     * The value for the cantidad_habitacion field.
     * @var        int
     */
    protected $cantidad_habitacion;

    /**
     * The value for the cantidad_banio field.
     * @var        int
     */
    protected $cantidad_banio;

    /**
     * The value for the cantidad_parqueo field.
     * @var        int
     */
    protected $cantidad_parqueo;

    /**
     * The value for the cantidad_comedor field.
     * @var        int
     */
    protected $cantidad_comedor;

    /**
     * The value for the cantidad_sala field.
     * @var        int
     */
    protected $cantidad_sala;

    /**
     * The value for the cantidad_cocina field.
     * @var        int
     */
    protected $cantidad_cocina;

    /**
     * The value for the dormitorio_servicio field.
     * Note: this column has a database default value of: false
     * @var        boolean
     */
    protected $dormitorio_servicio;

    /**
     * The value for the estudio field.
     * Note: this column has a database default value of: false
     * @var        boolean
     */
    protected $estudio;

    /**
     * The value for the cisterna field.
     * Note: this column has a database default value of: false
     * @var        boolean
     */
    protected $cisterna;

    /**
     * The value for the cantidad_jardin field.
     * @var        int
     */
    protected $cantidad_jardin;

    /**
     * The value for the cantidad_patio field.
     * @var        int
     */
    protected $cantidad_patio;

    /**
     * The value for the lavanderia field.
     * Note: this column has a database default value of: false
     * @var        boolean
     */
    protected $lavanderia;

    /**
     * The value for the estado field.
     * @var        string
     */
    protected $estado;

    /**
     * The value for the amenidades field.
     * @var        string
     */
    protected $amenidades;

    /**
     * The value for the precio field.
     * @var        double
     */
    protected $precio;

    /**
     * The value for the negociable field.
     * Note: this column has a database default value of: false
     * @var        boolean
     */
    protected $negociable;

    /**
     * The value for the incluye_gastos_escritura field.
     * Note: this column has a database default value of: false
     * @var        boolean
     */
    protected $incluye_gastos_escritura;

    /**
     * The value for the anio_construccion field.
     * @var        int
     */
    protected $anio_construccion;

    /**
     * The value for the mantenimiento_mensual field.
     * @var        double
     */
    protected $mantenimiento_mensual;

    /**
     * The value for the iusi_semestral field.
     * @var        double
     */
    protected $iusi_semestral;

    /**
     * The value for the valor_avaluo field.
     * @var        double
     */
    protected $valor_avaluo;

    /**
     * The value for the created_at field.
     * @var        string
     */
    protected $created_at;

    /**
     * The value for the updated_at field.
     * @var        string
     */
    protected $updated_at;

    /**
     * The value for the created_by field.
     * @var        string
     */
    protected $created_by;

    /**
     * The value for the updated_by field.
     * @var        string
     */
    protected $updated_by;

    /**
     * Flag to prevent endless save loop, if this object is referenced
     * by another object which falls in this transaction.
     * @var        boolean
     */
    protected $alreadyInSave = false;

    /**
     * Flag to prevent endless validation loop, if this object is referenced
     * by another object which falls in this transaction.
     * @var        boolean
     */
    protected $alreadyInValidation = false;

    /**
     * Applies default values to this object.
     * This method should be called from the object's constructor (or
     * equivalent initialization method).
     * @see        __construct()
     */
    public function applyDefaultValues()
    {
        $this->dormitorio_servicio = false;
        $this->estudio = false;
        $this->cisterna = false;
        $this->lavanderia = false;
        $this->negociable = false;
        $this->incluye_gastos_escritura = false;
    }

    /**
     * Initializes internal state of BasePropiedad object.
     * @see        applyDefaults()
     */
    public function __construct()
    {
        parent::__construct();
        $this->applyDefaultValues();
    }

    /**
     * Get the [id] column value.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get the [tipo_operacion] column value.
     *
     * @return string
     */
    public function getTipoOperacion()
    {
        return $this->tipo_operacion;
    }

    /**
     * Get the [tipo_inmueble] column value.
     *
     * @return string
     */
    public function getTipoInmueble()
    {
        return $this->tipo_inmueble;
    }

    /**
     * Get the [cantidad_habitacion] column value.
     *
     * @return int
     */
    public function getCantidadHabitacion()
    {
        return $this->cantidad_habitacion;
    }

    /**
     * Get the [cantidad_banio] column value.
     *
     * @return int
     */
    public function getCantidadBanio()
    {
        return $this->cantidad_banio;
    }

    /**
     * Get the [cantidad_parqueo] column value.
     *
     * @return int
     */
    public function getCantidadParqueo()
    {
        return $this->cantidad_parqueo;
    }

    /**
     * Get the [cantidad_comedor] column value.
     *
     * @return int
     */
    public function getCantidadComedor()
    {
        return $this->cantidad_comedor;
    }

    /**
     * Get the [cantidad_sala] column value.
     *
     * @return int
     */
    public function getCantidadSala()
    {
        return $this->cantidad_sala;
    }

    /**
     * Get the [cantidad_cocina] column value.
     *
     * @return int
     */
    public function getCantidadCocina()
    {
        return $this->cantidad_cocina;
    }

    /**
     * Get the [dormitorio_servicio] column value.
     *
     * @return boolean
     */
    public function getDormitorioServicio()
    {
        return $this->dormitorio_servicio;
    }

    /**
     * Get the [estudio] column value.
     *
     * @return boolean
     */
    public function getEstudio()
    {
        return $this->estudio;
    }

    /**
     * Get the [cisterna] column value.
     *
     * @return boolean
     */
    public function getCisterna()
    {
        return $this->cisterna;
    }

    /**
     * Get the [cantidad_jardin] column value.
     *
     * @return int
     */
    public function getCantidadJardin()
    {
        return $this->cantidad_jardin;
    }

    /**
     * Get the [cantidad_patio] column value.
     *
     * @return int
     */
    public function getCantidadPatio()
    {
        return $this->cantidad_patio;
    }

    /**
     * Get the [lavanderia] column value.
     *
     * @return boolean
     */
    public function getLavanderia()
    {
        return $this->lavanderia;
    }

    /**
     * Get the [estado] column value.
     *
     * @return string
     */
    public function getEstado()
    {
        return $this->estado;
    }

    /**
     * Get the [amenidades] column value.
     *
     * @return string
     */
    public function getAmenidades()
    {
        return $this->amenidades;
    }

    /**
     * Get the [precio] column value.
     *
     * @return double
     */
    public function getPrecio()
    {
        return $this->precio;
    }

    /**
     * Get the [negociable] column value.
     *
     * @return boolean
     */
    public function getNegociable()
    {
        return $this->negociable;
    }

    /**
     * Get the [incluye_gastos_escritura] column value.
     *
     * @return boolean
     */
    public function getIncluyeGastosEscritura()
    {
        return $this->incluye_gastos_escritura;
    }

    /**
     * Get the [anio_construccion] column value.
     *
     * @return int
     */
    public function getAnioConstruccion()
    {
        return $this->anio_construccion;
    }

    /**
     * Get the [mantenimiento_mensual] column value.
     *
     * @return double
     */
    public function getMantenimientoMensual()
    {
        return $this->mantenimiento_mensual;
    }

    /**
     * Get the [iusi_semestral] column value.
     *
     * @return double
     */
    public function getIusiSemestral()
    {
        return $this->iusi_semestral;
    }

    /**
     * Get the [valor_avaluo] column value.
     *
     * @return double
     */
    public function getValorAvaluo()
    {
        return $this->valor_avaluo;
    }

    /**
     * Get the [optionally formatted] temporal [created_at] column value.
     *
     *
     * @param string $format The date/time format string (either date()-style or strftime()-style).
     *				 If format is null, then the raw DateTime object will be returned.
     * @return mixed Formatted date/time value as string or DateTime object (if format is null), null if column is null, and 0 if column value is 0000-00-00 00:00:00
     * @throws PropelException - if unable to parse/validate the date/time value.
     */
    public function getCreatedAt($format = 'Y-m-d H:i:s')
    {
        if ($this->created_at === null) {
            return null;
        }

        if ($this->created_at === '0000-00-00 00:00:00') {
            // while technically this is not a default value of null,
            // this seems to be closest in meaning.
            return null;
        } else {
            try {
                $dt = new DateTime($this->created_at);
            } catch (Exception $x) {
                throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
            }
        }

        if ($format === null) {
            // Because propel.useDateTimeClass is true, we return a DateTime object.
            return $dt;
        } elseif (strpos($format, '%') !== false) {
            return strftime($format, $dt->format('U'));
        } else {
            return $dt->format($format);
        }
    }

    /**
     * Get the [optionally formatted] temporal [updated_at] column value.
     *
     *
     * @param string $format The date/time format string (either date()-style or strftime()-style).
     *				 If format is null, then the raw DateTime object will be returned.
     * @return mixed Formatted date/time value as string or DateTime object (if format is null), null if column is null, and 0 if column value is 0000-00-00 00:00:00
     * @throws PropelException - if unable to parse/validate the date/time value.
     */
    public function getUpdatedAt($format = 'Y-m-d H:i:s')
    {
        if ($this->updated_at === null) {
            return null;
        }

        if ($this->updated_at === '0000-00-00 00:00:00') {
            // while technically this is not a default value of null,
            // this seems to be closest in meaning.
            return null;
        } else {
            try {
                $dt = new DateTime($this->updated_at);
            } catch (Exception $x) {
                throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
            }
        }

        if ($format === null) {
            // Because propel.useDateTimeClass is true, we return a DateTime object.
            return $dt;
        } elseif (strpos($format, '%') !== false) {
            return strftime($format, $dt->format('U'));
        } else {
            return $dt->format($format);
        }
    }

    /**
     * Get the [created_by] column value.
     *
     * @return string
     */
    public function getCreatedBy()
    {
        return $this->created_by;
    }

    /**
     * Get the [updated_by] column value.
     *
     * @return string
     */
    public function getUpdatedBy()
    {
        return $this->updated_by;
    }

    /**
     * Set the value of [id] column.
     *
     * @param int $v new value
     * @return Propiedad The current object (for fluent API support)
     */
    public function setId($v)
    {
        if ($v !== null) {
            $v = (int) $v;
        }

        if ($this->id !== $v) {
            $this->id = $v;
            $this->modifiedColumns[] = PropiedadPeer::ID;
        }


        return $this;
    } // setId()

    /**
     * Set the value of [tipo_operacion] column.
     *
     * @param string $v new value
     * @return Propiedad The current object (for fluent API support)
     */
    public function setTipoOperacion($v)
    {
        if ($v !== null) {
            $v = (string) $v;
        }

        if ($this->tipo_operacion !== $v) {
            $this->tipo_operacion = $v;
            $this->modifiedColumns[] = PropiedadPeer::TIPO_OPERACION;
        }


        return $this;
    } // setTipoOperacion()

    /**
     * Set the value of [tipo_inmueble] column.
     *
     * @param string $v new value
     * @return Propiedad The current object (for fluent API support)
     */
    public function setTipoInmueble($v)
    {
        if ($v !== null) {
            $v = (string) $v;
        }

        if ($this->tipo_inmueble !== $v) {
            $this->tipo_inmueble = $v;
            $this->modifiedColumns[] = PropiedadPeer::TIPO_INMUEBLE;
        }


        return $this;
    } // setTipoInmueble()

    /**
     * Set the value of [cantidad_habitacion] column.
     *
     * @param int $v new value
     * @return Propiedad The current object (for fluent API support)
     */
    public function setCantidadHabitacion($v)
    {
        if ($v !== null) {
            $v = (int) $v;
        }

        if ($this->cantidad_habitacion !== $v) {
            $this->cantidad_habitacion = $v;
            $this->modifiedColumns[] = PropiedadPeer::CANTIDAD_HABITACION;
        }


        return $this;
    } // setCantidadHabitacion()

    /**
     * Set the value of [cantidad_banio] column.
     *
     * @param int $v new value
     * @return Propiedad The current object (for fluent API support)
     */
    public function setCantidadBanio($v)
    {
        if ($v !== null) {
            $v = (int) $v;
        }

        if ($this->cantidad_banio !== $v) {
            $this->cantidad_banio = $v;
            $this->modifiedColumns[] = PropiedadPeer::CANTIDAD_BANIO;
        }


        return $this;
    } // setCantidadBanio()

    /**
     * Set the value of [cantidad_parqueo] column.
     *
     * @param int $v new value
     * @return Propiedad The current object (for fluent API support)
     */
    public function setCantidadParqueo($v)
    {
        if ($v !== null) {
            $v = (int) $v;
        }

        if ($this->cantidad_parqueo !== $v) {
            $this->cantidad_parqueo = $v;
            $this->modifiedColumns[] = PropiedadPeer::CANTIDAD_PARQUEO;
        }


        return $this;
    } // setCantidadParqueo()

    /**
     * Set the value of [cantidad_comedor] column.
     *
     * @param int $v new value
     * @return Propiedad The current object (for fluent API support)
     */
    public function setCantidadComedor($v)
    {
        if ($v !== null) {
            $v = (int) $v;
        }

        if ($this->cantidad_comedor !== $v) {
            $this->cantidad_comedor = $v;
            $this->modifiedColumns[] = PropiedadPeer::CANTIDAD_COMEDOR;
        }


        return $this;
    } // setCantidadComedor()

    /**
     * Set the value of [cantidad_sala] column.
     *
     * @param int $v new value
     * @return Propiedad The current object (for fluent API support)
     */
    public function setCantidadSala($v)
    {
        if ($v !== null) {
            $v = (int) $v;
        }

        if ($this->cantidad_sala !== $v) {
            $this->cantidad_sala = $v;
            $this->modifiedColumns[] = PropiedadPeer::CANTIDAD_SALA;
        }


        return $this;
    } // setCantidadSala()

    /**
     * Set the value of [cantidad_cocina] column.
     *
     * @param int $v new value
     * @return Propiedad The current object (for fluent API support)
     */
    public function setCantidadCocina($v)
    {
        if ($v !== null) {
            $v = (int) $v;
        }

        if ($this->cantidad_cocina !== $v) {
            $this->cantidad_cocina = $v;
            $this->modifiedColumns[] = PropiedadPeer::CANTIDAD_COCINA;
        }


        return $this;
    } // setCantidadCocina()

    /**
     * Sets the value of the [dormitorio_servicio] column.
     * Non-boolean arguments are converted using the following rules:
     *   * 1, '1', 'true',  'on',  and 'yes' are converted to boolean true
     *   * 0, '0', 'false', 'off', and 'no'  are converted to boolean false
     * Check on string values is case insensitive (so 'FaLsE' is seen as 'false').
     *
     * @param boolean|integer|string $v The new value
     * @return Propiedad The current object (for fluent API support)
     */
    public function setDormitorioServicio($v)
    {
        if ($v !== null) {
            if (is_string($v)) {
                $v = in_array(strtolower($v), array('false', 'off', '-', 'no', 'n', '0', '')) ? false : true;
            } else {
                $v = (boolean) $v;
            }
        }

        if ($this->dormitorio_servicio !== $v) {
            $this->dormitorio_servicio = $v;
            $this->modifiedColumns[] = PropiedadPeer::DORMITORIO_SERVICIO;
        }


        return $this;
    } // setDormitorioServicio()

    /**
     * Sets the value of the [estudio] column.
     * Non-boolean arguments are converted using the following rules:
     *   * 1, '1', 'true',  'on',  and 'yes' are converted to boolean true
     *   * 0, '0', 'false', 'off', and 'no'  are converted to boolean false
     * Check on string values is case insensitive (so 'FaLsE' is seen as 'false').
     *
     * @param boolean|integer|string $v The new value
     * @return Propiedad The current object (for fluent API support)
     */
    public function setEstudio($v)
    {
        if ($v !== null) {
            if (is_string($v)) {
                $v = in_array(strtolower($v), array('false', 'off', '-', 'no', 'n', '0', '')) ? false : true;
            } else {
                $v = (boolean) $v;
            }
        }

        if ($this->estudio !== $v) {
            $this->estudio = $v;
            $this->modifiedColumns[] = PropiedadPeer::ESTUDIO;
        }


        return $this;
    } // setEstudio()

    /**
     * Sets the value of the [cisterna] column.
     * Non-boolean arguments are converted using the following rules:
     *   * 1, '1', 'true',  'on',  and 'yes' are converted to boolean true
     *   * 0, '0', 'false', 'off', and 'no'  are converted to boolean false
     * Check on string values is case insensitive (so 'FaLsE' is seen as 'false').
     *
     * @param boolean|integer|string $v The new value
     * @return Propiedad The current object (for fluent API support)
     */
    public function setCisterna($v)
    {
        if ($v !== null) {
            if (is_string($v)) {
                $v = in_array(strtolower($v), array('false', 'off', '-', 'no', 'n', '0', '')) ? false : true;
            } else {
                $v = (boolean) $v;
            }
        }

        if ($this->cisterna !== $v) {
            $this->cisterna = $v;
            $this->modifiedColumns[] = PropiedadPeer::CISTERNA;
        }


        return $this;
    } // setCisterna()

    /**
     * Set the value of [cantidad_jardin] column.
     *
     * @param int $v new value
     * @return Propiedad The current object (for fluent API support)
     */
    public function setCantidadJardin($v)
    {
        if ($v !== null) {
            $v = (int) $v;
        }

        if ($this->cantidad_jardin !== $v) {
            $this->cantidad_jardin = $v;
            $this->modifiedColumns[] = PropiedadPeer::CANTIDAD_JARDIN;
        }


        return $this;
    } // setCantidadJardin()

    /**
     * Set the value of [cantidad_patio] column.
     *
     * @param int $v new value
     * @return Propiedad The current object (for fluent API support)
     */
    public function setCantidadPatio($v)
    {
        if ($v !== null) {
            $v = (int) $v;
        }

        if ($this->cantidad_patio !== $v) {
            $this->cantidad_patio = $v;
            $this->modifiedColumns[] = PropiedadPeer::CANTIDAD_PATIO;
        }


        return $this;
    } // setCantidadPatio()

    /**
     * Sets the value of the [lavanderia] column.
     * Non-boolean arguments are converted using the following rules:
     *   * 1, '1', 'true',  'on',  and 'yes' are converted to boolean true
     *   * 0, '0', 'false', 'off', and 'no'  are converted to boolean false
     * Check on string values is case insensitive (so 'FaLsE' is seen as 'false').
     *
     * @param boolean|integer|string $v The new value
     * @return Propiedad The current object (for fluent API support)
     */
    public function setLavanderia($v)
    {
        if ($v !== null) {
            if (is_string($v)) {
                $v = in_array(strtolower($v), array('false', 'off', '-', 'no', 'n', '0', '')) ? false : true;
            } else {
                $v = (boolean) $v;
            }
        }

        if ($this->lavanderia !== $v) {
            $this->lavanderia = $v;
            $this->modifiedColumns[] = PropiedadPeer::LAVANDERIA;
        }


        return $this;
    } // setLavanderia()

    /**
     * Set the value of [estado] column.
     *
     * @param string $v new value
     * @return Propiedad The current object (for fluent API support)
     */
    public function setEstado($v)
    {
        if ($v !== null) {
            $v = (string) $v;
        }

        if ($this->estado !== $v) {
            $this->estado = $v;
            $this->modifiedColumns[] = PropiedadPeer::ESTADO;
        }


        return $this;
    } // setEstado()

    /**
     * Set the value of [amenidades] column.
     *
     * @param string $v new value
     * @return Propiedad The current object (for fluent API support)
     */
    public function setAmenidades($v)
    {
        if ($v !== null) {
            $v = (string) $v;
        }

        if ($this->amenidades !== $v) {
            $this->amenidades = $v;
            $this->modifiedColumns[] = PropiedadPeer::AMENIDADES;
        }


        return $this;
    } // setAmenidades()

    /**
     * Set the value of [precio] column.
     *
     * @param double $v new value
     * @return Propiedad The current object (for fluent API support)
     */
    public function setPrecio($v)
    {
        if ($v !== null) {
            $v = (double) $v;
        }

        if ($this->precio !== $v) {
            $this->precio = $v;
            $this->modifiedColumns[] = PropiedadPeer::PRECIO;
        }


        return $this;
    } // setPrecio()

    /**
     * Sets the value of the [negociable] column.
     * Non-boolean arguments are converted using the following rules:
     *   * 1, '1', 'true',  'on',  and 'yes' are converted to boolean true
     *   * 0, '0', 'false', 'off', and 'no'  are converted to boolean false
     * Check on string values is case insensitive (so 'FaLsE' is seen as 'false').
     *
     * @param boolean|integer|string $v The new value
     * @return Propiedad The current object (for fluent API support)
     */
    public function setNegociable($v)
    {
        if ($v !== null) {
            if (is_string($v)) {
                $v = in_array(strtolower($v), array('false', 'off', '-', 'no', 'n', '0', '')) ? false : true;
            } else {
                $v = (boolean) $v;
            }
        }

        if ($this->negociable !== $v) {
            $this->negociable = $v;
            $this->modifiedColumns[] = PropiedadPeer::NEGOCIABLE;
        }


        return $this;
    } // setNegociable()

    /**
     * Sets the value of the [incluye_gastos_escritura] column.
     * Non-boolean arguments are converted using the following rules:
     *   * 1, '1', 'true',  'on',  and 'yes' are converted to boolean true
     *   * 0, '0', 'false', 'off', and 'no'  are converted to boolean false
     * Check on string values is case insensitive (so 'FaLsE' is seen as 'false').
     *
     * @param boolean|integer|string $v The new value
     * @return Propiedad The current object (for fluent API support)
     */
    public function setIncluyeGastosEscritura($v)
    {
        if ($v !== null) {
            if (is_string($v)) {
                $v = in_array(strtolower($v), array('false', 'off', '-', 'no', 'n', '0', '')) ? false : true;
            } else {
                $v = (boolean) $v;
            }
        }

        if ($this->incluye_gastos_escritura !== $v) {
            $this->incluye_gastos_escritura = $v;
            $this->modifiedColumns[] = PropiedadPeer::INCLUYE_GASTOS_ESCRITURA;
        }


        return $this;
    } // setIncluyeGastosEscritura()

    /**
     * Set the value of [anio_construccion] column.
     *
     * @param int $v new value
     * @return Propiedad The current object (for fluent API support)
     */
    public function setAnioConstruccion($v)
    {
        if ($v !== null) {
            $v = (int) $v;
        }

        if ($this->anio_construccion !== $v) {
            $this->anio_construccion = $v;
            $this->modifiedColumns[] = PropiedadPeer::ANIO_CONSTRUCCION;
        }


        return $this;
    } // setAnioConstruccion()

    /**
     * Set the value of [mantenimiento_mensual] column.
     *
     * @param double $v new value
     * @return Propiedad The current object (for fluent API support)
     */
    public function setMantenimientoMensual($v)
    {
        if ($v !== null) {
            $v = (double) $v;
        }

        if ($this->mantenimiento_mensual !== $v) {
            $this->mantenimiento_mensual = $v;
            $this->modifiedColumns[] = PropiedadPeer::MANTENIMIENTO_MENSUAL;
        }


        return $this;
    } // setMantenimientoMensual()

    /**
     * Set the value of [iusi_semestral] column.
     *
     * @param double $v new value
     * @return Propiedad The current object (for fluent API support)
     */
    public function setIusiSemestral($v)
    {
        if ($v !== null) {
            $v = (double) $v;
        }

        if ($this->iusi_semestral !== $v) {
            $this->iusi_semestral = $v;
            $this->modifiedColumns[] = PropiedadPeer::IUSI_SEMESTRAL;
        }


        return $this;
    } // setIusiSemestral()

    /**
     * Set the value of [valor_avaluo] column.
     *
     * @param double $v new value
     * @return Propiedad The current object (for fluent API support)
     */
    public function setValorAvaluo($v)
    {
        if ($v !== null) {
            $v = (double) $v;
        }

        if ($this->valor_avaluo !== $v) {
            $this->valor_avaluo = $v;
            $this->modifiedColumns[] = PropiedadPeer::VALOR_AVALUO;
        }


        return $this;
    } // setValorAvaluo()

    /**
     * Sets the value of [created_at] column to a normalized version of the date/time value specified.
     *
     * @param mixed $v string, integer (timestamp), or DateTime value.
     *               Empty strings are treated as null.
     * @return Propiedad The current object (for fluent API support)
     */
    public function setCreatedAt($v)
    {
        $dt = PropelDateTime::newInstance($v, null, 'DateTime');
        if ($this->created_at !== null || $dt !== null) {
            $currentDateAsString = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
            $newDateAsString = $dt ? $dt->format('Y-m-d H:i:s') : null;
            if ($currentDateAsString !== $newDateAsString) {
                $this->created_at = $newDateAsString;
                $this->modifiedColumns[] = PropiedadPeer::CREATED_AT;
            }
        } // if either are not null


        return $this;
    } // setCreatedAt()

    /**
     * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
     *
     * @param mixed $v string, integer (timestamp), or DateTime value.
     *               Empty strings are treated as null.
     * @return Propiedad The current object (for fluent API support)
     */
    public function setUpdatedAt($v)
    {
        $dt = PropelDateTime::newInstance($v, null, 'DateTime');
        if ($this->updated_at !== null || $dt !== null) {
            $currentDateAsString = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
            $newDateAsString = $dt ? $dt->format('Y-m-d H:i:s') : null;
            if ($currentDateAsString !== $newDateAsString) {
                $this->updated_at = $newDateAsString;
                $this->modifiedColumns[] = PropiedadPeer::UPDATED_AT;
            }
        } // if either are not null


        return $this;
    } // setUpdatedAt()

    /**
     * Set the value of [created_by] column.
     *
     * @param string $v new value
     * @return Propiedad The current object (for fluent API support)
     */
    public function setCreatedBy($v)
    {
        if ($v !== null) {
            $v = (string) $v;
        }

        if ($this->created_by !== $v) {
            $this->created_by = $v;
            $this->modifiedColumns[] = PropiedadPeer::CREATED_BY;
        }


        return $this;
    } // setCreatedBy()

    /**
     * Set the value of [updated_by] column.
     *
     * @param string $v new value
     * @return Propiedad The current object (for fluent API support)
     */
    public function setUpdatedBy($v)
    {
        if ($v !== null) {
            $v = (string) $v;
        }

        if ($this->updated_by !== $v) {
            $this->updated_by = $v;
            $this->modifiedColumns[] = PropiedadPeer::UPDATED_BY;
        }


        return $this;
    } // setUpdatedBy()

    /**
     * Indicates whether the columns in this object are only set to default values.
     *
     * This method can be used in conjunction with isModified() to indicate whether an object is both
     * modified _and_ has some values set which are non-default.
     *
     * @return boolean Whether the columns in this object are only been set with default values.
     */
    public function hasOnlyDefaultValues()
    {
            if ($this->dormitorio_servicio !== false) {
                return false;
            }

            if ($this->estudio !== false) {
                return false;
            }

            if ($this->cisterna !== false) {
                return false;
            }

            if ($this->lavanderia !== false) {
                return false;
            }

            if ($this->negociable !== false) {
                return false;
            }

            if ($this->incluye_gastos_escritura !== false) {
                return false;
            }

        // otherwise, everything was equal, so return true
        return true;
    } // hasOnlyDefaultValues()

    /**
     * Hydrates (populates) the object variables with values from the database resultset.
     *
     * An offset (0-based "start column") is specified so that objects can be hydrated
     * with a subset of the columns in the resultset rows.  This is needed, for example,
     * for results of JOIN queries where the resultset row includes columns from two or
     * more tables.
     *
     * @param array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
     * @param int $startcol 0-based offset column which indicates which restultset column to start with.
     * @param boolean $rehydrate Whether this object is being re-hydrated from the database.
     * @return int             next starting column
     * @throws PropelException - Any caught Exception will be rewrapped as a PropelException.
     */
    public function hydrate($row, $startcol = 0, $rehydrate = false)
    {
        try {

            $this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
            $this->tipo_operacion = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
            $this->tipo_inmueble = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
            $this->cantidad_habitacion = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
            $this->cantidad_banio = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
            $this->cantidad_parqueo = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
            $this->cantidad_comedor = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
            $this->cantidad_sala = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
            $this->cantidad_cocina = ($row[$startcol + 8] !== null) ? (int) $row[$startcol + 8] : null;
            $this->dormitorio_servicio = ($row[$startcol + 9] !== null) ? (boolean) $row[$startcol + 9] : null;
            $this->estudio = ($row[$startcol + 10] !== null) ? (boolean) $row[$startcol + 10] : null;
            $this->cisterna = ($row[$startcol + 11] !== null) ? (boolean) $row[$startcol + 11] : null;
            $this->cantidad_jardin = ($row[$startcol + 12] !== null) ? (int) $row[$startcol + 12] : null;
            $this->cantidad_patio = ($row[$startcol + 13] !== null) ? (int) $row[$startcol + 13] : null;
            $this->lavanderia = ($row[$startcol + 14] !== null) ? (boolean) $row[$startcol + 14] : null;
            $this->estado = ($row[$startcol + 15] !== null) ? (string) $row[$startcol + 15] : null;
            $this->amenidades = ($row[$startcol + 16] !== null) ? (string) $row[$startcol + 16] : null;
            $this->precio = ($row[$startcol + 17] !== null) ? (double) $row[$startcol + 17] : null;
            $this->negociable = ($row[$startcol + 18] !== null) ? (boolean) $row[$startcol + 18] : null;
            $this->incluye_gastos_escritura = ($row[$startcol + 19] !== null) ? (boolean) $row[$startcol + 19] : null;
            $this->anio_construccion = ($row[$startcol + 20] !== null) ? (int) $row[$startcol + 20] : null;
            $this->mantenimiento_mensual = ($row[$startcol + 21] !== null) ? (double) $row[$startcol + 21] : null;
            $this->iusi_semestral = ($row[$startcol + 22] !== null) ? (double) $row[$startcol + 22] : null;
            $this->valor_avaluo = ($row[$startcol + 23] !== null) ? (double) $row[$startcol + 23] : null;
            $this->created_at = ($row[$startcol + 24] !== null) ? (string) $row[$startcol + 24] : null;
            $this->updated_at = ($row[$startcol + 25] !== null) ? (string) $row[$startcol + 25] : null;
            $this->created_by = ($row[$startcol + 26] !== null) ? (string) $row[$startcol + 26] : null;
            $this->updated_by = ($row[$startcol + 27] !== null) ? (string) $row[$startcol + 27] : null;
            $this->resetModified();

            $this->setNew(false);

            if ($rehydrate) {
                $this->ensureConsistency();
            }

            return $startcol + 28; // 28 = PropiedadPeer::NUM_HYDRATE_COLUMNS.

        } catch (Exception $e) {
            throw new PropelException("Error populating Propiedad object", $e);
        }
    }

    /**
     * Checks and repairs the internal consistency of the object.
     *
     * This method is executed after an already-instantiated object is re-hydrated
     * from the database.  It exists to check any foreign keys to make sure that
     * the objects related to the current object are correct based on foreign key.
     *
     * You can override this method in the stub class, but you should always invoke
     * the base method from the overridden method (i.e. parent::ensureConsistency()),
     * in case your model changes.
     *
     * @throws PropelException
     */
    public function ensureConsistency()
    {

    } // ensureConsistency

    /**
     * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
     *
     * This will only work if the object has been saved and has a valid primary key set.
     *
     * @param boolean $deep (optional) Whether to also de-associated any related objects.
     * @param PropelPDO $con (optional) The PropelPDO connection to use.
     * @return void
     * @throws PropelException - if this object is deleted, unsaved or doesn't have pk match in db
     */
    public function reload($deep = false, PropelPDO $con = null)
    {
        if ($this->isDeleted()) {
            throw new PropelException("Cannot reload a deleted object.");
        }

        if ($this->isNew()) {
            throw new PropelException("Cannot reload an unsaved object.");
        }

        if ($con === null) {
            $con = Propel::getConnection(PropiedadPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

        // We don't need to alter the object instance pool; we're just modifying this instance
        // already in the pool.

        $stmt = PropiedadPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
        $row = $stmt->fetch(PDO::FETCH_NUM);
        $stmt->closeCursor();
        if (!$row) {
            throw new PropelException('Cannot find matching row in the database to reload object values.');
        }
        $this->hydrate($row, 0, true); // rehydrate

        if ($deep) {  // also de-associate any related objects?

        } // if (deep)
    }

    /**
     * Removes this object from datastore and sets delete attribute.
     *
     * @param PropelPDO $con
     * @return void
     * @throws PropelException
     * @throws Exception
     * @see        BaseObject::setDeleted()
     * @see        BaseObject::isDeleted()
     */
    public function delete(PropelPDO $con = null)
    {
        if ($this->isDeleted()) {
            throw new PropelException("This object has already been deleted.");
        }

        if ($con === null) {
            $con = Propel::getConnection(PropiedadPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        $con->beginTransaction();
        try {
            $deleteQuery = PropiedadQuery::create()
                ->filterByPrimaryKey($this->getPrimaryKey());
            $ret = $this->preDelete($con);
            // symfony_behaviors behavior
            foreach (sfMixer::getCallables('BasePropiedad:delete:pre') as $callable)
            {
              if (call_user_func($callable, $this, $con))
              {
                $con->commit();
                return;
              }
            }

            if ($ret) {
                $deleteQuery->delete($con);
                $this->postDelete($con);
                // symfony_behaviors behavior
                foreach (sfMixer::getCallables('BasePropiedad:delete:post') as $callable)
                {
                  call_user_func($callable, $this, $con);
                }

                $con->commit();
                $this->setDeleted(true);
            } else {
                $con->commit();
            }
        } catch (Exception $e) {
            $con->rollBack();
            throw $e;
        }
    }

    /**
     * Persists this object to the database.
     *
     * If the object is new, it inserts it; otherwise an update is performed.
     * All modified related objects will also be persisted in the doSave()
     * method.  This method wraps all precipitate database operations in a
     * single transaction.
     *
     * @param PropelPDO $con
     * @return int             The number of rows affected by this insert/update and any referring fk objects' save() operations.
     * @throws PropelException
     * @throws Exception
     * @see        doSave()
     */
    public function save(PropelPDO $con = null)
    {
        if ($this->isDeleted()) {
            throw new PropelException("You cannot save an object that has been deleted.");
        }

        if ($con === null) {
            $con = Propel::getConnection(PropiedadPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        $con->beginTransaction();
        $isInsert = $this->isNew();
        try {
            $ret = $this->preSave($con);
            // symfony_behaviors behavior
            foreach (sfMixer::getCallables('BasePropiedad:save:pre') as $callable)
            {
              if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
              {
                  $con->commit();
                return $affectedRows;
              }
            }

            // symfony_timestampable behavior
            if ($this->isModified() && !$this->isColumnModified(PropiedadPeer::UPDATED_AT))
            {
                $this->setUpdatedAt(time());
            }
            if ($isInsert) {
                $ret = $ret && $this->preInsert($con);
                // symfony_timestampable behavior
                if (!$this->isColumnModified(PropiedadPeer::CREATED_AT))
                {
                  $this->setCreatedAt(time());
                }

            } else {
                $ret = $ret && $this->preUpdate($con);
            }
            if ($ret) {
                $affectedRows = $this->doSave($con);
                if ($isInsert) {
                    $this->postInsert($con);
                } else {
                    $this->postUpdate($con);
                }
                $this->postSave($con);
                // symfony_behaviors behavior
                foreach (sfMixer::getCallables('BasePropiedad:save:post') as $callable)
                {
                  call_user_func($callable, $this, $con, $affectedRows);
                }

                PropiedadPeer::addInstanceToPool($this);
            } else {
                $affectedRows = 0;
            }
            $con->commit();

            return $affectedRows;
        } catch (Exception $e) {
            $con->rollBack();
            throw $e;
        }
    }

    /**
     * Performs the work of inserting or updating the row in the database.
     *
     * If the object is new, it inserts it; otherwise an update is performed.
     * All related objects are also updated in this method.
     *
     * @param PropelPDO $con
     * @return int             The number of rows affected by this insert/update and any referring fk objects' save() operations.
     * @throws PropelException
     * @see        save()
     */
    protected function doSave(PropelPDO $con)
    {
        $affectedRows = 0; // initialize var to track total num of affected rows
        if (!$this->alreadyInSave) {
            $this->alreadyInSave = true;

            if ($this->isNew() || $this->isModified()) {
                // persist changes
                if ($this->isNew()) {
                    $this->doInsert($con);
                } else {
                    $this->doUpdate($con);
                }
                $affectedRows += 1;
                $this->resetModified();
            }

            $this->alreadyInSave = false;

        }

        return $affectedRows;
    } // doSave()

    /**
     * Insert the row in the database.
     *
     * @param PropelPDO $con
     *
     * @throws PropelException
     * @see        doSave()
     */
    protected function doInsert(PropelPDO $con)
    {
        $modifiedColumns = array();
        $index = 0;

        $this->modifiedColumns[] = PropiedadPeer::ID;
        if (null !== $this->id) {
            throw new PropelException('Cannot insert a value for auto-increment primary key (' . PropiedadPeer::ID . ')');
        }

         // check the columns in natural order for more readable SQL queries
        if ($this->isColumnModified(PropiedadPeer::ID)) {
            $modifiedColumns[':p' . $index++]  = '`ID`';
        }
        if ($this->isColumnModified(PropiedadPeer::TIPO_OPERACION)) {
            $modifiedColumns[':p' . $index++]  = '`TIPO_OPERACION`';
        }
        if ($this->isColumnModified(PropiedadPeer::TIPO_INMUEBLE)) {
            $modifiedColumns[':p' . $index++]  = '`TIPO_INMUEBLE`';
        }
        if ($this->isColumnModified(PropiedadPeer::CANTIDAD_HABITACION)) {
            $modifiedColumns[':p' . $index++]  = '`CANTIDAD_HABITACION`';
        }
        if ($this->isColumnModified(PropiedadPeer::CANTIDAD_BANIO)) {
            $modifiedColumns[':p' . $index++]  = '`CANTIDAD_BANIO`';
        }
        if ($this->isColumnModified(PropiedadPeer::CANTIDAD_PARQUEO)) {
            $modifiedColumns[':p' . $index++]  = '`CANTIDAD_PARQUEO`';
        }
        if ($this->isColumnModified(PropiedadPeer::CANTIDAD_COMEDOR)) {
            $modifiedColumns[':p' . $index++]  = '`CANTIDAD_COMEDOR`';
        }
        if ($this->isColumnModified(PropiedadPeer::CANTIDAD_SALA)) {
            $modifiedColumns[':p' . $index++]  = '`CANTIDAD_SALA`';
        }
        if ($this->isColumnModified(PropiedadPeer::CANTIDAD_COCINA)) {
            $modifiedColumns[':p' . $index++]  = '`CANTIDAD_COCINA`';
        }
        if ($this->isColumnModified(PropiedadPeer::DORMITORIO_SERVICIO)) {
            $modifiedColumns[':p' . $index++]  = '`DORMITORIO_SERVICIO`';
        }
        if ($this->isColumnModified(PropiedadPeer::ESTUDIO)) {
            $modifiedColumns[':p' . $index++]  = '`ESTUDIO`';
        }
        if ($this->isColumnModified(PropiedadPeer::CISTERNA)) {
            $modifiedColumns[':p' . $index++]  = '`CISTERNA`';
        }
        if ($this->isColumnModified(PropiedadPeer::CANTIDAD_JARDIN)) {
            $modifiedColumns[':p' . $index++]  = '`CANTIDAD_JARDIN`';
        }
        if ($this->isColumnModified(PropiedadPeer::CANTIDAD_PATIO)) {
            $modifiedColumns[':p' . $index++]  = '`CANTIDAD_PATIO`';
        }
        if ($this->isColumnModified(PropiedadPeer::LAVANDERIA)) {
            $modifiedColumns[':p' . $index++]  = '`LAVANDERIA`';
        }
        if ($this->isColumnModified(PropiedadPeer::ESTADO)) {
            $modifiedColumns[':p' . $index++]  = '`ESTADO`';
        }
        if ($this->isColumnModified(PropiedadPeer::AMENIDADES)) {
            $modifiedColumns[':p' . $index++]  = '`AMENIDADES`';
        }
        if ($this->isColumnModified(PropiedadPeer::PRECIO)) {
            $modifiedColumns[':p' . $index++]  = '`PRECIO`';
        }
        if ($this->isColumnModified(PropiedadPeer::NEGOCIABLE)) {
            $modifiedColumns[':p' . $index++]  = '`NEGOCIABLE`';
        }
        if ($this->isColumnModified(PropiedadPeer::INCLUYE_GASTOS_ESCRITURA)) {
            $modifiedColumns[':p' . $index++]  = '`INCLUYE_GASTOS_ESCRITURA`';
        }
        if ($this->isColumnModified(PropiedadPeer::ANIO_CONSTRUCCION)) {
            $modifiedColumns[':p' . $index++]  = '`ANIO_CONSTRUCCION`';
        }
        if ($this->isColumnModified(PropiedadPeer::MANTENIMIENTO_MENSUAL)) {
            $modifiedColumns[':p' . $index++]  = '`MANTENIMIENTO_MENSUAL`';
        }
        if ($this->isColumnModified(PropiedadPeer::IUSI_SEMESTRAL)) {
            $modifiedColumns[':p' . $index++]  = '`IUSI_SEMESTRAL`';
        }
        if ($this->isColumnModified(PropiedadPeer::VALOR_AVALUO)) {
            $modifiedColumns[':p' . $index++]  = '`VALOR_AVALUO`';
        }
        if ($this->isColumnModified(PropiedadPeer::CREATED_AT)) {
            $modifiedColumns[':p' . $index++]  = '`CREATED_AT`';
        }
        if ($this->isColumnModified(PropiedadPeer::UPDATED_AT)) {
            $modifiedColumns[':p' . $index++]  = '`UPDATED_AT`';
        }
        if ($this->isColumnModified(PropiedadPeer::CREATED_BY)) {
            $modifiedColumns[':p' . $index++]  = '`CREATED_BY`';
        }
        if ($this->isColumnModified(PropiedadPeer::UPDATED_BY)) {
            $modifiedColumns[':p' . $index++]  = '`UPDATED_BY`';
        }

        $sql = sprintf(
            'INSERT INTO `propiedad` (%s) VALUES (%s)',
            implode(', ', $modifiedColumns),
            implode(', ', array_keys($modifiedColumns))
        );

        try {
            $stmt = $con->prepare($sql);
            foreach ($modifiedColumns as $identifier => $columnName) {
                switch ($columnName) {
                    case '`ID`':
                        $stmt->bindValue($identifier, $this->id, PDO::PARAM_INT);
                        break;
                    case '`TIPO_OPERACION`':
                        $stmt->bindValue($identifier, $this->tipo_operacion, PDO::PARAM_STR);
                        break;
                    case '`TIPO_INMUEBLE`':
                        $stmt->bindValue($identifier, $this->tipo_inmueble, PDO::PARAM_STR);
                        break;
                    case '`CANTIDAD_HABITACION`':
                        $stmt->bindValue($identifier, $this->cantidad_habitacion, PDO::PARAM_INT);
                        break;
                    case '`CANTIDAD_BANIO`':
                        $stmt->bindValue($identifier, $this->cantidad_banio, PDO::PARAM_INT);
                        break;
                    case '`CANTIDAD_PARQUEO`':
                        $stmt->bindValue($identifier, $this->cantidad_parqueo, PDO::PARAM_INT);
                        break;
                    case '`CANTIDAD_COMEDOR`':
                        $stmt->bindValue($identifier, $this->cantidad_comedor, PDO::PARAM_INT);
                        break;
                    case '`CANTIDAD_SALA`':
                        $stmt->bindValue($identifier, $this->cantidad_sala, PDO::PARAM_INT);
                        break;
                    case '`CANTIDAD_COCINA`':
                        $stmt->bindValue($identifier, $this->cantidad_cocina, PDO::PARAM_INT);
                        break;
                    case '`DORMITORIO_SERVICIO`':
                        $stmt->bindValue($identifier, (int) $this->dormitorio_servicio, PDO::PARAM_INT);
                        break;
                    case '`ESTUDIO`':
                        $stmt->bindValue($identifier, (int) $this->estudio, PDO::PARAM_INT);
                        break;
                    case '`CISTERNA`':
                        $stmt->bindValue($identifier, (int) $this->cisterna, PDO::PARAM_INT);
                        break;
                    case '`CANTIDAD_JARDIN`':
                        $stmt->bindValue($identifier, $this->cantidad_jardin, PDO::PARAM_INT);
                        break;
                    case '`CANTIDAD_PATIO`':
                        $stmt->bindValue($identifier, $this->cantidad_patio, PDO::PARAM_INT);
                        break;
                    case '`LAVANDERIA`':
                        $stmt->bindValue($identifier, (int) $this->lavanderia, PDO::PARAM_INT);
                        break;
                    case '`ESTADO`':
                        $stmt->bindValue($identifier, $this->estado, PDO::PARAM_STR);
                        break;
                    case '`AMENIDADES`':
                        $stmt->bindValue($identifier, $this->amenidades, PDO::PARAM_STR);
                        break;
                    case '`PRECIO`':
                        $stmt->bindValue($identifier, $this->precio, PDO::PARAM_STR);
                        break;
                    case '`NEGOCIABLE`':
                        $stmt->bindValue($identifier, (int) $this->negociable, PDO::PARAM_INT);
                        break;
                    case '`INCLUYE_GASTOS_ESCRITURA`':
                        $stmt->bindValue($identifier, (int) $this->incluye_gastos_escritura, PDO::PARAM_INT);
                        break;
                    case '`ANIO_CONSTRUCCION`':
                        $stmt->bindValue($identifier, $this->anio_construccion, PDO::PARAM_INT);
                        break;
                    case '`MANTENIMIENTO_MENSUAL`':
                        $stmt->bindValue($identifier, $this->mantenimiento_mensual, PDO::PARAM_STR);
                        break;
                    case '`IUSI_SEMESTRAL`':
                        $stmt->bindValue($identifier, $this->iusi_semestral, PDO::PARAM_STR);
                        break;
                    case '`VALOR_AVALUO`':
                        $stmt->bindValue($identifier, $this->valor_avaluo, PDO::PARAM_STR);
                        break;
                    case '`CREATED_AT`':
                        $stmt->bindValue($identifier, $this->created_at, PDO::PARAM_STR);
                        break;
                    case '`UPDATED_AT`':
                        $stmt->bindValue($identifier, $this->updated_at, PDO::PARAM_STR);
                        break;
                    case '`CREATED_BY`':
                        $stmt->bindValue($identifier, $this->created_by, PDO::PARAM_STR);
                        break;
                    case '`UPDATED_BY`':
                        $stmt->bindValue($identifier, $this->updated_by, PDO::PARAM_STR);
                        break;
                }
            }
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute INSERT statement [%s]', $sql), $e);
        }

        try {
            $pk = $con->lastInsertId();
        } catch (Exception $e) {
            throw new PropelException('Unable to get autoincrement id.', $e);
        }
        $this->setId($pk);

        $this->setNew(false);
    }

    /**
     * Update the row in the database.
     *
     * @param PropelPDO $con
     *
     * @see        doSave()
     */
    protected function doUpdate(PropelPDO $con)
    {
        $selectCriteria = $this->buildPkeyCriteria();
        $valuesCriteria = $this->buildCriteria();
        BasePeer::doUpdate($selectCriteria, $valuesCriteria, $con);
    }

    /**
     * Array of ValidationFailed objects.
     * @var        array ValidationFailed[]
     */
    protected $validationFailures = array();

    /**
     * Gets any ValidationFailed objects that resulted from last call to validate().
     *
     *
     * @return array ValidationFailed[]
     * @see        validate()
     */
    public function getValidationFailures()
    {
        return $this->validationFailures;
    }

    /**
     * Validates the objects modified field values and all objects related to this table.
     *
     * If $columns is either a column name or an array of column names
     * only those columns are validated.
     *
     * @param mixed $columns Column name or an array of column names.
     * @return boolean Whether all columns pass validation.
     * @see        doValidate()
     * @see        getValidationFailures()
     */
    public function validate($columns = null)
    {
        $res = $this->doValidate($columns);
        if ($res === true) {
            $this->validationFailures = array();

            return true;
        } else {
            $this->validationFailures = $res;

            return false;
        }
    }

    /**
     * This function performs the validation work for complex object models.
     *
     * In addition to checking the current object, all related objects will
     * also be validated.  If all pass then <code>true</code> is returned; otherwise
     * an aggreagated array of ValidationFailed objects will be returned.
     *
     * @param array $columns Array of column names to validate.
     * @return mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
     */
    protected function doValidate($columns = null)
    {
        if (!$this->alreadyInValidation) {
            $this->alreadyInValidation = true;
            $retval = null;

            $failureMap = array();


            if (($retval = PropiedadPeer::doValidate($this, $columns)) !== true) {
                $failureMap = array_merge($failureMap, $retval);
            }



            $this->alreadyInValidation = false;
        }

        return (!empty($failureMap) ? $failureMap : true);
    }

    /**
     * Retrieves a field from the object by name passed in as a string.
     *
     * @param string $name name
     * @param string $type The type of fieldname the $name is of:
     *               one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
     *               BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     *               Defaults to BasePeer::TYPE_PHPNAME
     * @return mixed Value of field.
     */
    public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
    {
        $pos = PropiedadPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
        $field = $this->getByPosition($pos);

        return $field;
    }

    /**
     * Retrieves a field from the object by Position as specified in the xml schema.
     * Zero-based.
     *
     * @param int $pos position in xml schema
     * @return mixed Value of field at $pos
     */
    public function getByPosition($pos)
    {
        switch ($pos) {
            case 0:
                return $this->getId();
                break;
            case 1:
                return $this->getTipoOperacion();
                break;
            case 2:
                return $this->getTipoInmueble();
                break;
            case 3:
                return $this->getCantidadHabitacion();
                break;
            case 4:
                return $this->getCantidadBanio();
                break;
            case 5:
                return $this->getCantidadParqueo();
                break;
            case 6:
                return $this->getCantidadComedor();
                break;
            case 7:
                return $this->getCantidadSala();
                break;
            case 8:
                return $this->getCantidadCocina();
                break;
            case 9:
                return $this->getDormitorioServicio();
                break;
            case 10:
                return $this->getEstudio();
                break;
            case 11:
                return $this->getCisterna();
                break;
            case 12:
                return $this->getCantidadJardin();
                break;
            case 13:
                return $this->getCantidadPatio();
                break;
            case 14:
                return $this->getLavanderia();
                break;
            case 15:
                return $this->getEstado();
                break;
            case 16:
                return $this->getAmenidades();
                break;
            case 17:
                return $this->getPrecio();
                break;
            case 18:
                return $this->getNegociable();
                break;
            case 19:
                return $this->getIncluyeGastosEscritura();
                break;
            case 20:
                return $this->getAnioConstruccion();
                break;
            case 21:
                return $this->getMantenimientoMensual();
                break;
            case 22:
                return $this->getIusiSemestral();
                break;
            case 23:
                return $this->getValorAvaluo();
                break;
            case 24:
                return $this->getCreatedAt();
                break;
            case 25:
                return $this->getUpdatedAt();
                break;
            case 26:
                return $this->getCreatedBy();
                break;
            case 27:
                return $this->getUpdatedBy();
                break;
            default:
                return null;
                break;
        } // switch()
    }

    /**
     * Exports the object as an array.
     *
     * You can specify the key type of the array by passing one of the class
     * type constants.
     *
     * @param     string  $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
     *                    BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     *                    Defaults to BasePeer::TYPE_PHPNAME.
     * @param     boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns. Defaults to true.
     * @param     array $alreadyDumpedObjects List of objects to skip to avoid recursion
     *
     * @return array an associative array containing the field names (as keys) and field values
     */
    public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true, $alreadyDumpedObjects = array())
    {
        if (isset($alreadyDumpedObjects['Propiedad'][$this->getPrimaryKey()])) {
            return '*RECURSION*';
        }
        $alreadyDumpedObjects['Propiedad'][$this->getPrimaryKey()] = true;
        $keys = PropiedadPeer::getFieldNames($keyType);
        $result = array(
            $keys[0] => $this->getId(),
            $keys[1] => $this->getTipoOperacion(),
            $keys[2] => $this->getTipoInmueble(),
            $keys[3] => $this->getCantidadHabitacion(),
            $keys[4] => $this->getCantidadBanio(),
            $keys[5] => $this->getCantidadParqueo(),
            $keys[6] => $this->getCantidadComedor(),
            $keys[7] => $this->getCantidadSala(),
            $keys[8] => $this->getCantidadCocina(),
            $keys[9] => $this->getDormitorioServicio(),
            $keys[10] => $this->getEstudio(),
            $keys[11] => $this->getCisterna(),
            $keys[12] => $this->getCantidadJardin(),
            $keys[13] => $this->getCantidadPatio(),
            $keys[14] => $this->getLavanderia(),
            $keys[15] => $this->getEstado(),
            $keys[16] => $this->getAmenidades(),
            $keys[17] => $this->getPrecio(),
            $keys[18] => $this->getNegociable(),
            $keys[19] => $this->getIncluyeGastosEscritura(),
            $keys[20] => $this->getAnioConstruccion(),
            $keys[21] => $this->getMantenimientoMensual(),
            $keys[22] => $this->getIusiSemestral(),
            $keys[23] => $this->getValorAvaluo(),
            $keys[24] => $this->getCreatedAt(),
            $keys[25] => $this->getUpdatedAt(),
            $keys[26] => $this->getCreatedBy(),
            $keys[27] => $this->getUpdatedBy(),
        );

        return $result;
    }

    /**
     * Sets a field from the object by name passed in as a string.
     *
     * @param string $name peer name
     * @param mixed $value field value
     * @param string $type The type of fieldname the $name is of:
     *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
     *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     *                     Defaults to BasePeer::TYPE_PHPNAME
     * @return void
     */
    public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
    {
        $pos = PropiedadPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);

        $this->setByPosition($pos, $value);
    }

    /**
     * Sets a field from the object by Position as specified in the xml schema.
     * Zero-based.
     *
     * @param int $pos position in xml schema
     * @param mixed $value field value
     * @return void
     */
    public function setByPosition($pos, $value)
    {
        switch ($pos) {
            case 0:
                $this->setId($value);
                break;
            case 1:
                $this->setTipoOperacion($value);
                break;
            case 2:
                $this->setTipoInmueble($value);
                break;
            case 3:
                $this->setCantidadHabitacion($value);
                break;
            case 4:
                $this->setCantidadBanio($value);
                break;
            case 5:
                $this->setCantidadParqueo($value);
                break;
            case 6:
                $this->setCantidadComedor($value);
                break;
            case 7:
                $this->setCantidadSala($value);
                break;
            case 8:
                $this->setCantidadCocina($value);
                break;
            case 9:
                $this->setDormitorioServicio($value);
                break;
            case 10:
                $this->setEstudio($value);
                break;
            case 11:
                $this->setCisterna($value);
                break;
            case 12:
                $this->setCantidadJardin($value);
                break;
            case 13:
                $this->setCantidadPatio($value);
                break;
            case 14:
                $this->setLavanderia($value);
                break;
            case 15:
                $this->setEstado($value);
                break;
            case 16:
                $this->setAmenidades($value);
                break;
            case 17:
                $this->setPrecio($value);
                break;
            case 18:
                $this->setNegociable($value);
                break;
            case 19:
                $this->setIncluyeGastosEscritura($value);
                break;
            case 20:
                $this->setAnioConstruccion($value);
                break;
            case 21:
                $this->setMantenimientoMensual($value);
                break;
            case 22:
                $this->setIusiSemestral($value);
                break;
            case 23:
                $this->setValorAvaluo($value);
                break;
            case 24:
                $this->setCreatedAt($value);
                break;
            case 25:
                $this->setUpdatedAt($value);
                break;
            case 26:
                $this->setCreatedBy($value);
                break;
            case 27:
                $this->setUpdatedBy($value);
                break;
        } // switch()
    }

    /**
     * Populates the object using an array.
     *
     * This is particularly useful when populating an object from one of the
     * request arrays (e.g. $_POST).  This method goes through the column
     * names, checking to see whether a matching key exists in populated
     * array. If so the setByName() method is called for that column.
     *
     * You can specify the key type of the array by additionally passing one
     * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
     * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     * The default key type is the column's BasePeer::TYPE_PHPNAME
     *
     * @param array  $arr     An array to populate the object from.
     * @param string $keyType The type of keys the array uses.
     * @return void
     */
    public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
    {
        $keys = PropiedadPeer::getFieldNames($keyType);

        if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
        if (array_key_exists($keys[1], $arr)) $this->setTipoOperacion($arr[$keys[1]]);
        if (array_key_exists($keys[2], $arr)) $this->setTipoInmueble($arr[$keys[2]]);
        if (array_key_exists($keys[3], $arr)) $this->setCantidadHabitacion($arr[$keys[3]]);
        if (array_key_exists($keys[4], $arr)) $this->setCantidadBanio($arr[$keys[4]]);
        if (array_key_exists($keys[5], $arr)) $this->setCantidadParqueo($arr[$keys[5]]);
        if (array_key_exists($keys[6], $arr)) $this->setCantidadComedor($arr[$keys[6]]);
        if (array_key_exists($keys[7], $arr)) $this->setCantidadSala($arr[$keys[7]]);
        if (array_key_exists($keys[8], $arr)) $this->setCantidadCocina($arr[$keys[8]]);
        if (array_key_exists($keys[9], $arr)) $this->setDormitorioServicio($arr[$keys[9]]);
        if (array_key_exists($keys[10], $arr)) $this->setEstudio($arr[$keys[10]]);
        if (array_key_exists($keys[11], $arr)) $this->setCisterna($arr[$keys[11]]);
        if (array_key_exists($keys[12], $arr)) $this->setCantidadJardin($arr[$keys[12]]);
        if (array_key_exists($keys[13], $arr)) $this->setCantidadPatio($arr[$keys[13]]);
        if (array_key_exists($keys[14], $arr)) $this->setLavanderia($arr[$keys[14]]);
        if (array_key_exists($keys[15], $arr)) $this->setEstado($arr[$keys[15]]);
        if (array_key_exists($keys[16], $arr)) $this->setAmenidades($arr[$keys[16]]);
        if (array_key_exists($keys[17], $arr)) $this->setPrecio($arr[$keys[17]]);
        if (array_key_exists($keys[18], $arr)) $this->setNegociable($arr[$keys[18]]);
        if (array_key_exists($keys[19], $arr)) $this->setIncluyeGastosEscritura($arr[$keys[19]]);
        if (array_key_exists($keys[20], $arr)) $this->setAnioConstruccion($arr[$keys[20]]);
        if (array_key_exists($keys[21], $arr)) $this->setMantenimientoMensual($arr[$keys[21]]);
        if (array_key_exists($keys[22], $arr)) $this->setIusiSemestral($arr[$keys[22]]);
        if (array_key_exists($keys[23], $arr)) $this->setValorAvaluo($arr[$keys[23]]);
        if (array_key_exists($keys[24], $arr)) $this->setCreatedAt($arr[$keys[24]]);
        if (array_key_exists($keys[25], $arr)) $this->setUpdatedAt($arr[$keys[25]]);
        if (array_key_exists($keys[26], $arr)) $this->setCreatedBy($arr[$keys[26]]);
        if (array_key_exists($keys[27], $arr)) $this->setUpdatedBy($arr[$keys[27]]);
    }

    /**
     * Build a Criteria object containing the values of all modified columns in this object.
     *
     * @return Criteria The Criteria object containing all modified values.
     */
    public function buildCriteria()
    {
        $criteria = new Criteria(PropiedadPeer::DATABASE_NAME);

        if ($this->isColumnModified(PropiedadPeer::ID)) $criteria->add(PropiedadPeer::ID, $this->id);
        if ($this->isColumnModified(PropiedadPeer::TIPO_OPERACION)) $criteria->add(PropiedadPeer::TIPO_OPERACION, $this->tipo_operacion);
        if ($this->isColumnModified(PropiedadPeer::TIPO_INMUEBLE)) $criteria->add(PropiedadPeer::TIPO_INMUEBLE, $this->tipo_inmueble);
        if ($this->isColumnModified(PropiedadPeer::CANTIDAD_HABITACION)) $criteria->add(PropiedadPeer::CANTIDAD_HABITACION, $this->cantidad_habitacion);
        if ($this->isColumnModified(PropiedadPeer::CANTIDAD_BANIO)) $criteria->add(PropiedadPeer::CANTIDAD_BANIO, $this->cantidad_banio);
        if ($this->isColumnModified(PropiedadPeer::CANTIDAD_PARQUEO)) $criteria->add(PropiedadPeer::CANTIDAD_PARQUEO, $this->cantidad_parqueo);
        if ($this->isColumnModified(PropiedadPeer::CANTIDAD_COMEDOR)) $criteria->add(PropiedadPeer::CANTIDAD_COMEDOR, $this->cantidad_comedor);
        if ($this->isColumnModified(PropiedadPeer::CANTIDAD_SALA)) $criteria->add(PropiedadPeer::CANTIDAD_SALA, $this->cantidad_sala);
        if ($this->isColumnModified(PropiedadPeer::CANTIDAD_COCINA)) $criteria->add(PropiedadPeer::CANTIDAD_COCINA, $this->cantidad_cocina);
        if ($this->isColumnModified(PropiedadPeer::DORMITORIO_SERVICIO)) $criteria->add(PropiedadPeer::DORMITORIO_SERVICIO, $this->dormitorio_servicio);
        if ($this->isColumnModified(PropiedadPeer::ESTUDIO)) $criteria->add(PropiedadPeer::ESTUDIO, $this->estudio);
        if ($this->isColumnModified(PropiedadPeer::CISTERNA)) $criteria->add(PropiedadPeer::CISTERNA, $this->cisterna);
        if ($this->isColumnModified(PropiedadPeer::CANTIDAD_JARDIN)) $criteria->add(PropiedadPeer::CANTIDAD_JARDIN, $this->cantidad_jardin);
        if ($this->isColumnModified(PropiedadPeer::CANTIDAD_PATIO)) $criteria->add(PropiedadPeer::CANTIDAD_PATIO, $this->cantidad_patio);
        if ($this->isColumnModified(PropiedadPeer::LAVANDERIA)) $criteria->add(PropiedadPeer::LAVANDERIA, $this->lavanderia);
        if ($this->isColumnModified(PropiedadPeer::ESTADO)) $criteria->add(PropiedadPeer::ESTADO, $this->estado);
        if ($this->isColumnModified(PropiedadPeer::AMENIDADES)) $criteria->add(PropiedadPeer::AMENIDADES, $this->amenidades);
        if ($this->isColumnModified(PropiedadPeer::PRECIO)) $criteria->add(PropiedadPeer::PRECIO, $this->precio);
        if ($this->isColumnModified(PropiedadPeer::NEGOCIABLE)) $criteria->add(PropiedadPeer::NEGOCIABLE, $this->negociable);
        if ($this->isColumnModified(PropiedadPeer::INCLUYE_GASTOS_ESCRITURA)) $criteria->add(PropiedadPeer::INCLUYE_GASTOS_ESCRITURA, $this->incluye_gastos_escritura);
        if ($this->isColumnModified(PropiedadPeer::ANIO_CONSTRUCCION)) $criteria->add(PropiedadPeer::ANIO_CONSTRUCCION, $this->anio_construccion);
        if ($this->isColumnModified(PropiedadPeer::MANTENIMIENTO_MENSUAL)) $criteria->add(PropiedadPeer::MANTENIMIENTO_MENSUAL, $this->mantenimiento_mensual);
        if ($this->isColumnModified(PropiedadPeer::IUSI_SEMESTRAL)) $criteria->add(PropiedadPeer::IUSI_SEMESTRAL, $this->iusi_semestral);
        if ($this->isColumnModified(PropiedadPeer::VALOR_AVALUO)) $criteria->add(PropiedadPeer::VALOR_AVALUO, $this->valor_avaluo);
        if ($this->isColumnModified(PropiedadPeer::CREATED_AT)) $criteria->add(PropiedadPeer::CREATED_AT, $this->created_at);
        if ($this->isColumnModified(PropiedadPeer::UPDATED_AT)) $criteria->add(PropiedadPeer::UPDATED_AT, $this->updated_at);
        if ($this->isColumnModified(PropiedadPeer::CREATED_BY)) $criteria->add(PropiedadPeer::CREATED_BY, $this->created_by);
        if ($this->isColumnModified(PropiedadPeer::UPDATED_BY)) $criteria->add(PropiedadPeer::UPDATED_BY, $this->updated_by);

        return $criteria;
    }

    /**
     * Builds a Criteria object containing the primary key for this object.
     *
     * Unlike buildCriteria() this method includes the primary key values regardless
     * of whether or not they have been modified.
     *
     * @return Criteria The Criteria object containing value(s) for primary key(s).
     */
    public function buildPkeyCriteria()
    {
        $criteria = new Criteria(PropiedadPeer::DATABASE_NAME);
        $criteria->add(PropiedadPeer::ID, $this->id);

        return $criteria;
    }

    /**
     * Returns the primary key for this object (row).
     * @return int
     */
    public function getPrimaryKey()
    {
        return $this->getId();
    }

    /**
     * Generic method to set the primary key (id column).
     *
     * @param  int $key Primary key.
     * @return void
     */
    public function setPrimaryKey($key)
    {
        $this->setId($key);
    }

    /**
     * Returns true if the primary key for this object is null.
     * @return boolean
     */
    public function isPrimaryKeyNull()
    {

        return null === $this->getId();
    }

    /**
     * Sets contents of passed object to values from current object.
     *
     * If desired, this method can also make copies of all associated (fkey referrers)
     * objects.
     *
     * @param object $copyObj An object of Propiedad (or compatible) type.
     * @param boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
     * @param boolean $makeNew Whether to reset autoincrement PKs and make the object new.
     * @throws PropelException
     */
    public function copyInto($copyObj, $deepCopy = false, $makeNew = true)
    {
        $copyObj->setTipoOperacion($this->getTipoOperacion());
        $copyObj->setTipoInmueble($this->getTipoInmueble());
        $copyObj->setCantidadHabitacion($this->getCantidadHabitacion());
        $copyObj->setCantidadBanio($this->getCantidadBanio());
        $copyObj->setCantidadParqueo($this->getCantidadParqueo());
        $copyObj->setCantidadComedor($this->getCantidadComedor());
        $copyObj->setCantidadSala($this->getCantidadSala());
        $copyObj->setCantidadCocina($this->getCantidadCocina());
        $copyObj->setDormitorioServicio($this->getDormitorioServicio());
        $copyObj->setEstudio($this->getEstudio());
        $copyObj->setCisterna($this->getCisterna());
        $copyObj->setCantidadJardin($this->getCantidadJardin());
        $copyObj->setCantidadPatio($this->getCantidadPatio());
        $copyObj->setLavanderia($this->getLavanderia());
        $copyObj->setEstado($this->getEstado());
        $copyObj->setAmenidades($this->getAmenidades());
        $copyObj->setPrecio($this->getPrecio());
        $copyObj->setNegociable($this->getNegociable());
        $copyObj->setIncluyeGastosEscritura($this->getIncluyeGastosEscritura());
        $copyObj->setAnioConstruccion($this->getAnioConstruccion());
        $copyObj->setMantenimientoMensual($this->getMantenimientoMensual());
        $copyObj->setIusiSemestral($this->getIusiSemestral());
        $copyObj->setValorAvaluo($this->getValorAvaluo());
        $copyObj->setCreatedAt($this->getCreatedAt());
        $copyObj->setUpdatedAt($this->getUpdatedAt());
        $copyObj->setCreatedBy($this->getCreatedBy());
        $copyObj->setUpdatedBy($this->getUpdatedBy());
        if ($makeNew) {
            $copyObj->setNew(true);
            $copyObj->setId(NULL); // this is a auto-increment column, so set to default value
        }
    }

    /**
     * Makes a copy of this object that will be inserted as a new row in table when saved.
     * It creates a new object filling in the simple attributes, but skipping any primary
     * keys that are defined for the table.
     *
     * If desired, this method can also make copies of all associated (fkey referrers)
     * objects.
     *
     * @param boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
     * @return Propiedad Clone of current object.
     * @throws PropelException
     */
    public function copy($deepCopy = false)
    {
        // we use get_class(), because this might be a subclass
        $clazz = get_class($this);
        $copyObj = new $clazz();
        $this->copyInto($copyObj, $deepCopy);

        return $copyObj;
    }

    /**
     * Returns a peer instance associated with this om.
     *
     * Since Peer classes are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     *
     * @return PropiedadPeer
     */
    public function getPeer()
    {
        if (self::$peer === null) {
            self::$peer = new PropiedadPeer();
        }

        return self::$peer;
    }

    /**
     * Clears the current object and sets all attributes to their default values
     */
    public function clear()
    {
        $this->id = null;
        $this->tipo_operacion = null;
        $this->tipo_inmueble = null;
        $this->cantidad_habitacion = null;
        $this->cantidad_banio = null;
        $this->cantidad_parqueo = null;
        $this->cantidad_comedor = null;
        $this->cantidad_sala = null;
        $this->cantidad_cocina = null;
        $this->dormitorio_servicio = null;
        $this->estudio = null;
        $this->cisterna = null;
        $this->cantidad_jardin = null;
        $this->cantidad_patio = null;
        $this->lavanderia = null;
        $this->estado = null;
        $this->amenidades = null;
        $this->precio = null;
        $this->negociable = null;
        $this->incluye_gastos_escritura = null;
        $this->anio_construccion = null;
        $this->mantenimiento_mensual = null;
        $this->iusi_semestral = null;
        $this->valor_avaluo = null;
        $this->created_at = null;
        $this->updated_at = null;
        $this->created_by = null;
        $this->updated_by = null;
        $this->alreadyInSave = false;
        $this->alreadyInValidation = false;
        $this->clearAllReferences();
        $this->applyDefaultValues();
        $this->resetModified();
        $this->setNew(true);
        $this->setDeleted(false);
    }

    /**
     * Resets all references to other model objects or collections of model objects.
     *
     * This method is a user-space workaround for PHP's inability to garbage collect
     * objects with circular references (even in PHP 5.3). This is currently necessary
     * when using Propel in certain daemon or large-volumne/high-memory operations.
     *
     * @param boolean $deep Whether to also clear the references on all referrer objects.
     */
    public function clearAllReferences($deep = false)
    {
        if ($deep) {
        } // if ($deep)

    }

    /**
     * return the string representation of this object
     *
     * @return string
     */
    public function __toString()
    {
        return (string) $this->exportTo(PropiedadPeer::DEFAULT_STRING_FORMAT);
    }

    /**
     * return true is the object is in saving state
     *
     * @return boolean
     */
    public function isAlreadyInSave()
    {
        return $this->alreadyInSave;
    }

    /**
     * Catches calls to virtual methods
     */
    public function __call($name, $params)
    {

        // symfony_behaviors behavior
        if ($callable = sfMixer::getCallable('BasePropiedad:' . $name))
        {
          array_unshift($params, $this);
          return call_user_func_array($callable, $params);
        }


        return parent::__call($name, $params);
    }

}
