<?php


/**
 * Base class that represents a row from the 'negocio' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Sun Mar 18 14:41:28 2018
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseNegocio extends BaseObject implements Persistent
{
    /**
     * Peer class name
     */
    const PEER = 'NegocioPeer';

    /**
     * The Peer class.
     * Instance provides a convenient way of calling static methods on a class
     * that calling code may not be able to identify.
     * @var        NegocioPeer
     */
    protected static $peer;

    /**
     * The flag var to prevent infinit loop in deep copy
     * @var       boolean
     */
    protected $startCopy = false;

    /**
     * The value for the id field.
     * @var        int
     */
    protected $id;

    /**
     * The value for the requerimiento_id field.
     * @var        int
     */
    protected $requerimiento_id;

    /**
     * The value for the propiedad_id field.
     * @var        int
     */
    protected $propiedad_id;

    /**
     * The value for the usuario_req field.
     * @var        int
     */
    protected $usuario_req;

    /**
     * The value for the usuario_prop field.
     * @var        int
     */
    protected $usuario_prop;

    /**
     * The value for the activo field.
     * Note: this column has a database default value of: true
     * @var        boolean
     */
    protected $activo;

    /**
     * @var        Requerimiento
     */
    protected $aRequerimiento;

    /**
     * @var        Propiedad
     */
    protected $aPropiedad;

    /**
     * @var        Usuario
     */
    protected $aUsuarioRelatedByUsuarioReq;

    /**
     * @var        Usuario
     */
    protected $aUsuarioRelatedByUsuarioProp;

    /**
     * @var        PropelObjectCollection|MensajeNegocio[] Collection to store aggregation of MensajeNegocio objects.
     */
    protected $collMensajeNegocios;
    protected $collMensajeNegociosPartial;

    /**
     * Flag to prevent endless save loop, if this object is referenced
     * by another object which falls in this transaction.
     * @var        boolean
     */
    protected $alreadyInSave = false;

    /**
     * Flag to prevent endless validation loop, if this object is referenced
     * by another object which falls in this transaction.
     * @var        boolean
     */
    protected $alreadyInValidation = false;

    /**
     * An array of objects scheduled for deletion.
     * @var		PropelObjectCollection
     */
    protected $mensajeNegociosScheduledForDeletion = null;

    /**
     * Applies default values to this object.
     * This method should be called from the object's constructor (or
     * equivalent initialization method).
     * @see        __construct()
     */
    public function applyDefaultValues()
    {
        $this->activo = true;
    }

    /**
     * Initializes internal state of BaseNegocio object.
     * @see        applyDefaults()
     */
    public function __construct()
    {
        parent::__construct();
        $this->applyDefaultValues();
    }

    /**
     * Get the [id] column value.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get the [requerimiento_id] column value.
     *
     * @return int
     */
    public function getRequerimientoId()
    {
        return $this->requerimiento_id;
    }

    /**
     * Get the [propiedad_id] column value.
     *
     * @return int
     */
    public function getPropiedadId()
    {
        return $this->propiedad_id;
    }

    /**
     * Get the [usuario_req] column value.
     *
     * @return int
     */
    public function getUsuarioReq()
    {
        return $this->usuario_req;
    }

    /**
     * Get the [usuario_prop] column value.
     *
     * @return int
     */
    public function getUsuarioProp()
    {
        return $this->usuario_prop;
    }

    /**
     * Get the [activo] column value.
     *
     * @return boolean
     */
    public function getActivo()
    {
        return $this->activo;
    }

    /**
     * Set the value of [id] column.
     *
     * @param int $v new value
     * @return Negocio The current object (for fluent API support)
     */
    public function setId($v)
    {
        if ($v !== null) {
            $v = (int) $v;
        }

        if ($this->id !== $v) {
            $this->id = $v;
            $this->modifiedColumns[] = NegocioPeer::ID;
        }


        return $this;
    } // setId()

    /**
     * Set the value of [requerimiento_id] column.
     *
     * @param int $v new value
     * @return Negocio The current object (for fluent API support)
     */
    public function setRequerimientoId($v)
    {
        if ($v !== null) {
            $v = (int) $v;
        }

        if ($this->requerimiento_id !== $v) {
            $this->requerimiento_id = $v;
            $this->modifiedColumns[] = NegocioPeer::REQUERIMIENTO_ID;
        }

        if ($this->aRequerimiento !== null && $this->aRequerimiento->getId() !== $v) {
            $this->aRequerimiento = null;
        }


        return $this;
    } // setRequerimientoId()

    /**
     * Set the value of [propiedad_id] column.
     *
     * @param int $v new value
     * @return Negocio The current object (for fluent API support)
     */
    public function setPropiedadId($v)
    {
        if ($v !== null) {
            $v = (int) $v;
        }

        if ($this->propiedad_id !== $v) {
            $this->propiedad_id = $v;
            $this->modifiedColumns[] = NegocioPeer::PROPIEDAD_ID;
        }

        if ($this->aPropiedad !== null && $this->aPropiedad->getId() !== $v) {
            $this->aPropiedad = null;
        }


        return $this;
    } // setPropiedadId()

    /**
     * Set the value of [usuario_req] column.
     *
     * @param int $v new value
     * @return Negocio The current object (for fluent API support)
     */
    public function setUsuarioReq($v)
    {
        if ($v !== null) {
            $v = (int) $v;
        }

        if ($this->usuario_req !== $v) {
            $this->usuario_req = $v;
            $this->modifiedColumns[] = NegocioPeer::USUARIO_REQ;
        }

        if ($this->aUsuarioRelatedByUsuarioReq !== null && $this->aUsuarioRelatedByUsuarioReq->getId() !== $v) {
            $this->aUsuarioRelatedByUsuarioReq = null;
        }


        return $this;
    } // setUsuarioReq()

    /**
     * Set the value of [usuario_prop] column.
     *
     * @param int $v new value
     * @return Negocio The current object (for fluent API support)
     */
    public function setUsuarioProp($v)
    {
        if ($v !== null) {
            $v = (int) $v;
        }

        if ($this->usuario_prop !== $v) {
            $this->usuario_prop = $v;
            $this->modifiedColumns[] = NegocioPeer::USUARIO_PROP;
        }

        if ($this->aUsuarioRelatedByUsuarioProp !== null && $this->aUsuarioRelatedByUsuarioProp->getId() !== $v) {
            $this->aUsuarioRelatedByUsuarioProp = null;
        }


        return $this;
    } // setUsuarioProp()

    /**
     * Sets the value of the [activo] column.
     * Non-boolean arguments are converted using the following rules:
     *   * 1, '1', 'true',  'on',  and 'yes' are converted to boolean true
     *   * 0, '0', 'false', 'off', and 'no'  are converted to boolean false
     * Check on string values is case insensitive (so 'FaLsE' is seen as 'false').
     *
     * @param boolean|integer|string $v The new value
     * @return Negocio The current object (for fluent API support)
     */
    public function setActivo($v)
    {
        if ($v !== null) {
            if (is_string($v)) {
                $v = in_array(strtolower($v), array('false', 'off', '-', 'no', 'n', '0', '')) ? false : true;
            } else {
                $v = (boolean) $v;
            }
        }

        if ($this->activo !== $v) {
            $this->activo = $v;
            $this->modifiedColumns[] = NegocioPeer::ACTIVO;
        }


        return $this;
    } // setActivo()

    /**
     * Indicates whether the columns in this object are only set to default values.
     *
     * This method can be used in conjunction with isModified() to indicate whether an object is both
     * modified _and_ has some values set which are non-default.
     *
     * @return boolean Whether the columns in this object are only been set with default values.
     */
    public function hasOnlyDefaultValues()
    {
            if ($this->activo !== true) {
                return false;
            }

        // otherwise, everything was equal, so return true
        return true;
    } // hasOnlyDefaultValues()

    /**
     * Hydrates (populates) the object variables with values from the database resultset.
     *
     * An offset (0-based "start column") is specified so that objects can be hydrated
     * with a subset of the columns in the resultset rows.  This is needed, for example,
     * for results of JOIN queries where the resultset row includes columns from two or
     * more tables.
     *
     * @param array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
     * @param int $startcol 0-based offset column which indicates which restultset column to start with.
     * @param boolean $rehydrate Whether this object is being re-hydrated from the database.
     * @return int             next starting column
     * @throws PropelException - Any caught Exception will be rewrapped as a PropelException.
     */
    public function hydrate($row, $startcol = 0, $rehydrate = false)
    {
        try {

            $this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
            $this->requerimiento_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
            $this->propiedad_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
            $this->usuario_req = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
            $this->usuario_prop = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
            $this->activo = ($row[$startcol + 5] !== null) ? (boolean) $row[$startcol + 5] : null;
            $this->resetModified();

            $this->setNew(false);

            if ($rehydrate) {
                $this->ensureConsistency();
            }

            return $startcol + 6; // 6 = NegocioPeer::NUM_HYDRATE_COLUMNS.

        } catch (Exception $e) {
            throw new PropelException("Error populating Negocio object", $e);
        }
    }

    /**
     * Checks and repairs the internal consistency of the object.
     *
     * This method is executed after an already-instantiated object is re-hydrated
     * from the database.  It exists to check any foreign keys to make sure that
     * the objects related to the current object are correct based on foreign key.
     *
     * You can override this method in the stub class, but you should always invoke
     * the base method from the overridden method (i.e. parent::ensureConsistency()),
     * in case your model changes.
     *
     * @throws PropelException
     */
    public function ensureConsistency()
    {

        if ($this->aRequerimiento !== null && $this->requerimiento_id !== $this->aRequerimiento->getId()) {
            $this->aRequerimiento = null;
        }
        if ($this->aPropiedad !== null && $this->propiedad_id !== $this->aPropiedad->getId()) {
            $this->aPropiedad = null;
        }
        if ($this->aUsuarioRelatedByUsuarioReq !== null && $this->usuario_req !== $this->aUsuarioRelatedByUsuarioReq->getId()) {
            $this->aUsuarioRelatedByUsuarioReq = null;
        }
        if ($this->aUsuarioRelatedByUsuarioProp !== null && $this->usuario_prop !== $this->aUsuarioRelatedByUsuarioProp->getId()) {
            $this->aUsuarioRelatedByUsuarioProp = null;
        }
    } // ensureConsistency

    /**
     * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
     *
     * This will only work if the object has been saved and has a valid primary key set.
     *
     * @param boolean $deep (optional) Whether to also de-associated any related objects.
     * @param PropelPDO $con (optional) The PropelPDO connection to use.
     * @return void
     * @throws PropelException - if this object is deleted, unsaved or doesn't have pk match in db
     */
    public function reload($deep = false, PropelPDO $con = null)
    {
        if ($this->isDeleted()) {
            throw new PropelException("Cannot reload a deleted object.");
        }

        if ($this->isNew()) {
            throw new PropelException("Cannot reload an unsaved object.");
        }

        if ($con === null) {
            $con = Propel::getConnection(NegocioPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

        // We don't need to alter the object instance pool; we're just modifying this instance
        // already in the pool.

        $stmt = NegocioPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
        $row = $stmt->fetch(PDO::FETCH_NUM);
        $stmt->closeCursor();
        if (!$row) {
            throw new PropelException('Cannot find matching row in the database to reload object values.');
        }
        $this->hydrate($row, 0, true); // rehydrate

        if ($deep) {  // also de-associate any related objects?

            $this->aRequerimiento = null;
            $this->aPropiedad = null;
            $this->aUsuarioRelatedByUsuarioReq = null;
            $this->aUsuarioRelatedByUsuarioProp = null;
            $this->collMensajeNegocios = null;

        } // if (deep)
    }

    /**
     * Removes this object from datastore and sets delete attribute.
     *
     * @param PropelPDO $con
     * @return void
     * @throws PropelException
     * @throws Exception
     * @see        BaseObject::setDeleted()
     * @see        BaseObject::isDeleted()
     */
    public function delete(PropelPDO $con = null)
    {
        if ($this->isDeleted()) {
            throw new PropelException("This object has already been deleted.");
        }

        if ($con === null) {
            $con = Propel::getConnection(NegocioPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        $con->beginTransaction();
        try {
            $deleteQuery = NegocioQuery::create()
                ->filterByPrimaryKey($this->getPrimaryKey());
            $ret = $this->preDelete($con);
            // symfony_behaviors behavior
            foreach (sfMixer::getCallables('BaseNegocio:delete:pre') as $callable)
            {
              if (call_user_func($callable, $this, $con))
              {
                $con->commit();
                return;
              }
            }

            if ($ret) {
                $deleteQuery->delete($con);
                $this->postDelete($con);
                // symfony_behaviors behavior
                foreach (sfMixer::getCallables('BaseNegocio:delete:post') as $callable)
                {
                  call_user_func($callable, $this, $con);
                }

                $con->commit();
                $this->setDeleted(true);
            } else {
                $con->commit();
            }
        } catch (Exception $e) {
            $con->rollBack();
            throw $e;
        }
    }

    /**
     * Persists this object to the database.
     *
     * If the object is new, it inserts it; otherwise an update is performed.
     * All modified related objects will also be persisted in the doSave()
     * method.  This method wraps all precipitate database operations in a
     * single transaction.
     *
     * @param PropelPDO $con
     * @return int             The number of rows affected by this insert/update and any referring fk objects' save() operations.
     * @throws PropelException
     * @throws Exception
     * @see        doSave()
     */
    public function save(PropelPDO $con = null)
    {
        if ($this->isDeleted()) {
            throw new PropelException("You cannot save an object that has been deleted.");
        }

        if ($con === null) {
            $con = Propel::getConnection(NegocioPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        $con->beginTransaction();
        $isInsert = $this->isNew();
        try {
            $ret = $this->preSave($con);
            // symfony_behaviors behavior
            foreach (sfMixer::getCallables('BaseNegocio:save:pre') as $callable)
            {
              if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
              {
                  $con->commit();
                return $affectedRows;
              }
            }

            if ($isInsert) {
                $ret = $ret && $this->preInsert($con);
            } else {
                $ret = $ret && $this->preUpdate($con);
            }
            if ($ret) {
                $affectedRows = $this->doSave($con);
                if ($isInsert) {
                    $this->postInsert($con);
                } else {
                    $this->postUpdate($con);
                }
                $this->postSave($con);
                // symfony_behaviors behavior
                foreach (sfMixer::getCallables('BaseNegocio:save:post') as $callable)
                {
                  call_user_func($callable, $this, $con, $affectedRows);
                }

                NegocioPeer::addInstanceToPool($this);
            } else {
                $affectedRows = 0;
            }
            $con->commit();

            return $affectedRows;
        } catch (Exception $e) {
            $con->rollBack();
            throw $e;
        }
    }

    /**
     * Performs the work of inserting or updating the row in the database.
     *
     * If the object is new, it inserts it; otherwise an update is performed.
     * All related objects are also updated in this method.
     *
     * @param PropelPDO $con
     * @return int             The number of rows affected by this insert/update and any referring fk objects' save() operations.
     * @throws PropelException
     * @see        save()
     */
    protected function doSave(PropelPDO $con)
    {
        $affectedRows = 0; // initialize var to track total num of affected rows
        if (!$this->alreadyInSave) {
            $this->alreadyInSave = true;

            // We call the save method on the following object(s) if they
            // were passed to this object by their coresponding set
            // method.  This object relates to these object(s) by a
            // foreign key reference.

            if ($this->aRequerimiento !== null) {
                if ($this->aRequerimiento->isModified() || $this->aRequerimiento->isNew()) {
                    $affectedRows += $this->aRequerimiento->save($con);
                }
                $this->setRequerimiento($this->aRequerimiento);
            }

            if ($this->aPropiedad !== null) {
                if ($this->aPropiedad->isModified() || $this->aPropiedad->isNew()) {
                    $affectedRows += $this->aPropiedad->save($con);
                }
                $this->setPropiedad($this->aPropiedad);
            }

            if ($this->aUsuarioRelatedByUsuarioReq !== null) {
                if ($this->aUsuarioRelatedByUsuarioReq->isModified() || $this->aUsuarioRelatedByUsuarioReq->isNew()) {
                    $affectedRows += $this->aUsuarioRelatedByUsuarioReq->save($con);
                }
                $this->setUsuarioRelatedByUsuarioReq($this->aUsuarioRelatedByUsuarioReq);
            }

            if ($this->aUsuarioRelatedByUsuarioProp !== null) {
                if ($this->aUsuarioRelatedByUsuarioProp->isModified() || $this->aUsuarioRelatedByUsuarioProp->isNew()) {
                    $affectedRows += $this->aUsuarioRelatedByUsuarioProp->save($con);
                }
                $this->setUsuarioRelatedByUsuarioProp($this->aUsuarioRelatedByUsuarioProp);
            }

            if ($this->isNew() || $this->isModified()) {
                // persist changes
                if ($this->isNew()) {
                    $this->doInsert($con);
                } else {
                    $this->doUpdate($con);
                }
                $affectedRows += 1;
                $this->resetModified();
            }

            if ($this->mensajeNegociosScheduledForDeletion !== null) {
                if (!$this->mensajeNegociosScheduledForDeletion->isEmpty()) {
                    foreach ($this->mensajeNegociosScheduledForDeletion as $mensajeNegocio) {
                        // need to save related object because we set the relation to null
                        $mensajeNegocio->save($con);
                    }
                    $this->mensajeNegociosScheduledForDeletion = null;
                }
            }

            if ($this->collMensajeNegocios !== null) {
                foreach ($this->collMensajeNegocios as $referrerFK) {
                    if (!$referrerFK->isDeleted()) {
                        $affectedRows += $referrerFK->save($con);
                    }
                }
            }

            $this->alreadyInSave = false;

        }

        return $affectedRows;
    } // doSave()

    /**
     * Insert the row in the database.
     *
     * @param PropelPDO $con
     *
     * @throws PropelException
     * @see        doSave()
     */
    protected function doInsert(PropelPDO $con)
    {
        $modifiedColumns = array();
        $index = 0;

        $this->modifiedColumns[] = NegocioPeer::ID;
        if (null !== $this->id) {
            throw new PropelException('Cannot insert a value for auto-increment primary key (' . NegocioPeer::ID . ')');
        }

         // check the columns in natural order for more readable SQL queries
        if ($this->isColumnModified(NegocioPeer::ID)) {
            $modifiedColumns[':p' . $index++]  = '`ID`';
        }
        if ($this->isColumnModified(NegocioPeer::REQUERIMIENTO_ID)) {
            $modifiedColumns[':p' . $index++]  = '`REQUERIMIENTO_ID`';
        }
        if ($this->isColumnModified(NegocioPeer::PROPIEDAD_ID)) {
            $modifiedColumns[':p' . $index++]  = '`PROPIEDAD_ID`';
        }
        if ($this->isColumnModified(NegocioPeer::USUARIO_REQ)) {
            $modifiedColumns[':p' . $index++]  = '`USUARIO_REQ`';
        }
        if ($this->isColumnModified(NegocioPeer::USUARIO_PROP)) {
            $modifiedColumns[':p' . $index++]  = '`USUARIO_PROP`';
        }
        if ($this->isColumnModified(NegocioPeer::ACTIVO)) {
            $modifiedColumns[':p' . $index++]  = '`ACTIVO`';
        }

        $sql = sprintf(
            'INSERT INTO `negocio` (%s) VALUES (%s)',
            implode(', ', $modifiedColumns),
            implode(', ', array_keys($modifiedColumns))
        );

        try {
            $stmt = $con->prepare($sql);
            foreach ($modifiedColumns as $identifier => $columnName) {
                switch ($columnName) {
                    case '`ID`':
                        $stmt->bindValue($identifier, $this->id, PDO::PARAM_INT);
                        break;
                    case '`REQUERIMIENTO_ID`':
                        $stmt->bindValue($identifier, $this->requerimiento_id, PDO::PARAM_INT);
                        break;
                    case '`PROPIEDAD_ID`':
                        $stmt->bindValue($identifier, $this->propiedad_id, PDO::PARAM_INT);
                        break;
                    case '`USUARIO_REQ`':
                        $stmt->bindValue($identifier, $this->usuario_req, PDO::PARAM_INT);
                        break;
                    case '`USUARIO_PROP`':
                        $stmt->bindValue($identifier, $this->usuario_prop, PDO::PARAM_INT);
                        break;
                    case '`ACTIVO`':
                        $stmt->bindValue($identifier, (int) $this->activo, PDO::PARAM_INT);
                        break;
                }
            }
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute INSERT statement [%s]', $sql), $e);
        }

        try {
            $pk = $con->lastInsertId();
        } catch (Exception $e) {
            throw new PropelException('Unable to get autoincrement id.', $e);
        }
        $this->setId($pk);

        $this->setNew(false);
    }

    /**
     * Update the row in the database.
     *
     * @param PropelPDO $con
     *
     * @see        doSave()
     */
    protected function doUpdate(PropelPDO $con)
    {
        $selectCriteria = $this->buildPkeyCriteria();
        $valuesCriteria = $this->buildCriteria();
        BasePeer::doUpdate($selectCriteria, $valuesCriteria, $con);
    }

    /**
     * Array of ValidationFailed objects.
     * @var        array ValidationFailed[]
     */
    protected $validationFailures = array();

    /**
     * Gets any ValidationFailed objects that resulted from last call to validate().
     *
     *
     * @return array ValidationFailed[]
     * @see        validate()
     */
    public function getValidationFailures()
    {
        return $this->validationFailures;
    }

    /**
     * Validates the objects modified field values and all objects related to this table.
     *
     * If $columns is either a column name or an array of column names
     * only those columns are validated.
     *
     * @param mixed $columns Column name or an array of column names.
     * @return boolean Whether all columns pass validation.
     * @see        doValidate()
     * @see        getValidationFailures()
     */
    public function validate($columns = null)
    {
        $res = $this->doValidate($columns);
        if ($res === true) {
            $this->validationFailures = array();

            return true;
        } else {
            $this->validationFailures = $res;

            return false;
        }
    }

    /**
     * This function performs the validation work for complex object models.
     *
     * In addition to checking the current object, all related objects will
     * also be validated.  If all pass then <code>true</code> is returned; otherwise
     * an aggreagated array of ValidationFailed objects will be returned.
     *
     * @param array $columns Array of column names to validate.
     * @return mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
     */
    protected function doValidate($columns = null)
    {
        if (!$this->alreadyInValidation) {
            $this->alreadyInValidation = true;
            $retval = null;

            $failureMap = array();


            // We call the validate method on the following object(s) if they
            // were passed to this object by their coresponding set
            // method.  This object relates to these object(s) by a
            // foreign key reference.

            if ($this->aRequerimiento !== null) {
                if (!$this->aRequerimiento->validate($columns)) {
                    $failureMap = array_merge($failureMap, $this->aRequerimiento->getValidationFailures());
                }
            }

            if ($this->aPropiedad !== null) {
                if (!$this->aPropiedad->validate($columns)) {
                    $failureMap = array_merge($failureMap, $this->aPropiedad->getValidationFailures());
                }
            }

            if ($this->aUsuarioRelatedByUsuarioReq !== null) {
                if (!$this->aUsuarioRelatedByUsuarioReq->validate($columns)) {
                    $failureMap = array_merge($failureMap, $this->aUsuarioRelatedByUsuarioReq->getValidationFailures());
                }
            }

            if ($this->aUsuarioRelatedByUsuarioProp !== null) {
                if (!$this->aUsuarioRelatedByUsuarioProp->validate($columns)) {
                    $failureMap = array_merge($failureMap, $this->aUsuarioRelatedByUsuarioProp->getValidationFailures());
                }
            }


            if (($retval = NegocioPeer::doValidate($this, $columns)) !== true) {
                $failureMap = array_merge($failureMap, $retval);
            }


                if ($this->collMensajeNegocios !== null) {
                    foreach ($this->collMensajeNegocios as $referrerFK) {
                        if (!$referrerFK->validate($columns)) {
                            $failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
                        }
                    }
                }


            $this->alreadyInValidation = false;
        }

        return (!empty($failureMap) ? $failureMap : true);
    }

    /**
     * Retrieves a field from the object by name passed in as a string.
     *
     * @param string $name name
     * @param string $type The type of fieldname the $name is of:
     *               one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
     *               BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     *               Defaults to BasePeer::TYPE_PHPNAME
     * @return mixed Value of field.
     */
    public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
    {
        $pos = NegocioPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
        $field = $this->getByPosition($pos);

        return $field;
    }

    /**
     * Retrieves a field from the object by Position as specified in the xml schema.
     * Zero-based.
     *
     * @param int $pos position in xml schema
     * @return mixed Value of field at $pos
     */
    public function getByPosition($pos)
    {
        switch ($pos) {
            case 0:
                return $this->getId();
                break;
            case 1:
                return $this->getRequerimientoId();
                break;
            case 2:
                return $this->getPropiedadId();
                break;
            case 3:
                return $this->getUsuarioReq();
                break;
            case 4:
                return $this->getUsuarioProp();
                break;
            case 5:
                return $this->getActivo();
                break;
            default:
                return null;
                break;
        } // switch()
    }

    /**
     * Exports the object as an array.
     *
     * You can specify the key type of the array by passing one of the class
     * type constants.
     *
     * @param     string  $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
     *                    BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     *                    Defaults to BasePeer::TYPE_PHPNAME.
     * @param     boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns. Defaults to true.
     * @param     array $alreadyDumpedObjects List of objects to skip to avoid recursion
     * @param     boolean $includeForeignObjects (optional) Whether to include hydrated related objects. Default to FALSE.
     *
     * @return array an associative array containing the field names (as keys) and field values
     */
    public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true, $alreadyDumpedObjects = array(), $includeForeignObjects = false)
    {
        if (isset($alreadyDumpedObjects['Negocio'][$this->getPrimaryKey()])) {
            return '*RECURSION*';
        }
        $alreadyDumpedObjects['Negocio'][$this->getPrimaryKey()] = true;
        $keys = NegocioPeer::getFieldNames($keyType);
        $result = array(
            $keys[0] => $this->getId(),
            $keys[1] => $this->getRequerimientoId(),
            $keys[2] => $this->getPropiedadId(),
            $keys[3] => $this->getUsuarioReq(),
            $keys[4] => $this->getUsuarioProp(),
            $keys[5] => $this->getActivo(),
        );
        if ($includeForeignObjects) {
            if (null !== $this->aRequerimiento) {
                $result['Requerimiento'] = $this->aRequerimiento->toArray($keyType, $includeLazyLoadColumns,  $alreadyDumpedObjects, true);
            }
            if (null !== $this->aPropiedad) {
                $result['Propiedad'] = $this->aPropiedad->toArray($keyType, $includeLazyLoadColumns,  $alreadyDumpedObjects, true);
            }
            if (null !== $this->aUsuarioRelatedByUsuarioReq) {
                $result['UsuarioRelatedByUsuarioReq'] = $this->aUsuarioRelatedByUsuarioReq->toArray($keyType, $includeLazyLoadColumns,  $alreadyDumpedObjects, true);
            }
            if (null !== $this->aUsuarioRelatedByUsuarioProp) {
                $result['UsuarioRelatedByUsuarioProp'] = $this->aUsuarioRelatedByUsuarioProp->toArray($keyType, $includeLazyLoadColumns,  $alreadyDumpedObjects, true);
            }
            if (null !== $this->collMensajeNegocios) {
                $result['MensajeNegocios'] = $this->collMensajeNegocios->toArray(null, true, $keyType, $includeLazyLoadColumns, $alreadyDumpedObjects);
            }
        }

        return $result;
    }

    /**
     * Sets a field from the object by name passed in as a string.
     *
     * @param string $name peer name
     * @param mixed $value field value
     * @param string $type The type of fieldname the $name is of:
     *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
     *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     *                     Defaults to BasePeer::TYPE_PHPNAME
     * @return void
     */
    public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
    {
        $pos = NegocioPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);

        $this->setByPosition($pos, $value);
    }

    /**
     * Sets a field from the object by Position as specified in the xml schema.
     * Zero-based.
     *
     * @param int $pos position in xml schema
     * @param mixed $value field value
     * @return void
     */
    public function setByPosition($pos, $value)
    {
        switch ($pos) {
            case 0:
                $this->setId($value);
                break;
            case 1:
                $this->setRequerimientoId($value);
                break;
            case 2:
                $this->setPropiedadId($value);
                break;
            case 3:
                $this->setUsuarioReq($value);
                break;
            case 4:
                $this->setUsuarioProp($value);
                break;
            case 5:
                $this->setActivo($value);
                break;
        } // switch()
    }

    /**
     * Populates the object using an array.
     *
     * This is particularly useful when populating an object from one of the
     * request arrays (e.g. $_POST).  This method goes through the column
     * names, checking to see whether a matching key exists in populated
     * array. If so the setByName() method is called for that column.
     *
     * You can specify the key type of the array by additionally passing one
     * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
     * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     * The default key type is the column's BasePeer::TYPE_PHPNAME
     *
     * @param array  $arr     An array to populate the object from.
     * @param string $keyType The type of keys the array uses.
     * @return void
     */
    public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
    {
        $keys = NegocioPeer::getFieldNames($keyType);

        if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
        if (array_key_exists($keys[1], $arr)) $this->setRequerimientoId($arr[$keys[1]]);
        if (array_key_exists($keys[2], $arr)) $this->setPropiedadId($arr[$keys[2]]);
        if (array_key_exists($keys[3], $arr)) $this->setUsuarioReq($arr[$keys[3]]);
        if (array_key_exists($keys[4], $arr)) $this->setUsuarioProp($arr[$keys[4]]);
        if (array_key_exists($keys[5], $arr)) $this->setActivo($arr[$keys[5]]);
    }

    /**
     * Build a Criteria object containing the values of all modified columns in this object.
     *
     * @return Criteria The Criteria object containing all modified values.
     */
    public function buildCriteria()
    {
        $criteria = new Criteria(NegocioPeer::DATABASE_NAME);

        if ($this->isColumnModified(NegocioPeer::ID)) $criteria->add(NegocioPeer::ID, $this->id);
        if ($this->isColumnModified(NegocioPeer::REQUERIMIENTO_ID)) $criteria->add(NegocioPeer::REQUERIMIENTO_ID, $this->requerimiento_id);
        if ($this->isColumnModified(NegocioPeer::PROPIEDAD_ID)) $criteria->add(NegocioPeer::PROPIEDAD_ID, $this->propiedad_id);
        if ($this->isColumnModified(NegocioPeer::USUARIO_REQ)) $criteria->add(NegocioPeer::USUARIO_REQ, $this->usuario_req);
        if ($this->isColumnModified(NegocioPeer::USUARIO_PROP)) $criteria->add(NegocioPeer::USUARIO_PROP, $this->usuario_prop);
        if ($this->isColumnModified(NegocioPeer::ACTIVO)) $criteria->add(NegocioPeer::ACTIVO, $this->activo);

        return $criteria;
    }

    /**
     * Builds a Criteria object containing the primary key for this object.
     *
     * Unlike buildCriteria() this method includes the primary key values regardless
     * of whether or not they have been modified.
     *
     * @return Criteria The Criteria object containing value(s) for primary key(s).
     */
    public function buildPkeyCriteria()
    {
        $criteria = new Criteria(NegocioPeer::DATABASE_NAME);
        $criteria->add(NegocioPeer::ID, $this->id);

        return $criteria;
    }

    /**
     * Returns the primary key for this object (row).
     * @return int
     */
    public function getPrimaryKey()
    {
        return $this->getId();
    }

    /**
     * Generic method to set the primary key (id column).
     *
     * @param  int $key Primary key.
     * @return void
     */
    public function setPrimaryKey($key)
    {
        $this->setId($key);
    }

    /**
     * Returns true if the primary key for this object is null.
     * @return boolean
     */
    public function isPrimaryKeyNull()
    {

        return null === $this->getId();
    }

    /**
     * Sets contents of passed object to values from current object.
     *
     * If desired, this method can also make copies of all associated (fkey referrers)
     * objects.
     *
     * @param object $copyObj An object of Negocio (or compatible) type.
     * @param boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
     * @param boolean $makeNew Whether to reset autoincrement PKs and make the object new.
     * @throws PropelException
     */
    public function copyInto($copyObj, $deepCopy = false, $makeNew = true)
    {
        $copyObj->setRequerimientoId($this->getRequerimientoId());
        $copyObj->setPropiedadId($this->getPropiedadId());
        $copyObj->setUsuarioReq($this->getUsuarioReq());
        $copyObj->setUsuarioProp($this->getUsuarioProp());
        $copyObj->setActivo($this->getActivo());

        if ($deepCopy && !$this->startCopy) {
            // important: temporarily setNew(false) because this affects the behavior of
            // the getter/setter methods for fkey referrer objects.
            $copyObj->setNew(false);
            // store object hash to prevent cycle
            $this->startCopy = true;

            foreach ($this->getMensajeNegocios() as $relObj) {
                if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
                    $copyObj->addMensajeNegocio($relObj->copy($deepCopy));
                }
            }

            //unflag object copy
            $this->startCopy = false;
        } // if ($deepCopy)

        if ($makeNew) {
            $copyObj->setNew(true);
            $copyObj->setId(NULL); // this is a auto-increment column, so set to default value
        }
    }

    /**
     * Makes a copy of this object that will be inserted as a new row in table when saved.
     * It creates a new object filling in the simple attributes, but skipping any primary
     * keys that are defined for the table.
     *
     * If desired, this method can also make copies of all associated (fkey referrers)
     * objects.
     *
     * @param boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
     * @return Negocio Clone of current object.
     * @throws PropelException
     */
    public function copy($deepCopy = false)
    {
        // we use get_class(), because this might be a subclass
        $clazz = get_class($this);
        $copyObj = new $clazz();
        $this->copyInto($copyObj, $deepCopy);

        return $copyObj;
    }

    /**
     * Returns a peer instance associated with this om.
     *
     * Since Peer classes are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     *
     * @return NegocioPeer
     */
    public function getPeer()
    {
        if (self::$peer === null) {
            self::$peer = new NegocioPeer();
        }

        return self::$peer;
    }

    /**
     * Declares an association between this object and a Requerimiento object.
     *
     * @param             Requerimiento $v
     * @return Negocio The current object (for fluent API support)
     * @throws PropelException
     */
    public function setRequerimiento(Requerimiento $v = null)
    {
        if ($v === null) {
            $this->setRequerimientoId(NULL);
        } else {
            $this->setRequerimientoId($v->getId());
        }

        $this->aRequerimiento = $v;

        // Add binding for other direction of this n:n relationship.
        // If this object has already been added to the Requerimiento object, it will not be re-added.
        if ($v !== null) {
            $v->addNegocio($this);
        }


        return $this;
    }


    /**
     * Get the associated Requerimiento object
     *
     * @param PropelPDO $con Optional Connection object.
     * @return Requerimiento The associated Requerimiento object.
     * @throws PropelException
     */
    public function getRequerimiento(PropelPDO $con = null)
    {
        if ($this->aRequerimiento === null && ($this->requerimiento_id !== null)) {
            $this->aRequerimiento = RequerimientoQuery::create()->findPk($this->requerimiento_id, $con);
            /* The following can be used additionally to
                guarantee the related object contains a reference
                to this object.  This level of coupling may, however, be
                undesirable since it could result in an only partially populated collection
                in the referenced object.
                $this->aRequerimiento->addNegocios($this);
             */
        }

        return $this->aRequerimiento;
    }

    /**
     * Declares an association between this object and a Propiedad object.
     *
     * @param             Propiedad $v
     * @return Negocio The current object (for fluent API support)
     * @throws PropelException
     */
    public function setPropiedad(Propiedad $v = null)
    {
        if ($v === null) {
            $this->setPropiedadId(NULL);
        } else {
            $this->setPropiedadId($v->getId());
        }

        $this->aPropiedad = $v;

        // Add binding for other direction of this n:n relationship.
        // If this object has already been added to the Propiedad object, it will not be re-added.
        if ($v !== null) {
            $v->addNegocio($this);
        }


        return $this;
    }


    /**
     * Get the associated Propiedad object
     *
     * @param PropelPDO $con Optional Connection object.
     * @return Propiedad The associated Propiedad object.
     * @throws PropelException
     */
    public function getPropiedad(PropelPDO $con = null)
    {
        if ($this->aPropiedad === null && ($this->propiedad_id !== null)) {
            $this->aPropiedad = PropiedadQuery::create()->findPk($this->propiedad_id, $con);
            /* The following can be used additionally to
                guarantee the related object contains a reference
                to this object.  This level of coupling may, however, be
                undesirable since it could result in an only partially populated collection
                in the referenced object.
                $this->aPropiedad->addNegocios($this);
             */
        }

        return $this->aPropiedad;
    }

    /**
     * Declares an association between this object and a Usuario object.
     *
     * @param             Usuario $v
     * @return Negocio The current object (for fluent API support)
     * @throws PropelException
     */
    public function setUsuarioRelatedByUsuarioReq(Usuario $v = null)
    {
        if ($v === null) {
            $this->setUsuarioReq(NULL);
        } else {
            $this->setUsuarioReq($v->getId());
        }

        $this->aUsuarioRelatedByUsuarioReq = $v;

        // Add binding for other direction of this n:n relationship.
        // If this object has already been added to the Usuario object, it will not be re-added.
        if ($v !== null) {
            $v->addNegocioRelatedByUsuarioReq($this);
        }


        return $this;
    }


    /**
     * Get the associated Usuario object
     *
     * @param PropelPDO $con Optional Connection object.
     * @return Usuario The associated Usuario object.
     * @throws PropelException
     */
    public function getUsuarioRelatedByUsuarioReq(PropelPDO $con = null)
    {
        if ($this->aUsuarioRelatedByUsuarioReq === null && ($this->usuario_req !== null)) {
            $this->aUsuarioRelatedByUsuarioReq = UsuarioQuery::create()->findPk($this->usuario_req, $con);
            /* The following can be used additionally to
                guarantee the related object contains a reference
                to this object.  This level of coupling may, however, be
                undesirable since it could result in an only partially populated collection
                in the referenced object.
                $this->aUsuarioRelatedByUsuarioReq->addNegociosRelatedByUsuarioReq($this);
             */
        }

        return $this->aUsuarioRelatedByUsuarioReq;
    }

    /**
     * Declares an association between this object and a Usuario object.
     *
     * @param             Usuario $v
     * @return Negocio The current object (for fluent API support)
     * @throws PropelException
     */
    public function setUsuarioRelatedByUsuarioProp(Usuario $v = null)
    {
        if ($v === null) {
            $this->setUsuarioProp(NULL);
        } else {
            $this->setUsuarioProp($v->getId());
        }

        $this->aUsuarioRelatedByUsuarioProp = $v;

        // Add binding for other direction of this n:n relationship.
        // If this object has already been added to the Usuario object, it will not be re-added.
        if ($v !== null) {
            $v->addNegocioRelatedByUsuarioProp($this);
        }


        return $this;
    }


    /**
     * Get the associated Usuario object
     *
     * @param PropelPDO $con Optional Connection object.
     * @return Usuario The associated Usuario object.
     * @throws PropelException
     */
    public function getUsuarioRelatedByUsuarioProp(PropelPDO $con = null)
    {
        if ($this->aUsuarioRelatedByUsuarioProp === null && ($this->usuario_prop !== null)) {
            $this->aUsuarioRelatedByUsuarioProp = UsuarioQuery::create()->findPk($this->usuario_prop, $con);
            /* The following can be used additionally to
                guarantee the related object contains a reference
                to this object.  This level of coupling may, however, be
                undesirable since it could result in an only partially populated collection
                in the referenced object.
                $this->aUsuarioRelatedByUsuarioProp->addNegociosRelatedByUsuarioProp($this);
             */
        }

        return $this->aUsuarioRelatedByUsuarioProp;
    }


    /**
     * Initializes a collection based on the name of a relation.
     * Avoids crafting an 'init[$relationName]s' method name
     * that wouldn't work when StandardEnglishPluralizer is used.
     *
     * @param string $relationName The name of the relation to initialize
     * @return void
     */
    public function initRelation($relationName)
    {
        if ('MensajeNegocio' == $relationName) {
            $this->initMensajeNegocios();
        }
    }

    /**
     * Clears out the collMensajeNegocios collection
     *
     * This does not modify the database; however, it will remove any associated objects, causing
     * them to be refetched by subsequent calls to accessor method.
     *
     * @return void
     * @see        addMensajeNegocios()
     */
    public function clearMensajeNegocios()
    {
        $this->collMensajeNegocios = null; // important to set this to null since that means it is uninitialized
        $this->collMensajeNegociosPartial = null;
    }

    /**
     * reset is the collMensajeNegocios collection loaded partially
     *
     * @return void
     */
    public function resetPartialMensajeNegocios($v = true)
    {
        $this->collMensajeNegociosPartial = $v;
    }

    /**
     * Initializes the collMensajeNegocios collection.
     *
     * By default this just sets the collMensajeNegocios collection to an empty array (like clearcollMensajeNegocios());
     * however, you may wish to override this method in your stub class to provide setting appropriate
     * to your application -- for example, setting the initial array to the values stored in database.
     *
     * @param boolean $overrideExisting If set to true, the method call initializes
     *                                        the collection even if it is not empty
     *
     * @return void
     */
    public function initMensajeNegocios($overrideExisting = true)
    {
        if (null !== $this->collMensajeNegocios && !$overrideExisting) {
            return;
        }
        $this->collMensajeNegocios = new PropelObjectCollection();
        $this->collMensajeNegocios->setModel('MensajeNegocio');
    }

    /**
     * Gets an array of MensajeNegocio objects which contain a foreign key that references this object.
     *
     * If the $criteria is not null, it is used to always fetch the results from the database.
     * Otherwise the results are fetched from the database the first time, then cached.
     * Next time the same method is called without $criteria, the cached collection is returned.
     * If this Negocio is new, it will return
     * an empty collection or the current collection; the criteria is ignored on a new object.
     *
     * @param Criteria $criteria optional Criteria object to narrow the query
     * @param PropelPDO $con optional connection object
     * @return PropelObjectCollection|MensajeNegocio[] List of MensajeNegocio objects
     * @throws PropelException
     */
    public function getMensajeNegocios($criteria = null, PropelPDO $con = null)
    {
        $partial = $this->collMensajeNegociosPartial && !$this->isNew();
        if (null === $this->collMensajeNegocios || null !== $criteria  || $partial) {
            if ($this->isNew() && null === $this->collMensajeNegocios) {
                // return empty collection
                $this->initMensajeNegocios();
            } else {
                $collMensajeNegocios = MensajeNegocioQuery::create(null, $criteria)
                    ->filterByNegocio($this)
                    ->find($con);
                if (null !== $criteria) {
                    if (false !== $this->collMensajeNegociosPartial && count($collMensajeNegocios)) {
                      $this->initMensajeNegocios(false);

                      foreach($collMensajeNegocios as $obj) {
                        if (false == $this->collMensajeNegocios->contains($obj)) {
                          $this->collMensajeNegocios->append($obj);
                        }
                      }

                      $this->collMensajeNegociosPartial = true;
                    }

                    return $collMensajeNegocios;
                }

                if($partial && $this->collMensajeNegocios) {
                    foreach($this->collMensajeNegocios as $obj) {
                        if($obj->isNew()) {
                            $collMensajeNegocios[] = $obj;
                        }
                    }
                }

                $this->collMensajeNegocios = $collMensajeNegocios;
                $this->collMensajeNegociosPartial = false;
            }
        }

        return $this->collMensajeNegocios;
    }

    /**
     * Sets a collection of MensajeNegocio objects related by a one-to-many relationship
     * to the current object.
     * It will also schedule objects for deletion based on a diff between old objects (aka persisted)
     * and new objects from the given Propel collection.
     *
     * @param PropelCollection $mensajeNegocios A Propel collection.
     * @param PropelPDO $con Optional connection object
     */
    public function setMensajeNegocios(PropelCollection $mensajeNegocios, PropelPDO $con = null)
    {
        $this->mensajeNegociosScheduledForDeletion = $this->getMensajeNegocios(new Criteria(), $con)->diff($mensajeNegocios);

        foreach ($this->mensajeNegociosScheduledForDeletion as $mensajeNegocioRemoved) {
            $mensajeNegocioRemoved->setNegocio(null);
        }

        $this->collMensajeNegocios = null;
        foreach ($mensajeNegocios as $mensajeNegocio) {
            $this->addMensajeNegocio($mensajeNegocio);
        }

        $this->collMensajeNegocios = $mensajeNegocios;
        $this->collMensajeNegociosPartial = false;
    }

    /**
     * Returns the number of related MensajeNegocio objects.
     *
     * @param Criteria $criteria
     * @param boolean $distinct
     * @param PropelPDO $con
     * @return int             Count of related MensajeNegocio objects.
     * @throws PropelException
     */
    public function countMensajeNegocios(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
    {
        $partial = $this->collMensajeNegociosPartial && !$this->isNew();
        if (null === $this->collMensajeNegocios || null !== $criteria || $partial) {
            if ($this->isNew() && null === $this->collMensajeNegocios) {
                return 0;
            } else {
                if($partial && !$criteria) {
                    return count($this->getMensajeNegocios());
                }
                $query = MensajeNegocioQuery::create(null, $criteria);
                if ($distinct) {
                    $query->distinct();
                }

                return $query
                    ->filterByNegocio($this)
                    ->count($con);
            }
        } else {
            return count($this->collMensajeNegocios);
        }
    }

    /**
     * Method called to associate a MensajeNegocio object to this object
     * through the MensajeNegocio foreign key attribute.
     *
     * @param    MensajeNegocio $l MensajeNegocio
     * @return Negocio The current object (for fluent API support)
     */
    public function addMensajeNegocio(MensajeNegocio $l)
    {
        if ($this->collMensajeNegocios === null) {
            $this->initMensajeNegocios();
            $this->collMensajeNegociosPartial = true;
        }
        if (!$this->collMensajeNegocios->contains($l)) { // only add it if the **same** object is not already associated
            $this->doAddMensajeNegocio($l);
        }

        return $this;
    }

    /**
     * @param	MensajeNegocio $mensajeNegocio The mensajeNegocio object to add.
     */
    protected function doAddMensajeNegocio($mensajeNegocio)
    {
        $this->collMensajeNegocios[]= $mensajeNegocio;
        $mensajeNegocio->setNegocio($this);
    }

    /**
     * @param	MensajeNegocio $mensajeNegocio The mensajeNegocio object to remove.
     */
    public function removeMensajeNegocio($mensajeNegocio)
    {
        if ($this->getMensajeNegocios()->contains($mensajeNegocio)) {
            $this->collMensajeNegocios->remove($this->collMensajeNegocios->search($mensajeNegocio));
            if (null === $this->mensajeNegociosScheduledForDeletion) {
                $this->mensajeNegociosScheduledForDeletion = clone $this->collMensajeNegocios;
                $this->mensajeNegociosScheduledForDeletion->clear();
            }
            $this->mensajeNegociosScheduledForDeletion[]= $mensajeNegocio;
            $mensajeNegocio->setNegocio(null);
        }
    }


    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Negocio is new, it will return
     * an empty collection; or if this Negocio has previously
     * been saved, it will retrieve related MensajeNegocios from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Negocio.
     *
     * @param Criteria $criteria optional Criteria object to narrow the query
     * @param PropelPDO $con optional connection object
     * @param string $join_behavior optional join type to use (defaults to Criteria::LEFT_JOIN)
     * @return PropelObjectCollection|MensajeNegocio[] List of MensajeNegocio objects
     */
    public function getMensajeNegociosJoinUsuario($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        $query = MensajeNegocioQuery::create(null, $criteria);
        $query->joinWith('Usuario', $join_behavior);

        return $this->getMensajeNegocios($query, $con);
    }

    /**
     * Clears the current object and sets all attributes to their default values
     */
    public function clear()
    {
        $this->id = null;
        $this->requerimiento_id = null;
        $this->propiedad_id = null;
        $this->usuario_req = null;
        $this->usuario_prop = null;
        $this->activo = null;
        $this->alreadyInSave = false;
        $this->alreadyInValidation = false;
        $this->clearAllReferences();
        $this->applyDefaultValues();
        $this->resetModified();
        $this->setNew(true);
        $this->setDeleted(false);
    }

    /**
     * Resets all references to other model objects or collections of model objects.
     *
     * This method is a user-space workaround for PHP's inability to garbage collect
     * objects with circular references (even in PHP 5.3). This is currently necessary
     * when using Propel in certain daemon or large-volumne/high-memory operations.
     *
     * @param boolean $deep Whether to also clear the references on all referrer objects.
     */
    public function clearAllReferences($deep = false)
    {
        if ($deep) {
            if ($this->collMensajeNegocios) {
                foreach ($this->collMensajeNegocios as $o) {
                    $o->clearAllReferences($deep);
                }
            }
        } // if ($deep)

        if ($this->collMensajeNegocios instanceof PropelCollection) {
            $this->collMensajeNegocios->clearIterator();
        }
        $this->collMensajeNegocios = null;
        $this->aRequerimiento = null;
        $this->aPropiedad = null;
        $this->aUsuarioRelatedByUsuarioReq = null;
        $this->aUsuarioRelatedByUsuarioProp = null;
    }

    /**
     * return the string representation of this object
     *
     * @return string
     */
    public function __toString()
    {
        return (string) $this->exportTo(NegocioPeer::DEFAULT_STRING_FORMAT);
    }

    /**
     * return true is the object is in saving state
     *
     * @return boolean
     */
    public function isAlreadyInSave()
    {
        return $this->alreadyInSave;
    }

    /**
     * Catches calls to virtual methods
     */
    public function __call($name, $params)
    {

        // symfony_behaviors behavior
        if ($callable = sfMixer::getCallable('BaseNegocio:' . $name))
        {
          array_unshift($params, $this);
          return call_user_func_array($callable, $params);
        }


        return parent::__call($name, $params);
    }

}
