<?php


/**
 * Base class that represents a query for the 'mensaje_negocio' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Sun Mar 18 14:41:29 2018
 *
 * @method MensajeNegocioQuery orderById($order = Criteria::ASC) Order by the id column
 * @method MensajeNegocioQuery orderByNegocioId($order = Criteria::ASC) Order by the negocio_id column
 * @method MensajeNegocioQuery orderByUsuarioId($order = Criteria::ASC) Order by the usuario_id column
 * @method MensajeNegocioQuery orderByMensaje($order = Criteria::ASC) Order by the mensaje column
 * @method MensajeNegocioQuery orderByCreatedAt($order = Criteria::ASC) Order by the created_at column
 * @method MensajeNegocioQuery orderByUpdatedAt($order = Criteria::ASC) Order by the updated_at column
 * @method MensajeNegocioQuery orderByVisto($order = Criteria::ASC) Order by the visto column
 *
 * @method MensajeNegocioQuery groupById() Group by the id column
 * @method MensajeNegocioQuery groupByNegocioId() Group by the negocio_id column
 * @method MensajeNegocioQuery groupByUsuarioId() Group by the usuario_id column
 * @method MensajeNegocioQuery groupByMensaje() Group by the mensaje column
 * @method MensajeNegocioQuery groupByCreatedAt() Group by the created_at column
 * @method MensajeNegocioQuery groupByUpdatedAt() Group by the updated_at column
 * @method MensajeNegocioQuery groupByVisto() Group by the visto column
 *
 * @method MensajeNegocioQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method MensajeNegocioQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method MensajeNegocioQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method MensajeNegocioQuery leftJoinNegocio($relationAlias = null) Adds a LEFT JOIN clause to the query using the Negocio relation
 * @method MensajeNegocioQuery rightJoinNegocio($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Negocio relation
 * @method MensajeNegocioQuery innerJoinNegocio($relationAlias = null) Adds a INNER JOIN clause to the query using the Negocio relation
 *
 * @method MensajeNegocioQuery leftJoinUsuario($relationAlias = null) Adds a LEFT JOIN clause to the query using the Usuario relation
 * @method MensajeNegocioQuery rightJoinUsuario($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Usuario relation
 * @method MensajeNegocioQuery innerJoinUsuario($relationAlias = null) Adds a INNER JOIN clause to the query using the Usuario relation
 *
 * @method MensajeNegocio findOne(PropelPDO $con = null) Return the first MensajeNegocio matching the query
 * @method MensajeNegocio findOneOrCreate(PropelPDO $con = null) Return the first MensajeNegocio matching the query, or a new MensajeNegocio object populated from the query conditions when no match is found
 *
 * @method MensajeNegocio findOneById(int $id) Return the first MensajeNegocio filtered by the id column
 * @method MensajeNegocio findOneByNegocioId(int $negocio_id) Return the first MensajeNegocio filtered by the negocio_id column
 * @method MensajeNegocio findOneByUsuarioId(int $usuario_id) Return the first MensajeNegocio filtered by the usuario_id column
 * @method MensajeNegocio findOneByMensaje(string $mensaje) Return the first MensajeNegocio filtered by the mensaje column
 * @method MensajeNegocio findOneByCreatedAt(string $created_at) Return the first MensajeNegocio filtered by the created_at column
 * @method MensajeNegocio findOneByUpdatedAt(string $updated_at) Return the first MensajeNegocio filtered by the updated_at column
 * @method MensajeNegocio findOneByVisto(boolean $visto) Return the first MensajeNegocio filtered by the visto column
 *
 * @method array findById(int $id) Return MensajeNegocio objects filtered by the id column
 * @method array findByNegocioId(int $negocio_id) Return MensajeNegocio objects filtered by the negocio_id column
 * @method array findByUsuarioId(int $usuario_id) Return MensajeNegocio objects filtered by the usuario_id column
 * @method array findByMensaje(string $mensaje) Return MensajeNegocio objects filtered by the mensaje column
 * @method array findByCreatedAt(string $created_at) Return MensajeNegocio objects filtered by the created_at column
 * @method array findByUpdatedAt(string $updated_at) Return MensajeNegocio objects filtered by the updated_at column
 * @method array findByVisto(boolean $visto) Return MensajeNegocio objects filtered by the visto column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseMensajeNegocioQuery extends ModelCriteria
{
    /**
     * Initializes internal state of BaseMensajeNegocioQuery object.
     *
     * @param     string $dbName The dabase name
     * @param     string $modelName The phpName of a model, e.g. 'Book'
     * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct($dbName = 'propel', $modelName = 'MensajeNegocio', $modelAlias = null)
    {
        parent::__construct($dbName, $modelName, $modelAlias);
    }

    /**
     * Returns a new MensajeNegocioQuery object.
     *
     * @param     string $modelAlias The alias of a model in the query
     * @param     MensajeNegocioQuery|Criteria $criteria Optional Criteria to build the query from
     *
     * @return MensajeNegocioQuery
     */
    public static function create($modelAlias = null, $criteria = null)
    {
        if ($criteria instanceof MensajeNegocioQuery) {
            return $criteria;
        }
        $query = new MensajeNegocioQuery();
        if (null !== $modelAlias) {
            $query->setModelAlias($modelAlias);
        }
        if ($criteria instanceof Criteria) {
            $query->mergeWith($criteria);
        }

        return $query;
    }

    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * <code>
     * $obj  = $c->findPk(12, $con);
     * </code>
     *
     * @param mixed $key Primary key to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return   MensajeNegocio|MensajeNegocio[]|mixed the result, formatted by the current formatter
     */
    public function findPk($key, $con = null)
    {
        if ($key === null) {
            return null;
        }
        if ((null !== ($obj = MensajeNegocioPeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
            // the object is alredy in the instance pool
            return $obj;
        }
        if ($con === null) {
            $con = Propel::getConnection(MensajeNegocioPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        if ($this->formatter || $this->modelAlias || $this->with || $this->select
         || $this->selectColumns || $this->asColumns || $this->selectModifiers
         || $this->map || $this->having || $this->joins) {
            return $this->findPkComplex($key, $con);
        } else {
            return $this->findPkSimple($key, $con);
        }
    }

    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return   MensajeNegocio A model object, or null if the key is not found
     * @throws   PropelException
     */
    protected function findPkSimple($key, $con)
    {
        $sql = 'SELECT `ID`, `NEGOCIO_ID`, `USUARIO_ID`, `MENSAJE`, `CREATED_AT`, `UPDATED_AT`, `VISTO` FROM `mensaje_negocio` WHERE `ID` = :p0';
        try {
            $stmt = $con->prepare($sql);
            $stmt->bindValue(':p0', $key, PDO::PARAM_INT);
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
        }
        $obj = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $obj = new MensajeNegocio();
            $obj->hydrate($row);
            MensajeNegocioPeer::addInstanceToPool($obj, (string) $key);
        }
        $stmt->closeCursor();

        return $obj;
    }

    /**
     * Find object by primary key.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return MensajeNegocio|MensajeNegocio[]|mixed the result, formatted by the current formatter
     */
    protected function findPkComplex($key, $con)
    {
        // As the query uses a PK condition, no limit(1) is necessary.
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKey($key)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }

    /**
     * Find objects by primary key
     * <code>
     * $objs = $c->findPks(array(12, 56, 832), $con);
     * </code>
     * @param     array $keys Primary keys to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return PropelObjectCollection|MensajeNegocio[]|mixed the list of results, formatted by the current formatter
     */
    public function findPks($keys, $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKeys($keys)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->format($stmt);
    }

    /**
     * Filter the query by primary key
     *
     * @param     mixed $key Primary key to use for the query
     *
     * @return MensajeNegocioQuery The current query, for fluid interface
     */
    public function filterByPrimaryKey($key)
    {

        return $this->addUsingAlias(MensajeNegocioPeer::ID, $key, Criteria::EQUAL);
    }

    /**
     * Filter the query by a list of primary keys
     *
     * @param     array $keys The list of primary key to use for the query
     *
     * @return MensajeNegocioQuery The current query, for fluid interface
     */
    public function filterByPrimaryKeys($keys)
    {

        return $this->addUsingAlias(MensajeNegocioPeer::ID, $keys, Criteria::IN);
    }

    /**
     * Filter the query on the id column
     *
     * Example usage:
     * <code>
     * $query->filterById(1234); // WHERE id = 1234
     * $query->filterById(array(12, 34)); // WHERE id IN (12, 34)
     * $query->filterById(array('min' => 12)); // WHERE id > 12
     * </code>
     *
     * @param     mixed $id The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return MensajeNegocioQuery The current query, for fluid interface
     */
    public function filterById($id = null, $comparison = null)
    {
        if (is_array($id) && null === $comparison) {
            $comparison = Criteria::IN;
        }

        return $this->addUsingAlias(MensajeNegocioPeer::ID, $id, $comparison);
    }

    /**
     * Filter the query on the negocio_id column
     *
     * Example usage:
     * <code>
     * $query->filterByNegocioId(1234); // WHERE negocio_id = 1234
     * $query->filterByNegocioId(array(12, 34)); // WHERE negocio_id IN (12, 34)
     * $query->filterByNegocioId(array('min' => 12)); // WHERE negocio_id > 12
     * </code>
     *
     * @see       filterByNegocio()
     *
     * @param     mixed $negocioId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return MensajeNegocioQuery The current query, for fluid interface
     */
    public function filterByNegocioId($negocioId = null, $comparison = null)
    {
        if (is_array($negocioId)) {
            $useMinMax = false;
            if (isset($negocioId['min'])) {
                $this->addUsingAlias(MensajeNegocioPeer::NEGOCIO_ID, $negocioId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($negocioId['max'])) {
                $this->addUsingAlias(MensajeNegocioPeer::NEGOCIO_ID, $negocioId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(MensajeNegocioPeer::NEGOCIO_ID, $negocioId, $comparison);
    }

    /**
     * Filter the query on the usuario_id column
     *
     * Example usage:
     * <code>
     * $query->filterByUsuarioId(1234); // WHERE usuario_id = 1234
     * $query->filterByUsuarioId(array(12, 34)); // WHERE usuario_id IN (12, 34)
     * $query->filterByUsuarioId(array('min' => 12)); // WHERE usuario_id > 12
     * </code>
     *
     * @see       filterByUsuario()
     *
     * @param     mixed $usuarioId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return MensajeNegocioQuery The current query, for fluid interface
     */
    public function filterByUsuarioId($usuarioId = null, $comparison = null)
    {
        if (is_array($usuarioId)) {
            $useMinMax = false;
            if (isset($usuarioId['min'])) {
                $this->addUsingAlias(MensajeNegocioPeer::USUARIO_ID, $usuarioId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($usuarioId['max'])) {
                $this->addUsingAlias(MensajeNegocioPeer::USUARIO_ID, $usuarioId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(MensajeNegocioPeer::USUARIO_ID, $usuarioId, $comparison);
    }

    /**
     * Filter the query on the mensaje column
     *
     * Example usage:
     * <code>
     * $query->filterByMensaje('fooValue');   // WHERE mensaje = 'fooValue'
     * $query->filterByMensaje('%fooValue%'); // WHERE mensaje LIKE '%fooValue%'
     * </code>
     *
     * @param     string $mensaje The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return MensajeNegocioQuery The current query, for fluid interface
     */
    public function filterByMensaje($mensaje = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($mensaje)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $mensaje)) {
                $mensaje = str_replace('*', '%', $mensaje);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(MensajeNegocioPeer::MENSAJE, $mensaje, $comparison);
    }

    /**
     * Filter the query on the created_at column
     *
     * Example usage:
     * <code>
     * $query->filterByCreatedAt('2011-03-14'); // WHERE created_at = '2011-03-14'
     * $query->filterByCreatedAt('now'); // WHERE created_at = '2011-03-14'
     * $query->filterByCreatedAt(array('max' => 'yesterday')); // WHERE created_at > '2011-03-13'
     * </code>
     *
     * @param     mixed $createdAt The value to use as filter.
     *              Values can be integers (unix timestamps), DateTime objects, or strings.
     *              Empty strings are treated as NULL.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return MensajeNegocioQuery The current query, for fluid interface
     */
    public function filterByCreatedAt($createdAt = null, $comparison = null)
    {
        if (is_array($createdAt)) {
            $useMinMax = false;
            if (isset($createdAt['min'])) {
                $this->addUsingAlias(MensajeNegocioPeer::CREATED_AT, $createdAt['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($createdAt['max'])) {
                $this->addUsingAlias(MensajeNegocioPeer::CREATED_AT, $createdAt['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(MensajeNegocioPeer::CREATED_AT, $createdAt, $comparison);
    }

    /**
     * Filter the query on the updated_at column
     *
     * Example usage:
     * <code>
     * $query->filterByUpdatedAt('2011-03-14'); // WHERE updated_at = '2011-03-14'
     * $query->filterByUpdatedAt('now'); // WHERE updated_at = '2011-03-14'
     * $query->filterByUpdatedAt(array('max' => 'yesterday')); // WHERE updated_at > '2011-03-13'
     * </code>
     *
     * @param     mixed $updatedAt The value to use as filter.
     *              Values can be integers (unix timestamps), DateTime objects, or strings.
     *              Empty strings are treated as NULL.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return MensajeNegocioQuery The current query, for fluid interface
     */
    public function filterByUpdatedAt($updatedAt = null, $comparison = null)
    {
        if (is_array($updatedAt)) {
            $useMinMax = false;
            if (isset($updatedAt['min'])) {
                $this->addUsingAlias(MensajeNegocioPeer::UPDATED_AT, $updatedAt['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($updatedAt['max'])) {
                $this->addUsingAlias(MensajeNegocioPeer::UPDATED_AT, $updatedAt['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(MensajeNegocioPeer::UPDATED_AT, $updatedAt, $comparison);
    }

    /**
     * Filter the query on the visto column
     *
     * Example usage:
     * <code>
     * $query->filterByVisto(true); // WHERE visto = true
     * $query->filterByVisto('yes'); // WHERE visto = true
     * </code>
     *
     * @param     boolean|string $visto The value to use as filter.
     *              Non-boolean arguments are converted using the following rules:
     *                * 1, '1', 'true',  'on',  and 'yes' are converted to boolean true
     *                * 0, '0', 'false', 'off', and 'no'  are converted to boolean false
     *              Check on string values is case insensitive (so 'FaLsE' is seen as 'false').
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return MensajeNegocioQuery The current query, for fluid interface
     */
    public function filterByVisto($visto = null, $comparison = null)
    {
        if (is_string($visto)) {
            $visto = in_array(strtolower($visto), array('false', 'off', '-', 'no', 'n', '0', '')) ? false : true;
        }

        return $this->addUsingAlias(MensajeNegocioPeer::VISTO, $visto, $comparison);
    }

    /**
     * Filter the query by a related Negocio object
     *
     * @param   Negocio|PropelObjectCollection $negocio The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   MensajeNegocioQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterByNegocio($negocio, $comparison = null)
    {
        if ($negocio instanceof Negocio) {
            return $this
                ->addUsingAlias(MensajeNegocioPeer::NEGOCIO_ID, $negocio->getId(), $comparison);
        } elseif ($negocio instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(MensajeNegocioPeer::NEGOCIO_ID, $negocio->toKeyValue('PrimaryKey', 'Id'), $comparison);
        } else {
            throw new PropelException('filterByNegocio() only accepts arguments of type Negocio or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the Negocio relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return MensajeNegocioQuery The current query, for fluid interface
     */
    public function joinNegocio($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('Negocio');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'Negocio');
        }

        return $this;
    }

    /**
     * Use the Negocio relation Negocio object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   NegocioQuery A secondary query class using the current class as primary query
     */
    public function useNegocioQuery($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        return $this
            ->joinNegocio($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'Negocio', 'NegocioQuery');
    }

    /**
     * Filter the query by a related Usuario object
     *
     * @param   Usuario|PropelObjectCollection $usuario The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   MensajeNegocioQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterByUsuario($usuario, $comparison = null)
    {
        if ($usuario instanceof Usuario) {
            return $this
                ->addUsingAlias(MensajeNegocioPeer::USUARIO_ID, $usuario->getId(), $comparison);
        } elseif ($usuario instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(MensajeNegocioPeer::USUARIO_ID, $usuario->toKeyValue('PrimaryKey', 'Id'), $comparison);
        } else {
            throw new PropelException('filterByUsuario() only accepts arguments of type Usuario or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the Usuario relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return MensajeNegocioQuery The current query, for fluid interface
     */
    public function joinUsuario($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('Usuario');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'Usuario');
        }

        return $this;
    }

    /**
     * Use the Usuario relation Usuario object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   UsuarioQuery A secondary query class using the current class as primary query
     */
    public function useUsuarioQuery($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        return $this
            ->joinUsuario($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'Usuario', 'UsuarioQuery');
    }

    /**
     * Exclude object from result
     *
     * @param   MensajeNegocio $mensajeNegocio Object to remove from the list of results
     *
     * @return MensajeNegocioQuery The current query, for fluid interface
     */
    public function prune($mensajeNegocio = null)
    {
        if ($mensajeNegocio) {
            $this->addUsingAlias(MensajeNegocioPeer::ID, $mensajeNegocio->getId(), Criteria::NOT_EQUAL);
        }

        return $this;
    }

}
