
<div class="panel" id="direccion_<?php echo $num; ?>">
    <div class="panel-content">
        <div class="row">
            <div style="float:left;">
                <h4><b>Ubicación <?php echo $num ?></b></h4>
            </div>
            <div style="float:right;">
                <a class="btn btn-default btn-rounded" href="#/" onclick="menos_direccion(<?php echo $num ?>);">
                    <i class="fa fa-minus"></i>
                </a>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                <h5>Departamento</h5>
                <div style="text-align: center">
                    <select class="form-control col-md-12" name="nuevo_requerimiento[departamento_<?php echo $num; ?>]" id="nuevo_requerimiento_departamento_<?php echo $num; ?>">
                        <option value="1">Alta Verapaz</option>
                        <option value="2">Baja Verapaz</option>
                        <option value="3">Chimaltenango</option>
                        <option value="4">Chiquimula</option>
                        <option value="5">El Progreso</option>
                        <option value="6">Escuintla</option>
                        <option value="7">Guatemala</option>
                        <option value="8">Huehuetenango</option>
                        <option value="9">Izabal</option>
                        <option value="10">Jutiapa</option>
                        <option value="11">Petén</option>
                        <option value="12">Quetzaltenango</option>
                        <option value="13">Quiché</option>
                        <option value="14">Retalhuleu</option>
                        <option value="15">Sacatepéquez</option>
                        <option value="16">San Marcos</option>
                        <option value="17">Santa Rosa</option>
                        <option value="18">Sololá</option>
                        <option value="19">Suchitepéquez</option>
                        <option value="20">Totonicapán</option>
                        <option value="21">Zacapa</option>
                    </select>                                </div>
            </div>
            <div class="col-md-2">
                <h5>Municipio</h5>
                <div style="text-align: center">
                    <select class="form-control col-md-12" name="nuevo_requerimiento[municipio_<?php echo $num; ?>]" id="nuevo_requerimiento_municipio_<?php echo $num; ?>">
                        <option value="1">Cahabón</option>
                        <option value="2">Chahal</option>
                        <option value="3">Chisec</option>
                        <option value="4">Cobán</option>
                        <option value="5">Fray Bartolomé de las Casas</option>
                        <option value="6">Lanquín</option>
                        <option value="7">Panzós</option>
                        <option value="8">Raxruha</option>
                        <option value="9">San Cristóbal Verapaz</option>
                        <option value="10">San Juan Chamelco</option>
                        <option value="11">San Pedro Carchá</option>
                        <option value="12">Santa Cruz Verapaz</option>
                        <option value="13">Senahú</option>
                        <option value="14">Tactic</option>
                        <option value="15">Tamahú</option>
                        <option value="16">Tucurú</option>
                        <option value="17">Santa Catarina La Tinta</option>
                        <option value="18">Cubulco</option>
                        <option value="19">Granados</option>
                        <option value="20">Purulhá</option>
                        <option value="21">Rabinal</option>
                        <option value="22">Salamá</option>
                        <option value="23">San Jerónimo</option>
                        <option value="24">San Miguel Chicaj</option>
                        <option value="25">Santa Cruz El Chol</option>
                        <option value="26">Acatenango</option>
                        <option value="27">Chimaltenango</option>
                        <option value="28">El Tejar</option>
                        <option value="29">Parramos</option>
                        <option value="30">Patzicía</option>
                        <option value="31">Patzún</option>
                        <option value="32">Pochuta</option>
                        <option value="33">San Andrés Itzapa</option>
                        <option value="34">San José Poaquil</option>
                        <option value="35">San Juan Comalapa</option>
                        <option value="36">San Martín Jilotepeque</option>
                        <option value="37">Santa Apolonia</option>
                        <option value="38">Santa Cruz Balanyá</option>
                        <option value="39">Tecpán Guatemala</option>
                        <option value="40">Yepocapa</option>
                        <option value="41">Zaragoza</option>
                        <option value="42">Camotán</option>
                        <option value="43">Chiquimula</option>
                        <option value="44">Concepción Las Minas</option>
                        <option value="45">Esquipulas</option>
                        <option value="46">Ipala</option>
                        <option value="47">Jocotán</option>
                        <option value="48">Olopa</option>
                        <option value="49">Quezaltepeque</option>
                        <option value="50">San Jacinto</option>
                        <option value="51">San José La Arada</option>
                        <option value="52">San Juan Ermita</option>
                        <option value="53">El Jícaro</option>
                        <option value="54">Guastatoya</option>
                        <option value="55">Morazán</option>
                        <option value="56">San Agustín Acasaguastlán</option>
                        <option value="57">San Antonio La Paz</option>
                        <option value="58">San Cristóbal Acasaguastlán</option>
                        <option value="59">Sanarate</option>
                        <option value="60">Escuintla</option>
                        <option value="61">Guanagazapa</option>
                        <option value="62">Iztapa</option>
                        <option value="63">La Democracia</option>
                        <option value="64">La Gomera</option>
                        <option value="65">Masagua</option>
                        <option value="66">Nueva Concepción</option>
                        <option value="67">Palín</option>
                        <option value="68">San José</option>
                        <option value="69">San Vicente Pacaya</option>
                        <option value="70">Santa Lucía Cotzumalguapa</option>
                        <option value="71">Siquinalá</option>
                        <option value="72">Tiquisate</option>
                        <option value="73">Amatitlán</option>
                        <option value="74">Chinautla</option>
                        <option value="75">Chuarrancho</option>
                        <option value="76">Fraijanes</option>
                        <option value="77">Guatemala City</option>
                        <option value="78">Mixco</option>
                        <option value="79">Palencia</option>
                        <option value="80">Petapa</option>
                        <option value="81">San José del Golfo</option>
                        <option value="82">San José Pinula</option>
                        <option value="83">San Juan Sacatepéquez</option>
                        <option value="84">San Pedro Ayampuc</option>
                        <option value="85">San Pedro Sacatepéquez</option>
                        <option value="86">San Raymundo</option>
                        <option value="87">Santa Catarina Pinula</option>
                        <option value="88">Villa Canales</option>
                        <option value="89">Aguacatán</option>
                        <option value="90">Chiantla</option>
                        <option value="91">Colotenango</option>
                        <option value="92">Concepción Huista</option>
                        <option value="93">Cuilco</option>
                        <option value="94">Huehuetenango</option>
                        <option value="95">Ixtahuacán</option>
                        <option value="96">Jacaltenango</option>
                        <option value="97">La Democracia</option>
                        <option value="98">La Libertad</option>
                        <option value="99">Malacatancito</option>
                        <option value="100">Nentón</option>
                        <option value="101">San Antonio Huista</option>
                        <option value="102">San Gaspar Ixchil</option>
                        <option value="103">San Juan Atitán</option>
                        <option value="104">San Juan Ixcoy</option>
                        <option value="105">San Mateo Ixtatán</option>
                        <option value="106">San Miguel Acatán</option>
                        <option value="107">San Pedro Necta</option>
                        <option value="108">San Rafael La Independencia</option>
                        <option value="109">San Rafael Petzal</option>
                        <option value="110">San Sebastián Coatán</option>
                        <option value="111">San Sebastián Huehuetenango</option>
                        <option value="112">Santa Ana Huista</option>
                        <option value="113">Santa Bárbara</option>
                        <option value="114">Santa Cruz Barillas</option>
                        <option value="115">Santa Eulalia</option>
                        <option value="116">Santiago Chimaltenango</option>
                        <option value="117">Soloma</option>
                        <option value="118">Tectitán</option>
                        <option value="119">Todos Santos Cuchumatan</option>
                        <option value="120">El Estor</option>
                        <option value="121">Livingston</option>
                        <option value="122">Los Amates</option>
                        <option value="123">Morales</option>
                        <option value="124">Puerto Barrios</option>
                        <option value="125">Agua Blanca</option>
                        <option value="126">Asunción Mita</option>
                        <option value="127">Atescatempa</option>
                        <option value="128">Comapa</option>
                        <option value="129">Conguaco</option>
                        <option value="130">El Adelanto</option>
                        <option value="131">El Progreso</option>
                        <option value="132">Jalpatagua</option>
                        <option value="133">Jerez</option>
                        <option value="134">Jutiapa</option>
                        <option value="135">Moyuta</option>
                        <option value="136">Pasaco</option>
                        <option value="137">Quezada</option>
                        <option value="138">San José Acatempa</option>
                        <option value="139">Santa Catarina Mita</option>
                        <option value="140">Yupiltepeque</option>
                        <option value="141">Zapotitlán</option>
                        <option value="142">Dolores</option>
                        <option value="143">Flores</option>
                        <option value="144">La Libertad</option>
                        <option value="145">Melchor de Mencos</option>
                        <option value="146">Poptún</option>
                        <option value="147">San Andrés</option>
                        <option value="148">San Benito</option>
                        <option value="149">San Francisco</option>
                        <option value="150">San José</option>
                        <option value="151">San Luis</option>
                        <option value="152">Santa Ana</option>
                        <option value="153">Sayaxché</option>
                        <option value="154">Las Cruces</option>
                        <option value="155">Almolonga</option>
                        <option value="156">Cabricán</option>
                        <option value="157">Cajolá</option>
                        <option value="158">Cantel</option>
                        <option value="159">Coatepeque</option>
                        <option value="160">Colomba</option>
                        <option value="161">Concepción Chiquirichapa</option>
                        <option value="162">El Palmar</option>
                        <option value="163">Flores Costa Cuca</option>
                        <option value="164">Génova</option>
                        <option value="165">Huitán</option>
                        <option value="166">La Esperanza</option>
                        <option value="167">Olintepeque</option>
                        <option value="168">Ostuncalco</option>
                        <option value="169">Palestina de Los Altos</option>
                        <option value="170">Quetzaltenango</option>
                        <option value="171">Salcajá</option>
                        <option value="172">San Carlos Sija</option>
                        <option value="173">San Francisco La Unión</option>
                        <option value="174">San Martín Sacatepéquez</option>
                        <option value="175">San Mateo</option>
                        <option value="176">San Miguel Sigüilá</option>
                        <option value="177">Sibilia</option>
                        <option value="178">Zunil</option>
                        <option value="179">Canillá</option>
                        <option value="180">Chajul</option>
                        <option value="181">Chicamán</option>
                        <option value="182">Chiché</option>
                        <option value="183">Chichicastenango</option>
                        <option value="184">Chinique</option>
                        <option value="185">Cunén</option>
                        <option value="186">Ixcán</option>
                        <option value="187">Joyabaj</option>
                        <option value="188">Nebaj</option>
                        <option value="189">Pachalum</option>
                        <option value="190">Patzité</option>
                        <option value="191">Sacapulas</option>
                        <option value="192">San Andrés Sajcabajá</option>
                        <option value="193">San Antonio Ilotenango</option>
                        <option value="194">San Bartolomé Jocotenango</option>
                        <option value="195">San Juan Cotzal</option>
                        <option value="196">San Pedro Jocopilas</option>
                        <option value="197">Santa Cruz del Quiché</option>
                        <option value="198">Uspantán</option>
                        <option value="199">Zacualpa</option>
                        <option value="200">Champerico</option>
                        <option value="201">El Asintal</option>
                        <option value="202">Nuevo San Carlos</option>
                        <option value="203">Retalhuleu</option>
                        <option value="204">San Andrés Villa Seca</option>
                        <option value="205">San Felipe</option>
                        <option value="206">San Martín Zapotitlán</option>
                        <option value="207">San Sebastián</option>
                        <option value="208">Santa Cruz Muluá</option>
                        <option value="209">Alotenango</option>
                        <option value="210">Antigua</option>
                        <option value="211">Ciudad Vieja</option>
                        <option value="212">Jocotenango</option>
                        <option value="213">Magdalena Milpas Altas</option>
                        <option value="214">Pastores</option>
                        <option value="215">San Antonio Aguas Calientes</option>
                        <option value="216">San Bartolomé Milpas Altas</option>
                        <option value="217">San Lucas Sacatepéquez</option>
                        <option value="218">San Miguel Dueñas</option>
                        <option value="219">Santa Catarina Barahona</option>
                        <option value="220">Santa Lucía Milpas Altas</option>
                        <option value="221">Santa María de Jesús</option>
                        <option value="222">Santiago Sacatepéquez</option>
                        <option value="223">Santo Domingo Xenacoj</option>
                        <option value="224">Sumpango</option>
                        <option value="225">Ayutla</option>
                        <option value="226">Catarina</option>
                        <option value="227">Comitancillo</option>
                        <option value="228">Concepción Tutuapa</option>
                        <option value="229">El Quetzal</option>
                        <option value="230">El Rodeo</option>
                        <option value="231">El Tumbador</option>
                        <option value="232">Esquipulas Palo Gordo</option>
                        <option value="233">Ixchiguan</option>
                        <option value="234">La Reforma</option>
                        <option value="235">Malacatán</option>
                        <option value="236">Nuevo Progreso</option>
                        <option value="237">Ocos</option>
                        <option value="238">Pajapita</option>
                        <option value="239">Río Blanco</option>
                        <option value="240">San Antonio Sacatepéquez</option>
                        <option value="241">San Cristóbal Cucho</option>
                        <option value="242">San José Ojetenam</option>
                        <option value="243">San Lorenzo</option>
                        <option value="244">San Marcos</option>
                        <option value="245">San Miguel Ixtahuacán</option>
                        <option value="246">San Pablo</option>
                        <option value="247">San Pedro Sacatepéquez</option>
                        <option value="248">San Rafael Pie de La Cuesta</option>
                        <option value="249">San Sibinal</option>
                        <option value="250">Sipacapa</option>
                        <option value="251">Tacaná</option>
                        <option value="252">Tajumulco</option>
                        <option value="253">Tejutla</option>
                        <option value="254">Barberena</option>
                        <option value="255">Casillas</option>
                        <option value="256">Chiquimulilla</option>
                        <option value="257">Cuilapa</option>
                        <option value="258">Guazacapán</option>
                        <option value="259">Nueva Santa Rosa</option>
                        <option value="260">Oratorio</option>
                        <option value="261">Pueblo Nuevo Viñas</option>
                        <option value="262">San Juan Tecuaco</option>
                        <option value="263">San Rafael Las Flores</option>
                        <option value="264">Santa Cruz Naranjo</option>
                        <option value="265">Santa María Ixhuatán</option>
                        <option value="266">Santa Rosa de Lima</option>
                        <option value="267">Taxisco</option>
                        <option value="268">Concepción</option>
                        <option value="269">Nahualá</option>
                        <option value="270">Panajachel</option>
                        <option value="271">San Andrés Semetabaj</option>
                        <option value="272">San Antonio Palopó</option>
                        <option value="273">San José Chacaya</option>
                        <option value="274">San Juan La Laguna</option>
                        <option value="275">San Lucas Tolimán</option>
                        <option value="276">San Marcos La Laguna</option>
                        <option value="277">San Pablo La Laguna</option>
                        <option value="278">San Pedro La Laguna</option>
                        <option value="279">Santa Catarina Ixtahuacan</option>
                        <option value="280">Santa Catarina Palopó</option>
                        <option value="281">Santa Clara La Laguna</option>
                        <option value="282">Santa Cruz La Laguna</option>
                        <option value="283">Santa Lucía Utatlán</option>
                        <option value="284">Santa María Visitación</option>
                        <option value="285">Santiago Atitlán</option>
                        <option value="286">Sololá</option>
                        <option value="287">Chicacao</option>
                        <option value="288">Cuyotenango</option>
                        <option value="289">Mazatenango</option>
                        <option value="290">Patulul</option>
                        <option value="291">Pueblo Nuevo</option>
                        <option value="292">Río Bravo</option>
                        <option value="293">Samayac</option>
                        <option value="294">San Antonio Suchitepéquez</option>
                        <option value="295">San Bernardino</option>
                        <option value="296">San Francisco Zapotitlán</option>
                        <option value="297">San Gabriel</option>
                        <option value="298">San José El Idolo</option>
                        <option value="299">San Juan Bautista</option>
                        <option value="300">San Lorenzo</option>
                        <option value="301">San Miguel Panán</option>
                        <option value="302">San Pablo Jocopilas</option>
                        <option value="303">Santa Bárbara</option>
                        <option value="304">Santo Domingo Suchitepequez</option>
                        <option value="305">Santo Tomas La Unión</option>
                        <option value="306">Zunilito</option>
                        <option value="307">Momostenango</option>
                        <option value="308">San Andrés Xecul</option>
                        <option value="309">San Bartolo</option>
                        <option value="310">San Cristóbal Totonicapán</option>
                        <option value="311">San Francisco El Alto</option>
                        <option value="312">Santa Lucía La Reforma</option>
                        <option value="313">Santa María Chiquimula</option>
                        <option value="314">Totonicapán</option>
                        <option value="315">Cabañas</option>
                        <option value="316">Estanzuela</option>
                        <option value="317">Gualán</option>
                        <option value="318">Huité</option>
                        <option value="319">La Unión</option>
                        <option value="320">Río Hondo</option>
                        <option value="321">San Diego</option>
                        <option value="322">Teculután</option>
                        <option value="323">Usumatlán</option>
                        <option value="324">Zacapa</option>
                    </select>                                </div>
            </div>
            <div class="col-md-2">
                <h5>Zona</h5>
                <div style="text-align: center">
                    <input class="form-control" name="nuevo_requerimiento[zona_<?php echo $num; ?>]" id="nuevo_requerimiento_zona_<?php echo $num; ?>" type="text">                                </div>
            </div>
            <div class="col-md-2">
                <h5>KM</h5>
                <div style="text-align: center">
                    <select class="form-control col-md-10" name="nuevo_requerimiento[km_<?php echo $num; ?>]" id="nuevo_requerimiento_km_<?php echo $num; ?>">
                        <option value="" selected="selected">[Seleccione KM]</option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                        <option value="11">11</option>
                        <option value="12">12</option>
                        <option value="13">13</option>
                        <option value="14">14</option>
                        <option value="15">15</option>
                        <option value="16">16</option>
                        <option value="17">17</option>
                        <option value="18">18</option>
                        <option value="19">19</option>
                        <option value="20">20</option>
                        <option value="21">21</option>
                    </select>                                </div>
            </div>
            <div class="col-md-4">
                <h5>Carretera</h5>
                <div style="text-align: center">
                    <select class="form-control col-md-10" name="nuevo_requerimiento[carretera_<?php echo $num; ?>]" id="nuevo_requerimiento_carretera_<?php echo $num; ?>">
                        <option value="" selected="selected">[Seleccione Carretera]</option>
                        <option value="1">Aguilar Batres</option>
                        <option value="2">CA9</option>
                        <option value="3">CA1</option>
                        <option value="4">Roosevelt</option>
                    </select>                                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <h5>Dirección</h5>
                <div style="text-align: center">
                    <input class="form-control" name="nuevo_requerimiento[direccion_<?php echo $num; ?>]" id="nuevo_requerimiento_direccion_<?php echo $num; ?>" type="text">                                </div>
            </div>
        </div>
    </div>
</div>