<?php



/**
 * Skeleton subclass for performing query and update operations on the 'correo_pendiente' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Sun Jan 28 19:27:33 2018
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class CorreoPendienteQuery extends BaseCorreoPendienteQuery
{
}
