<?php

/**
 * Skeleton subclass for representing a row from the 'direccion_requerimiento' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * 01/10/18 12:30:14
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class DireccionRequerimiento extends BaseDireccionRequerimiento {

    public function getDireccionCompleta() {
        $listado = array();
        $listado[] = trim($this->getZona()) ? "Zona: " . trim($this->getZona()) : null;
        $listado[] = trim($this->getCarretera()) ? "Carretera: " . trim($this->getCarretera()) : null;
        $listado[] = trim($this->getKm()) ? "Km: " . trim($this->getKm()) : null;
        $listado[] = trim($this->getMunicipio()) ? "Muni: " . trim($this->getMunicipio()) : null;
        $listado[] = trim($this->getDepartamento()) ? "Depto: " . trim($this->getDepartamento()) : null;
        $listado[] = trim($this->getDireccion()) ? "Dirección: " . trim($this->getDireccion()) : null;
        $listado = array_filter($listado);
        return implode(", ", $listado);
    }

}
