<?php



/**
 * Skeleton subclass for representing a row from the 'formato_inicial' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Sun Feb 18 23:57:35 2018
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class FormatoInicial extends BaseFormatoInicial
{
}
