<?php



/**
 * Skeleton subclass for performing query and update operations on the 'formato_correo' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Mon Feb  5 12:49:12 2018
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class FormatoCorreoPeer extends BaseFormatoCorreoPeer
{
}
