<?php



/**
 * Skeleton subclass for performing query and update operations on the 'mensaje_negocio' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Mon Feb 26 02:35:56 2018
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class MensajeNegocioQuery extends BaseMensajeNegocioQuery
{
}
