<?php

/**
 * Skeleton subclass for performing query and update operations on the 'negocio' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * 01/14/18 19:18:11
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class NegocioQuery extends BaseNegocioQuery {
    
}
