<?php



/**
 * Skeleton subclass for representing a row from the 'requerimiento' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * 01/10/18 12:30:13
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class Requerimiento extends BaseRequerimiento
{
}
