<?php



/**
 * Skeleton subclass for performing query and update operations on the 'tasa_cambio' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Fri Jan 26 12:03:25 2018
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class TasaCambioPeer extends BaseTasaCambioPeer
{
}
