<?php

/**
 * Skeleton subclass for representing a row from the 'usuario' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * 12/19/17 13:27:31
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class Usuario extends BaseUsuario {

    public function delete(\PropelPDO $con = null) {
        parent::delete($con);
    }

    public function save(\PropelPDO $con = null) {
        if ($this->isNew()) {
            $this->setClave(sha1($this->getClave()));
        }
        parent::save($con);
    }

    static function getValidacionUsuario($tabla = null) {
        $retorno = false;
        if (sfContext::hasInstance()) {
            $user = sfContext::getInstance()->getUser();
            if ($user->isAuthenticated()) {
                if ($user->getAttribute('filtro', null, $tabla) || is_null($user->getAttribute('filtro', null, $tabla))) {
                    $retorno = true;
                } else {
                    $user->setAttribute('filtro', true, $tabla);
                }
            }
        }
        return $retorno;
    }

}
