propel:
  usuario:
    id:                                ~
    usuario:                           { type: varchar(32), required: true , primaryString: true}
    clave:                             { type: varchar(60) }
    correo:                            { type: varchar(255) }
    created_at:                        ~
    updated_at:                        ~
    created_by:                        { type: varchar(32) }
    updated_by:                        { type: varchar(32) }
    activo:                            { type: boolean, default: true }
  