propel:
  usuario:
    id:                                ~
    usuario:                           { type: varchar(32), required: true , primaryString: true}
    clave:                             { type: varchar(60) }
    correo:                            { type: varchar(255) }
    created_at:                        ~
    updated_at:                        ~
    created_by:                        { type: varchar(32) }
    updated_by:                        { type: varchar(32) }
    activo:                            { type: boolean, default: true }
    email:                             { type: varchar(255) }
    numero_telefono:                   { type: varchar(255) }
    perfil_id:                         ~
    
  perfil:
    id:                                ~
    descripcion:                       { type: varchar(255) , primaryString: true}
    activo:                            { type: boolean, default: true }
    created_at:                        ~
    updated_at:                        ~
    created_by:                        { type: varchar(32) }
    updated_by:                        { type: varchar(32) }
  propiedad:
    id:                                 ~
    tipo_operacion:                     { type: varchar(32) }
    tipo_inmueble:                      { type: varchar(32) }
    cantidad_habitacion:                { type: integer }
    cantidad_banio:                     { type: integer }
    cantidad_parqueo:                   { type: integer }
    cantidad_comedor:                   { type: integer }
    cantidad_sala:                      { type: integer }
    cantidad_cocina:                    { type: integer }
    dormitorio_servicio:                { type: boolean, default: false }
    estudio:                            { type: boolean, default: false }
    cisterna:                           { type: boolean, default: false }
    cantidad_jardin:                    { type: integer }
    cantidad_patio:                     { type: integer }
    lavanderia:                         { type: boolean, default: false }
    estado:                             { type: varchar(32) }
    amenidades:                         { type: varchar(255) }
    moneda_id:                          ~
    precio:                             { type: double }
    negociable:                         { type: boolean, default: false }
    incluye_gastos_escritura:           { type: boolean, default: false }
    anio_construccion:                  { type: integer }
    mantenimiento_mensual:              { type: double }
    iusi_semestral:                     { type: double }
    valor_avaluo:                       { type: double }
    mi_comision:                        { type: double }
    comision_compartida:                { type: double }
    nombre_cliente:                     { type: varchar(255) }
    correo_cliente:                     { type: varchar(255) }
    telefono_cliente:                   { type: varchar(25) }
    departamento_id:                    ~
    municipio_id:                       ~
    zona:                               { type: varchar(200) }
    carretera_id:                       ~
    km:                                 { type: varchar(200) }
    direccion:                          { type: varchar(255) }
    seguridad:                          { type: double }
    accesos:                            { type: double }
    agua:                               { type: double }
    transporte_publico:                 { type: double }
    transito_vehicular:                 { type: double }
    comunidades_colidantes:             { type: double }
    areas_recreacion:                   { type: double }
    forma_pago:                         { type: varchar(255) }
    created_at:                         ~
    updated_at:                         ~
    created_by:                         { type: varchar(32) }
    updated_by:                         { type: varchar(32) }
    tiene_luz:                          { type: boolean, default: false }
    tiene_agua:                         { type: boolean, default: false }
    niveles:                            { type: integer }
    area:                               { type: double }
    area_x:                             { type: double }
    area_y:                             { type: double }
  departamento:
    id:                                ~
    descripcion:                       { type: varchar(255) , primaryString: true}
  carretera:
    id:                                ~
    descripcion:                       { type: varchar(255) , primaryString: true}
  municipio:
    id:                                ~
    descripcion:                       { type: varchar(255) , primaryString: true}
    departamento_id:                   ~
  moneda:
    id:                                ~
    descripcion:                       { type: varchar(255) , primaryString: true}
    simbolo:                           { type: varchar(3) , primaryString: true}
    codigo:                            { type: varchar(3) , primaryString: true}