propel:
    
  negocio:
    id:                                 ~
    requerimiento_id:                   { type: integer, foreignTable: requerimiento, foreignReference: id, required: true  }
    propiedad_id:                       { type: integer, foreignTable: propiedad, foreignReference: id, required: true  }    
    usuario_req:                        { type: integer, foreignTable: usuario, foreignReference: id, required: true  }    
    usuario_prop:                       { type: integer, foreignTable: usuario, foreignReference: id, required: true  }    
  direccion_requerimiento:
    id:                                 ~
    requerimiento_id:                   { type: integer, foreignTable: requerimiento, foreignReference: id, required: true  }
    departamento_id:                    { type: integer, foreignTable: departamento, foreignReference: id, required: true  }
    municipio_id:                       { type: integer, foreignTable: municipio, foreignReference: id, required: true  }
    zona:                               { type: varchar(200) }
    carretera_id:                       { type: integer, foreignTable: carretera, foreignReference: id, required: false  }
    km:                                 { type: varchar(200) }
    direccion:                          { type: varchar(255) }
    
  requerimiento:
    id:                                 ~
    tipo_operacion:                     { type: varchar(32) }
    tipo_inmueble:                      { type: varchar(32) }
    cantidad_habitacion:                { type: integer }
    cantidad_banio:                     { type: double  }
    cantidad_parqueo:                   { type: integer }
    cantidad_comedor:                   { type: integer }
    cantidad_sala:                      { type: integer }
    cantidad_cocina:                    { type: integer }
    dormitorio_servicio:                { type: boolean, default: false }
    estudio:                            { type: boolean, default: false }
    cisterna:                           { type: boolean, default: false }
    cantidad_jardin:                    { type: integer }
    cantidad_patio:                     { type: integer }
    lavanderia:                         { type: boolean, default: false }
    tiene_luz:                          { type: boolean, default: false }
    tiene_agua:                         { type: boolean, default: false }
    niveles:                            { type: integer }
    area:                               { type: double }
    area_x:                             { type: double }
    area_y:                             { type: double }
    estado:                             { type: varchar(32) }
    amenidades:                         { type: varchar(255) }
    moneda_id:                          { type: integer, foreignTable: moneda, foreignReference: id, required: true  }
    forma_pago:                         { type: varchar(255) }
    presupuesto_min:                    { type: double }
    presupuesto_max:                    { type: double }
    nombre_cliente:                     { type: varchar(255) }
    correo_cliente:                     { type: varchar(255) }
    telefono_cliente:                   { type: varchar(25) }
    estatus:                            { type: varchar(25), default: "Disponible"}
    precalificacion:                    { type: boolean }
    nucleo_familiar:                    { type: integer }
#    moneda_ingreso:                     { type: integer, foreignTable: moneda, foreignReference: id, required: true  }
    ingresos:                           { type: double }
#    moneda_egresos:                     { type: integer, foreignTable: moneda, foreignReference: id, required: true  }
    egresos:                            { type: double }
    enganche:                           { type: double }
    tasa_interes_anual:                 { type: double }
    plazo_en_anios:                     { type: double }
    plazo_en_meses:                     { type: double }
    monto_financiar_maximo:             { type: double }
    cuota_total_mensual_maxima:         { type: double }
    created_at:                        ~
    updated_at:                        ~
    created_by:                        { type: varchar(32) }
    updated_by:                        { type: varchar(32) }
    usuario_id:                        ~
    cantidad_oficina:                   { type: integer }
    
  propiedad_imagen:
    id:                                ~
    propiedad_id:                      { type: integer, foreignTable: propiedad, foreignReference: id, required: true  }
    nombre_original:                   { type: varchar(255) , primaryString: true}
    nombre_actual:                     { type: varchar(255) , primaryString: true}
    created_at:                        ~
    updated_at:                        ~
    created_by:                        { type: varchar(32) }
    updated_by:                        { type: varchar(32) }
              
  usuario:
    id:                                ~
    usuario:                           { type: varchar(32), required: true , primaryString: true}
    clave:                             { type: varchar(60) }
    correo:                            { type: varchar(255) }
    created_at:                        ~
    updated_at:                        ~
    created_by:                        { type: varchar(32) }
    updated_by:                        { type: varchar(32) }
    activo:                            { type: boolean, default: true }
    email:                             { type: varchar(255) }
    numero_telefono:                   { type: varchar(255) }
    perfil_id:                         { type: integer, foreignTable: perfil, foreignReference: id, required: true  }
    administrador:                     { type: boolean, default: false }
    nombre_completo:                   { type: varchar(255) }
    
  perfil:
    id:                                ~
    descripcion:                       { type: varchar(255) , primaryString: true}
    activo:                            { type: boolean, default: true }
    created_at:                        ~
    updated_at:                        ~
    created_by:                        { type: varchar(32) }
    updated_by:                        { type: varchar(32) }
    
  propiedad:
    id:                                 ~
    tipo_operacion:                     { type: varchar(32) }
    tipo_inmueble:                      { type: varchar(32) }
    cantidad_habitacion:                { type: integer }
    cantidad_banio:                     { type: double }
    cantidad_parqueo:                   { type: integer }
    cantidad_comedor:                   { type: integer }
    cantidad_sala:                      { type: integer }
    cantidad_cocina:                    { type: integer }
    dormitorio_servicio:                { type: boolean, default: false }
    estudio:                            { type: boolean, default: false }
    cisterna:                           { type: boolean, default: false }
    cantidad_jardin:                    { type: integer }
    cantidad_patio:                     { type: integer }
    lavanderia:                         { type: boolean, default: false }
    estado:                             { type: varchar(32) }
    amenidades:                         { type: varchar(255) }
    moneda_id:                          { type: integer, foreignTable: moneda, foreignReference: id, required: true  }
    precio:                             { type: double }
    negociable:                         { type: boolean, default: false }
    incluye_gastos_escritura:           { type: boolean, default: false }
    anio_construccion:                  { type: integer }
    mantenimiento_mensual:              { type: double }
    iusi_semestral:                     { type: double }
    valor_avaluo:                       { type: double }
    mi_comision:                        { type: double }
    comision_compartida:                { type: double }
    nombre_cliente:                     { type: varchar(255) }
    correo_cliente:                     { type: varchar(255) }
    telefono_cliente:                   { type: varchar(25) }
    departamento_id:                    { type: integer, foreignTable: departamento, foreignReference: id, required: true  }
    municipio_id:                       { type: integer, foreignTable: municipio, foreignReference: id, required: true  }
    zona:                               { type: varchar(200) }
    carretera_id:                       { type: integer, foreignTable: carretera, foreignReference: id, required: false  }
    km:                                 { type: varchar(200) }
    direccion:                          { type: varchar(255) }
    seguridad:                          { type: double }
    accesos:                            { type: double }
    agua:                               { type: double }
    transporte_publico:                 { type: double }
    transito_vehicular:                 { type: double }
    comunidades_colidantes:             { type: double }
    areas_recreacion:                   { type: double }
    forma_pago:                         { type: varchar(255) }
    created_at:                         ~
    updated_at:                         ~
    created_by:                         { type: varchar(32) }
    updated_by:                         { type: varchar(32) }
    tiene_luz:                          { type: boolean, default: false }
    tiene_agua:                         { type: boolean, default: false }
    niveles:                            { type: integer }
    area:                               { type: double }
    area_x:                             { type: double }
    area_y:                             { type: double }
    estatus:                            { type: varchar(25), default: "Disponible" }
    usuario_id:                         ~
    cantidad_oficina:                   { type: integer }
    
  municipio:
    id:                                ~
    descripcion:                       { type: varchar(255) , primaryString: true}
    departamento_id:                   { type: integer, foreignTable: departamento, foreignReference: id, required: true  }    
    
  departamento:
    id:                                ~
    descripcion:                       { type: varchar(255) , primaryString: true}
    
  carretera:
    id:                                ~
    descripcion:                       { type: varchar(255) , primaryString: true}
        
  moneda:
    id:                                ~
    descripcion:                       { type: varchar(255) , primaryString: true}
    simbolo:                           { type: varchar(3) , primaryString: true}
    codigo:                            { type: varchar(3) , primaryString: true}
  tasa_cambio:
    id:                                ~
    moneda_origen:                     { type: integer, foreignTable: moneda, foreignReference: id, required: true  }    
    moneda_destino:                    { type: integer, foreignTable: moneda, foreignReference: id, required: true  }    
    monto:                             { type: float }
  token:
    id:                                ~
    usuario_id:                        { type: integer, foreignTable: usuario, foreignReference: id, required: true  }    
    token:                             { type: varchar(255) , primaryString: true}
    created_at:                         ~
    updated_at:                         ~
    utilizado:                         { type: boolean, default: false }
    tipo:                              { type: varchar(255) }
  correo_pendiente:
    id:                                ~
    asunto:                            { type: varchar(255) }
    contenido:                         { type: longvarchar }
    beneficiario:                      { type: longvarchar }
    enviado:                           { type: boolean, default: false }
  configuracion:
    id:                                ~
    host:                              { type: varchar(255) }
    encriptacion:                      { type: varchar(255) }
    puerto:                            { type: varchar(255) }
    usuario:                           { type: varchar(255) }
    clave:                             { type: varchar(255) }
  formato_correo:
    id:                                ~
    tipo:                              { type: varchar(255) }
    contenido:                         { type: longvarchar }
    
  formato_inicial:
    id:                                ~
    contenido:                         { type: longvarchar }
  mensaje_negocio:
    id:                                ~
    negocio_id:                        ~
    usuario_id:                        ~
    mensaje:                           { type: longvarchar }
    created_at:                        ~
    updated_at:                        ~
    visto:                             { type: boolean, default: false }
  banco:
    id:                                ~
    descripcion:                       { type: varchar(255), primaryString: true}
    relacion_cuota_interes:            { type: double }
    seguro_banco:                      { type: double }
    factor_construccion:               { type: double }
    created_at:                        ~
    updated_at:                        ~