<?php

/**
 * Propiedad filter form base class.
 *
 * @package    plan
 * @subpackage filter
 * @author     Via
 */
abstract class BasePropiedadFormFilter extends BaseFormFilterPropel
{
  public function setup()
  {
    $this->setWidgets(array(
      'tipo_operacion'           => new sfWidgetFormFilterInput(),
      'tipo_inmueble'            => new sfWidgetFormFilterInput(),
      'cantidad_habitacion'      => new sfWidgetFormFilterInput(),
      'cantidad_banio'           => new sfWidgetFormFilterInput(),
      'cantidad_parqueo'         => new sfWidgetFormFilterInput(),
      'cantidad_comedor'         => new sfWidgetFormFilterInput(),
      'cantidad_sala'            => new sfWidgetFormFilterInput(),
      'cantidad_cocina'          => new sfWidgetFormFilterInput(),
      'dormitorio_servicio'      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'estudio'                  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'cisterna'                 => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'cantidad_jardin'          => new sfWidgetFormFilterInput(),
      'cantidad_patio'           => new sfWidgetFormFilterInput(),
      'lavanderia'               => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'estado'                   => new sfWidgetFormFilterInput(),
      'amenidades'               => new sfWidgetFormFilterInput(),
      'moneda_id'                => new sfWidgetFormPropelChoice(array('model' => 'Moneda', 'add_empty' => true)),
      'precio'                   => new sfWidgetFormFilterInput(),
      'negociable'               => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'incluye_gastos_escritura' => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'anio_construccion'        => new sfWidgetFormFilterInput(),
      'mantenimiento_mensual'    => new sfWidgetFormFilterInput(),
      'iusi_semestral'           => new sfWidgetFormFilterInput(),
      'valor_avaluo'             => new sfWidgetFormFilterInput(),
      'mi_comision'              => new sfWidgetFormFilterInput(),
      'comision_compartida'      => new sfWidgetFormFilterInput(),
      'nombre_cliente'           => new sfWidgetFormFilterInput(),
      'correo_cliente'           => new sfWidgetFormFilterInput(),
      'telefono_cliente'         => new sfWidgetFormFilterInput(),
      'departamento_id'          => new sfWidgetFormPropelChoice(array('model' => 'Departamento', 'add_empty' => true)),
      'municipio_id'             => new sfWidgetFormPropelChoice(array('model' => 'Municipio', 'add_empty' => true)),
      'zona'                     => new sfWidgetFormFilterInput(),
      'carretera_id'             => new sfWidgetFormPropelChoice(array('model' => 'Carretera', 'add_empty' => true)),
      'km'                       => new sfWidgetFormFilterInput(),
      'direccion'                => new sfWidgetFormFilterInput(),
      'seguridad'                => new sfWidgetFormFilterInput(),
      'accesos'                  => new sfWidgetFormFilterInput(),
      'agua'                     => new sfWidgetFormFilterInput(),
      'transporte_publico'       => new sfWidgetFormFilterInput(),
      'transito_vehicular'       => new sfWidgetFormFilterInput(),
      'comunidades_colidantes'   => new sfWidgetFormFilterInput(),
      'areas_recreacion'         => new sfWidgetFormFilterInput(),
      'forma_pago'               => new sfWidgetFormFilterInput(),
      'created_at'               => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate())),
      'updated_at'               => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate())),
      'created_by'               => new sfWidgetFormFilterInput(),
      'updated_by'               => new sfWidgetFormFilterInput(),
      'tiene_luz'                => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'tiene_agua'               => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'niveles'                  => new sfWidgetFormFilterInput(),
      'area'                     => new sfWidgetFormFilterInput(),
      'area_x'                   => new sfWidgetFormFilterInput(),
      'area_y'                   => new sfWidgetFormFilterInput(),
      'estatus'                  => new sfWidgetFormFilterInput(),
      'usuario_id'               => new sfWidgetFormPropelChoice(array('model' => 'Usuario', 'add_empty' => true)),
      'cantidad_oficina'         => new sfWidgetFormFilterInput(),
    ));

    $this->setValidators(array(
      'tipo_operacion'           => new sfValidatorPass(array('required' => false)),
      'tipo_inmueble'            => new sfValidatorPass(array('required' => false)),
      'cantidad_habitacion'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'cantidad_banio'           => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'cantidad_parqueo'         => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'cantidad_comedor'         => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'cantidad_sala'            => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'cantidad_cocina'          => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'dormitorio_servicio'      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'estudio'                  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'cisterna'                 => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'cantidad_jardin'          => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'cantidad_patio'           => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'lavanderia'               => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'estado'                   => new sfValidatorPass(array('required' => false)),
      'amenidades'               => new sfValidatorPass(array('required' => false)),
      'moneda_id'                => new sfValidatorPropelChoice(array('required' => false, 'model' => 'Moneda', 'column' => 'id')),
      'precio'                   => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'negociable'               => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'incluye_gastos_escritura' => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'anio_construccion'        => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'mantenimiento_mensual'    => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'iusi_semestral'           => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'valor_avaluo'             => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'mi_comision'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'comision_compartida'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'nombre_cliente'           => new sfValidatorPass(array('required' => false)),
      'correo_cliente'           => new sfValidatorPass(array('required' => false)),
      'telefono_cliente'         => new sfValidatorPass(array('required' => false)),
      'departamento_id'          => new sfValidatorPropelChoice(array('required' => false, 'model' => 'Departamento', 'column' => 'id')),
      'municipio_id'             => new sfValidatorPropelChoice(array('required' => false, 'model' => 'Municipio', 'column' => 'id')),
      'zona'                     => new sfValidatorPass(array('required' => false)),
      'carretera_id'             => new sfValidatorPropelChoice(array('required' => false, 'model' => 'Carretera', 'column' => 'id')),
      'km'                       => new sfValidatorPass(array('required' => false)),
      'direccion'                => new sfValidatorPass(array('required' => false)),
      'seguridad'                => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'accesos'                  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'agua'                     => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'transporte_publico'       => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'transito_vehicular'       => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'comunidades_colidantes'   => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'areas_recreacion'         => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'forma_pago'               => new sfValidatorPass(array('required' => false)),
      'created_at'               => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDate(array('required' => false)))),
      'updated_at'               => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDate(array('required' => false)))),
      'created_by'               => new sfValidatorPass(array('required' => false)),
      'updated_by'               => new sfValidatorPass(array('required' => false)),
      'tiene_luz'                => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'tiene_agua'               => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'niveles'                  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'area'                     => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'area_x'                   => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'area_y'                   => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'estatus'                  => new sfValidatorPass(array('required' => false)),
      'usuario_id'               => new sfValidatorPropelChoice(array('required' => false, 'model' => 'Usuario', 'column' => 'id')),
      'cantidad_oficina'         => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
    ));

    $this->widgetSchema->setNameFormat('propiedad_filters[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    parent::setup();
  }

  public function getModelName()
  {
    return 'Propiedad';
  }

  public function getFields()
  {
    return array(
      'id'                       => 'Number',
      'tipo_operacion'           => 'Text',
      'tipo_inmueble'            => 'Text',
      'cantidad_habitacion'      => 'Number',
      'cantidad_banio'           => 'Number',
      'cantidad_parqueo'         => 'Number',
      'cantidad_comedor'         => 'Number',
      'cantidad_sala'            => 'Number',
      'cantidad_cocina'          => 'Number',
      'dormitorio_servicio'      => 'Boolean',
      'estudio'                  => 'Boolean',
      'cisterna'                 => 'Boolean',
      'cantidad_jardin'          => 'Number',
      'cantidad_patio'           => 'Number',
      'lavanderia'               => 'Boolean',
      'estado'                   => 'Text',
      'amenidades'               => 'Text',
      'moneda_id'                => 'ForeignKey',
      'precio'                   => 'Number',
      'negociable'               => 'Boolean',
      'incluye_gastos_escritura' => 'Boolean',
      'anio_construccion'        => 'Number',
      'mantenimiento_mensual'    => 'Number',
      'iusi_semestral'           => 'Number',
      'valor_avaluo'             => 'Number',
      'mi_comision'              => 'Number',
      'comision_compartida'      => 'Number',
      'nombre_cliente'           => 'Text',
      'correo_cliente'           => 'Text',
      'telefono_cliente'         => 'Text',
      'departamento_id'          => 'ForeignKey',
      'municipio_id'             => 'ForeignKey',
      'zona'                     => 'Text',
      'carretera_id'             => 'ForeignKey',
      'km'                       => 'Text',
      'direccion'                => 'Text',
      'seguridad'                => 'Number',
      'accesos'                  => 'Number',
      'agua'                     => 'Number',
      'transporte_publico'       => 'Number',
      'transito_vehicular'       => 'Number',
      'comunidades_colidantes'   => 'Number',
      'areas_recreacion'         => 'Number',
      'forma_pago'               => 'Text',
      'created_at'               => 'Date',
      'updated_at'               => 'Date',
      'created_by'               => 'Text',
      'updated_by'               => 'Text',
      'tiene_luz'                => 'Boolean',
      'tiene_agua'               => 'Boolean',
      'niveles'                  => 'Number',
      'area'                     => 'Number',
      'area_x'                   => 'Number',
      'area_y'                   => 'Number',
      'estatus'                  => 'Text',
      'usuario_id'               => 'ForeignKey',
      'cantidad_oficina'         => 'Number',
    );
  }
}
